### ISSUE TITLE
Make Checkbox label wrapper a div

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#1028]
Currently the `labelText` slot content is wrapped in a `<span>`. This limits the valid label content to [phrasing content ](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2) while using a `<div>` would allow [flow content](https://html.spec.whatwg.org/multipage/dom.html#flow-content-2) as well.

This limitation seems unnecessary because the layout is done using flexbox anyway (see class `bx--checkbox-label`). So the default display type of these elements (block vs. inline) should not matter.

**Comment by metonym** [comment]
I ran into this when implementing a slottable `MultiSelect` (#1183); I wanted the slot to span multiple lines.

As a workaround, I had to apply a global style that set `display: block` on the `span` element:

```css
:global(.bx--checkbox-label-text) {
  display: block;
}
```

Although `<label><div /></label>` does not throw Lighthouse accessibility warnings, unfortunately I don't think have a `div` as a child of `label` is valid HTML, [per the spec](https://html.spec.whatwg.org/multipage/forms.html#the-label-element) ([StackOverflow answer](https://stackoverflow.com/a/18609649)).

**Comment by brunnerh** [comment]
You are correct, maybe I accidentally looked at the `Categories` instead of the `Content model` when I looked up the spec at the time.

```
Categories:
  Flow content.
  Phrasing content.
  Interactive content.
  Palpable content.
```

I know that I have made that error before...

Should close this for now then.
