### ISSUE TITLE
NumberInput never empty

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#1031]
The `value` property accepts both `undefined` and `""` as values, but the `input` always gets initialized to `0`. This is true even if `allowEmpty` is set.

This can be undesirable if there is no sensible default and one wants to present an empty input, clearly signaling that no value has been set yet.

[REPL](https://svelte.dev/repl/603f453d86e7499ca87e53d4d9d0562f?version=3.46.2)

**Comment by metonym** [comment]
Fixed in [v0.55.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.55.0)
