### ISSUE TITLE
`NumberInput` change event data or type is off

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#1039]
The `change` event dispatches the `value` property as its payload.
The event is typed as `number`, the property as `number | string`.

`value`, can implicitly be `undefined` as well, maybe that needs to be considered, too.

**Comment by metonym** [comment]
Just a thought: `null` is perhaps a better value to signify "no value" than an empty string or undefined.

**Comment by brunnerh** [comment]
I agree. When the component already exposes the value in a parsed form, then no longer having any string values would be best.

Currently I have to manually convert the empty value so my server-side validation does not fail because it expects the JSON property to contain a `number` or be `undefined`.

Of course that would be a breaking change, but this is still in 0.x anyway, so...
