### ISSUE TITLE
Correct way to wrap a Carbon component in typescript?

### ISSUE THREAD

**Issue by ambiguous48** [carbon-design-system/carbon-components-svelte#1041]
Often, I find myself needing to wrap the existing Carbon components with my own custom ones. But whenever I do so, I get the following typescript error:

`Types of property 'slot' are incompatible.`

Is there a way to get around this? I've tried fiddling with typescript's utility types (NonNullable<T>, Exclude<T>, etc) but with no luck. I did manage to override the `slot` property to match the signature. However, typescript gave me a very similar error but with `HtmlInputElement` instead of `slots`.

Note: The functionality is working flawlessly as far as I can tell, but I have a bunch of typescript errors in my project that I'm not sure how to remove. 

```html
// MyCustomComboBox.svelte

<script lang="ts">
  import ComboBox from 'carbon-components-svelte/src/ComboBox/ComboBox.svelte';
  import type { ComboBoxProps } from 'carbon-components-svelte/types/ComboBox/ComboBox.svelte';

  export let comboBoxProps: ComboBoxProps;
</script>

<ComboBox
  {...comboBoxProps}  // Error here
/>
```

```html
// AnotherComponent.svelte

<script lang="ts">
  import MyCustomComboBox from 'MyCustomComboBox.svelte';
</script>

<MyCustomComboBox
  comboBoxProps={{
    placeholder: 'SomeText',  // intellisense works here
  }}
/>
```

![image](https://user-images.githubusercontent.com/33713262/150973045-8f0d5588-0e8f-4a5e-a9e7-c9116a5ee04d.png)

**Comment by metonym** [comment]
I can repro these errors in TypeScript strict mode.

Regarding the "IntrinsicAttributes... types of property 'slot' are incompatible" error, the `ComboBoxProps` interface extends the attributes for the "input" element to account for $$restProps:

https://github.com/carbon-design-system/carbon-components-svelte/blob/e37b632fef36f027c62dbc206b7c0671ceec48fc/types/ComboBox/ComboBox.svelte.d.ts#L11-L12

One workaround is to manually pick props from `ComboBoxProps`:

```ts
export let comboBoxProps: Pick<ComboBoxProps, "itemToString"> = {
  itemToString: (item) => item.text,
};
```

However, it doesn't work with the `ref` or `listRef` props, which you will need to bind manually:

```svelte
<script>
  /** ... */
  export let ref: null | HTMLInputElement = null;
</script>

<ComboBox {...comboBoxProps} bind:ref />
```

**Comment by ambiguous48** [comment]
Thank you, my typescript compiler is happy again.
