### ISSUE TITLE
Modal button icons

### ISSUE THREAD

**Issue by gregorw** [carbon-design-system/carbon-components-svelte#1048]
We would like to use a primary button _icon_ in modals.

In Carbon Design System buttons already have icons. Modals have buttons most of the time. So, this seems to be a logic addition. The [guidelines](https://www.carbondesignsystem.com/components/modal/usage/) do not cover this, though. The closest thing I could find was a [loading indicator on a modal button](https://www.carbondesignsystem.com/components/modal/usage/#loading).

<img width="454" alt="image" src="https://user-images.githubusercontent.com/988276/151658377-7ffc2f03-8259-42d8-916d-5a2ed31d50f6.png">

What we want is this:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/988276/151657362-81106160-d679-4005-b1b3-10aaf44beecf.png">

What do you think?

I have already implemented this in #1047.

**Comment by metonym** [comment]
Agreed – thank you for taking the time to research the Carbon guidelines. I prefer the proposed design of #1047

**Comment by metonym** [comment]
Closed by #1047

Released in [v0.57.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.57.0)
