### ISSUE TITLE
NumberInput not binding `null` and defaulting to `0`

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#1050]
The null check introduced in the recent fix (https://github.com/carbon-design-system/carbon-components-svelte/commit/402de56029f6c400df335e8182be65c79cc5dd9f) is invalid due to the fact that an input's value is always a string.

This causes `''` to be coerced to `0` instead of returning `null`.

[REPL](https://svelte.dev/repl/7408eee2e9f044269504e6e99dd6aa96?version=3.46.3)

**Comment by metonym** [comment]
Fixed in [v0.57.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.57.0).
