### ISSUE TITLE
Align NumberInput events with native inputs?

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#1052]
Currently `change` fires on input and the `input` event is simply forwarded (i.e. does not parse).

For the native inputs the firing semantics are:
- [`change`](https://html.spec.whatwg.org/multipage/indices.html#event-change): Fired at controls when the user commits a value change
- [`input`](https://html.spec.whatwg.org/multipage/indices.html#event-input): Fired at controls when the user changes the value

It would be nice if the component only fires `change` at the same time the input fires `change` in case uncommitted value changes are not of interest. Also, both `input` and `change` should provide the parsed value (`string` => `number | null`).

(Steppers should fire `change` and `input`, the native steppers do that as well.)

[REPL illustrating differences](https://svelte.dev/repl/6193507d3aea47dfbbddc0db381df6bd?version=3.46.3)

**Comment by metonym** [comment]
Great observation – Agreed 💯

**Comment by metonym** [comment]
Released in [v0.57.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.57.0).
