### ISSUE TITLE
MultiSelect docus bug

### ISSUE THREAD

**Issue by dmitriym09** [carbon-design-system/carbon-components-svelte#1054]
I found a bug: MultiSelect inside Content doesn't lose focus.

Thanks for the cool library!

**Comment by metonym** [comment]
Would you mind providing a minimal repro?

I have a REPL here but am unable to repro what you're describing:

https://svelte.dev/repl/e1c98a8ee79c49779610bfa359896224?version=3.46.4

**Comment by metonym** [comment]
Related #938, #848

**Comment by metonym** [comment]
Fixed in [v0.58.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.58.0)
