### ISSUE TITLE
TooltipDefinition button defaults to submit

### ISSUE THREAD

**Issue by tmarsik42** [carbon-design-system/carbon-components-svelte#1055]
TooltipDefinition button element defaults to type submit and while it is possible to solve this by binding to ref and changing type,  with multiple definitions, this gets quite irritating.

This behavior is unintuitive due to general use case of TooltipDefinition, and is a source of various bugs.

Eg.: Survey form with introduction, where you have TooltipDefinition explaining... well, definition. And accidentally clicking it, would submit the survey.

Would it be possible to change TooltipDefinition button type to "button" or make a property for it?

**Comment by metonym** [comment]
Nice catch – this is definitely a bug.

The [upstream React implementation](https://github.com/carbon-design-system/carbon/blob/60d75183440f0a0e93e5211860a884a98ba1b54c/packages/react/src/components/TooltipDefinition/TooltipDefinition.js#L89) has an explicit `type="button"` set.

**Comment by metonym** [comment]
Fixed in [v0.57.1](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.57.1)
