### ISSUE TITLE
How do I correctly use a different font?

### ISSUE THREAD

**Issue by canyonwater** [carbon-design-system/carbon-components-svelte#1059]
Hi, 
I use Carbon Components Svelte with SvelteKit, I want to use IBM Plex Sans Arabic instead of the default configured font of Carbon Components Svelte.
Where should I write the style code and how?
Does Carbon Components Svelte support IBM Plex Sans Arabic by itself?

This is my current code but it my `font-family` does not get applied and does not overwrite the Carbon Components Svelte's font.

```
@import "carbon-components-svelte/css/white.css";
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@200;400;600&display=swap');

* {
    font-family: 'IBM Plex Sans Arabic', sans-serif;
}
```

Thanks.

**Comment by metonym** [comment]
In your example, can you try applying the custom font declaration to the `body` selector?

```css
body {
  font-family: 'IBM Plex Sans Arabic', sans-serif;
}
```

Reference: Carbon guide on [IBM Plex](https://github.com/carbon-design-system/carbon/blob/580ea3e50bc2aa51cd44b36ae5ababaff179fc3e/docs/guides/ibm-plex.md).
