### ISSUE TITLE
Why is the name of every checkbox input in MultiSelect component the same as its label ?

### ISSUE THREAD

**Issue by alkanna** [carbon-design-system/carbon-components-svelte#1060]
On the `MultiSelect` component, every `checkbox` input has its `name` property set to the content of the label just beneath it (the displayed value of the choice in the list).
Shouldn't there be a `itemToName` prop exported like the `itemToString` prop, and take the item `id` by default for its name ?

This currently clashes hard with libraries such as Felte, where an object is built out of all the content of a form.
Right now, my workaround is to put my `MultiSelect` in a separate `fieldset` and delete those from my data object before submitting it, but I think I should be able to use the this component natively here.

**Comment by metonym** [comment]
It seems that React implementation actually no longer uses the `input` element for MultiSelect fields.

https://github.com/carbon-design-system/carbon/blob/5bf32f92f233f78823f8cf1b222cae038f3e13ef/packages/react/src/components/MultiSelect/MultiSelect.js#L301

I'll take a look into aligning this.

**Comment by alkanna** [comment]
Interesting, I'm not too familiar with React so I wouldn't know why that is.
But it you're okay with the proposition I made I can maybe draft a PR and propose an alignment ?

**Comment by metonym** [comment]
PRs welcome

**Comment by metonym** [comment]
Supported in [v0.58.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.58.0).

Use the `itemToInput` prop to customize the name, title, and labelText values.

```svelte
<MultiSelect
  filterable
  titleText="Contact"
  label="Select contact methods..."
  itemToInput={(item) => ({
    name: "name: " + item.id,
    labelText: "label: " + item.text,
    title: "title: " + item.text,
  })}
  items={[
    { id: "0", text: "Slack" },
    { id: "1", text: "Email" },
    { id: "2", text: "Fax" },
  ]}
/>
```
