### ISSUE TITLE
DataTable sorting indicator appears in wrong TableColumnHead

### ISSUE THREAD

**Issue by berndfuhrmann** [carbon-design-system/carbon-components-svelte#1062]
Demo of problem:
https://svelte.dev/repl/3a27073d9b4f48f383b90c1dfd7395e2?version=3.46.3

Steps to reproduce:
1. load REPL
2. click on table header "Name"
3. Sorting indicator appear in column "Rule" instead of "Name"

Version tested: 0.57.1

**Comment by metonym** [comment]
Nice find – the reactivity of the `headers` prop is buggy
