### ISSUE TITLE
`HeaderNavMenu` does not close if item is activated using Enter

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#1067]
On click the menu closes, on Enter it stays open. This probably should behave the same way.

[REPL](https://svelte.dev/repl/994386a473c74fd69edbd23788c90290?version=3.46.4)

**Comment by metonym** [comment]
Fixed in [v0.58.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.58.0)
