### ISSUE TITLE
TableCell TypeError: Cannot read properties of null (reading 'removeChild')

### ISSUE THREAD

**Issue by datasushi** [carbon-design-system/carbon-components-svelte#1082]
Hi folks,

let me start by saying that I really love working with Carbon on Svelte, thanks a lot for the solid framework!

I have run into an issue while making DataTable editable. Please consider [this REPL](https://svelte.dev/repl/10cf7c33b0974829b00432164fe3b137?version=3.46.4). You can trigger the issue by clicking the "A" in the "Messages" column, deleting it, and then removing the focus.

I have found that the if/else block on lines 46-50 in combination with the on:blur and on:select functions causes the issue and results in the following error message:
`TypeError: Cannot read properties of null (reading 'removeChild')`

Not sure if this is by design or a bug. 

Cheers

**Comment by metonym** [comment]
Hi there – thank you for providing a REPL.

I don't think the runtime error is from Carbon, but rather the if/else statements inside the contenteditable interferes with how Svelte manipulates the DOM. See https://github.com/sveltejs/svelte/issues/4978

I think that the best way is to bind to `textContent` and use the `on:blur` event to modify the value after the fact. This would support your use case of changing the value to "✏️" if no value is provided.

One downside is that by using two-binding, `data` will be updated on every keystroke.

You'll notice the "rowIndex" prop from; this will be added in #1086 to more easily reference the original data.

```svelte
<script>
  import { DataTable, Dropdown } from "carbon-components-svelte";

  let data = [
    {
      id: "1",
      message: "A",
      action: "0",
    },
    {
      id: "2",
      message: "B",
      action: "1",
    },
  ];

  let headers = [
    { key: "id", value: "ID" },
    { key: "message", value: "Message" },
    { key: "action", value: "Action" },
  ];
</script>

<DataTable bind:rows={data} {headers}>
  <svelte:fragment slot="cell" let:cell let:rowIndex>
    {#if cell.key === "action"}
      <Dropdown
        type="inline"
        bind:selectedId={data[rowIndex].action}
        items={[
          { id: "0", text: "Choose 1" },
          { id: "1", text: "Choose 2" },
        ]}
      />
    {:else if cell.key === "message"}
      <div
        spellcheck="false"
        contenteditable="true"
        bind:textContent={data[rowIndex].message}
        on:blur={() => {
          if (data[rowIndex].message.length === 0) {
            data[rowIndex].message = "✏️";
          }
        }}
      />
    {:else}
      {cell.value}
    {/if}
  </svelte:fragment>
</DataTable>

<pre>
  {JSON.stringify(data, null, 2)}
</pre>
```

**Comment by metonym** [comment]
`DataTable` now passes `rowIndex` and `cellIndex` to the "cell" slot in [v0.58.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.58.0).

**Comment by datasushi** [comment]
Thanks a lot!
