### ISSUE TITLE
Setting selectedRowIds to [] should reset  batch selection checkbox

### ISSUE THREAD

**Issue by datasushi** [carbon-design-system/carbon-components-svelte#1083]
Hi,

trying to do batch actions and remove selection upon completion. Currently trying via:
`selectedRowIds = []`

[REPL for reference.](https://svelte.dev/repl/0c8c9c9a92d24543b22f0461ee01f32d?version=3.46.4)

Unfortunately the batch selection checkbox remains checked. How do you reset the checkbox?

Thanks

**Comment by metonym** [comment]
Fixed in [v0.58.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.58.0)
