### ISSUE TITLE
Feature Request: "Search" Button for the search component

### ISSUE THREAD

**Issue by datasushi** [carbon-design-system/carbon-components-svelte#1097]
Hi,

it would be great to have a "Search" button in the search component, identical to the clear button in behaviour,

Cheers

**Comment by metonym** [comment]
I would recommend using the `Button` in conjunction with `Search`, and wrapping both in a form to capture the "submit on enter" behavior.

You can apply a style to display the `Search` and `Button` in the same row.

In the following example, `value` will be printed when:

- pressing "Enter" if the input is focused
- clicking the "Search" button

```svelte
<script>
  import { Search, Button } from "carbon-components-svelte";

  let value = "";
</script>

<form
  on:submit|preventDefault={() => {
    console.log("value", value);
  }}
>
  <div style="display: flex">
    <Search bind:value />
    <Button type="Submit">Search</Button>
  </div>
</form>

```

**Comment by datasushi** [comment]
That definitely works as well. Doesn't align nicely with vanilla themes but that's an easy fix. Thanks!
