### ISSUE TITLE
`StructuredList`'s `overflow-y: hidden`  results in hiding Tooltips (Safari)

### ISSUE THREAD

**Issue by tmarsik42** [carbon-design-system/carbon-components-svelte#1106]
`StructuredList` has a CSS property `overflow-y: hidden` that hides floating components like Tooltip.
I thought it's intended at first, but noticed it behaves this way only in Safari.

IMHO overflowing floating elements should be visible by default. I'm more curious about which behavior is intentional though?

Default behavior of `TooltipDefinition` in column of `StructuredList` at the last row (Safari)
<img width="276" alt="Snímek obrazovky 2022-02-18 v 11 50 27" src="https://user-images.githubusercontent.com/95856146/154668928-eee64f43-a42c-41c7-b5c9-2cb54a934bb5.png">
</figure>

Expected behavior of `TooltipDefinition` in column of `StructuredList` at the last row (this is how it works in Chrome and Firefox)
<img width="269" alt="Snímek obrazovky 2022-02-18 v 11 57 15" src="https://user-images.githubusercontent.com/95856146/154669933-35dcf88e-d6c6-4304-bc22-0a0a71b49a34.png">

Thanks for clarification

edit: bad image link

**Comment by metonym** [comment]
Nice catch. #1107 monkey patches the current style to allow overflow content. This is acceptable until it can be clarified upstream.

An immediate workaround is to set `direction="top"` for the `TooltipDefinition` in the last row.

**Comment by metonym** [comment]
Fixed in [v0.58.3](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.58.3)
