### ISSUE TITLE
Sortable DataTable's headers do not show sort order indicators when activated

### ISSUE THREAD

**Issue by n-peugnet** [carbon-design-system/carbon-components-svelte#1113]
### Description

The sortable DataTable's header should have indicators that show the current sort order applied to the data when clicked on. Currently these are not shown.

### Reproducing

To reproduce, simply go to the doc, and activate a sort header : https://carbon-components-svelte.onrender.com/components/DataTable#sortable

We can see that the sort order arrow indicator is not there.

### Problem

After a quick look in the code I saw that everything was already there to make it work, so I guess this is a regression.

I figured that the problem comes from this line:
https://github.com/carbon-design-system/carbon-components-svelte/blob/fe8fd65893e9d40696af5f3ef69ed440d41d56b6/src/DataTable/TableHeader.svelte#L23

The `sortHeader` store does contain this kind of informations:

```json
{
  "id": "size",
  "key": "size",
  "sortDirection": "descending"
}
```

Where `id` and `key` both refer to the key of this column. Whereas the `id` value inside the header is a generated one:
https://github.com/carbon-design-system/carbon-components-svelte/blob/fe8fd65893e9d40696af5f3ef69ed440d41d56b6/src/DataTable/TableHeader.svelte#L15

### One solution

I simply tried to add a `header` argument to the `TableHeader` component like this:

```js
/**
 * Header data
 * @type {key: string, value: string}
 */
export let header;
```

Changed the reactive `active` value to:

```js
$: active = $sortHeader.key === header.key;
```

And passed it from the `DataTable` like this

```html
<TableHeader header={header}></TableHeader>
```

And everything worked as expected.

**Comment by metonym** [comment]
Fixed in [v0.58.4](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.58.4)
