### ISSUE TITLE
`DatePicker`'s `minDate` and `maxDate` props don't change with provided variable

### ISSUE THREAD

**Issue by tmarsik42** [carbon-design-system/carbon-components-svelte#1127]
Made a [repl](https://svelte.dev/repl/3f3e54168a14464ab648b07f79255eb6?version=3.46.4) for this.

I have a `DatePicker` with `minDate` prop set with a variable. When variable changes, I'd expect `minDate` prop to get updated but it doesn't happen and calendar fields are still grey. You can see in repl how `labelText` gets updated after button click but calendar fields do not.

**Comment by metonym** [comment]
Fixed in [v0.60.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.60.0)
