### ISSUE TITLE
Form submit not triggered / forwarded

### ISSUE THREAD

**Issue by kpopovic** [carbon-design-system/carbon-components-svelte#1134]
Hello,

https://carbon-components-svelte.onrender.com/components/Form
I looked the example above, and form submit is not triggered when submit Button is clicked.

But when I do this then it works:

```
<Form 
        id="myform"
	on:submit={() => {
		document.getElementById('myform').submit();
	}}
...
<FormGroup legendText="Checkboxes">
    <Checkbox id="checkbox-0" labelText="Checkbox Label" checked name="checkbox-0" /> // <--- added name attribute
    <Checkbox id="checkbox-1" labelText="Checkbox Label" name="checkbox-1" />
    <Checkbox id="checkbox-2" labelText="Checkbox Label" disabled name="checkbox-2"/>
</FormGroup>
...
</Form>
```

Question: is this the proper way? 

Best Regards,
Krešimir

**Comment by metonym** [comment]
Hi there. The `Form` component [prevents the default behavior](https://github.com/carbon-design-system/carbon-components-svelte/blob/bbd2cbe62cae80f2653be84778265f123c9ac6e1/src/Form/Form.svelte#L16) on the forwarded submit event.

What you have works.

An alternative is to use the native `form` element if you would prefer the default submit behavior:

```svelte
<form on:submit>
  ...
</form>
```

**Comment by metonym** [comment]
@kpopovic The `Form` default submit event is no longer modified in [v0.62.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.62.0).

If you do want to prevent the default behavior (like in a SPA), you can invoke `preventDefault` in the forwarded submit event:

```svelte
<Form on:submit={e => {
  e.preventDefault();
  console.log("submit", e);
}}>
   <Checkbox id="checkbox-0" labelText="Checkbox Label" checked />
  <Button type="submit">Submit</Button>
</Form>
```

**Comment by jeremyben** [comment]
This was an actual breaking change for me, you should mention it in the changelog.
It reloads the page and puts values of the form in the url as search parameters (including password for the login page).

**Comment by jeremyben** [comment]
Sorry for misremembering, I though it was not labelled as breaking.
