### ISSUE TITLE
Clicking a Toggle component selects nearby text

### ISSUE THREAD

**Issue by TheophileMot** [carbon-design-system/carbon-components-svelte#1137]
If you click quickly on a Toggle component, this will cause the browser to select text on the page. This happens when clicking on the graphical part of the toggle, not the label beside it.

Here's a demonstration of the behaviour on the [documentation page](https://carbon-components-svelte.onrender.com/components/Toggle), showing how text gets selected alternately above and below the toggle:

![Feb-28-2022 15-16-37](https://user-images.githubusercontent.com/34871447/156052752-1ea740b1-fc39-456b-8080-11d91de2e391.gif)

**Comment by metonym** [comment]
This is a question best suited for the upstream library.

https://github.com/carbon-design-system/carbon/issues

**Comment by TheophileMot** [comment]
I added the issue at the main library here: https://github.com/carbon-design-system/carbon/issues/10881

**Comment by metonym** [comment]
It looks like the ["user-select: none" approach](https://github.com/carbon-design-system/carbon/pull/11670) is endorsed by the upstream implementation, so we can apply it here.

**Comment by metonym** [comment]
Fixed in [v0.67.3](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.67.3)
