### ISSUE TITLE
Slider has bugs

### ISSUE THREAD

**Issue by pjebs** [carbon-design-system/carbon-components-svelte#1142]
This repo: https://svelte.dev/repl/5258e80d41a2467b994fdcb516385bf5?version=3.46.4

https://svelte.dev/repl/5258e80d41a2467b994fdcb516385bf5?version=3.46.4

demonstrates that the slider stretches infinitely to right hand side and on the left hand side, it becomes "NaN".

**Comment by pjebs** [comment]
You can also see in the last slider that when the min value is set to `0.1`, it doesn't even work.

**Comment by brunnerh** [comment]
I have been tripped up by this behavior before as well. Maybe components that deal with numbers could be made more resilient and try to auto convert these props? E.g. using `+prop`

[REPL example](https://svelte.dev/repl/7d4bc0256e994164b91ec8258e7ee938?version=3.46.4)
