### ISSUE TITLE
ClickableTile weird border

### ISSUE THREAD

**Issue by pjebs** [carbon-design-system/carbon-components-svelte#1146]
When using a ClickableTile with a `href` set,
there is a weird border that emerges around the Tile when the mouse is down or clicked.
How can I disable it?
<img width="563" alt="Screen Shot 2022-03-05 at 12 50 41 pm" src="https://user-images.githubusercontent.com/5377970/156862930-9dcc7ebc-1a6b-450d-9dd3-4f5f78df3aec.png">
<img width="567" alt="Screen Shot 2022-03-05 at 12 50 47 pm" src="https://user-images.githubusercontent.com/5377970/156862931-bb4c5f68-2776-4fd4-b528-738f11970690.png">

**Comment by metonym** [comment]
The outline exists for interactive elements by design to signify a "focus" state.

You can manually override the CSS to hide it:

```css
:global(.bx--tile--clickable:focus) {
  outline: 0;
}
```
