### ISSUE TITLE
Should be possible to mark rows as non-selectable

### ISSUE THREAD

**Issue by datasushi** [carbon-design-system/carbon-components-svelte#1148]
Hi,

I have a use case where I need batch actions with selection where I need to exclude specific row ids,

Thank you

**Comment by metonym** [comment]
Released in [v0.61.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.61.0).

Example: https://carbon-components-svelte.onrender.com/components/DataTable#non-selectable-rows
