### ISSUE TITLE
MultiSelect filterable - highlightedIndex not reset when highlighted option is filtered

### ISSUE THREAD

**Issue by dominikg** [carbon-design-system/carbon-components-svelte#1150]
Steps to reproduce:
- go to https://carbon-components-svelte.onrender.com/components/MultiSelect#filterable
- focus the input field
- press "arrow down" to highlight the "email" option (but do not select it)
- type "p" into the input field so all options are filtered away
- press Enter
- open browser console
- see `Uncaught TypeError: Cannot read properties of undefined (reading 'id') error` 

the error happens in this line https://github.com/carbon-design-system/carbon-components-svelte/blob/853942f998b656593afc8801970489aa10369ac9/src/MultiSelect/MultiSelect.svelte#L399

**Comment by dominikg** [comment]
context:
I stumbled on this while building an advanced multi-select field where the user can add custom options by pressing enter (if the value is not present in the list of options already)

For this it would also be useful if the state "user has highlighted an option" would be exposed directly instead of just as an aria attribute here https://github.com/carbon-design-system/carbon-components-svelte/blob/853942f998b656593afc8801970489aa10369ac9/src/MultiSelect/MultiSelect.svelte#L385 
Is this something you would consider adding? (can send a feature request/pr)

**Comment by metonym** [comment]
> For this it would also be useful if the state "user has highlighted an option" would be exposed directly instead of just as an aria attribute here

Can you elaborate on the proposed implementation? Do you mean via a prop or slot?

**Comment by dominikg** [comment]
> > For this it would also be useful if the state "user has highlighted an option" would be exposed directly instead of just as an aria attribute here
> 
> Can you elaborate on the proposed implementation? Do you mean via a prop or slot?

exported prop.

Support for a customizable list item component (eg to add a 'delete option' button) would be great too but this would add a lot more complexity and i'm not sure if you want/need this amount of flexibility for MultiSelect itself.

**Comment by metonym** [comment]
I think that's a great idea, giving the end user to the flexibility to control the highlighted option.

> Support for a customizable list item component

For something like this, I could see adding a slot, if possible, so that users can pass their own elements etc.

PRs welcome.

**Comment by metonym** [comment]
Released in [v0.61.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.61.0)
