### ISSUE TITLE
Detail page header

### ISSUE THREAD

**Issue by AlvaroPata** [carbon-design-system/carbon-components-svelte#1151]
Hello!
I've been trying to implement this page header as seen on the carbon design system homepage with the svelte component library, but I'm pretty lost.

I'm talking about the black title section with the tabs below it.

<img width="1280" alt="Screenshot 2022-03-09 at 11 34 36" src="https://user-images.githubusercontent.com/69887666/157424836-91680ce6-04a5-47da-9a1a-9f59046c94d0.png">

Is there any suggested way to do it?  Or could someone point out what the best way to do it would be?

Thanks in advice!

**Comment by metonym** [comment]
This is a custom Carbon Gatsby component.

The source code include [PageHeader](https://github.com/carbon-design-system/gatsby-theme-carbon/tree/5257408683f56b4a9709111325455e201c4f0584/packages/gatsby-theme-carbon/src/components/PageHeader) and [PageTabs](https://github.com/carbon-design-system/gatsby-theme-carbon/tree/5257408683f56b4a9709111325455e201c4f0584/packages/gatsby-theme-carbon/src/components/PageTabs).
