### ISSUE TITLE
Copy component does not copy and is also missing from the docs

### ISSUE THREAD

**Issue by kkudose** [carbon-design-system/carbon-components-svelte#1156]
[Copy](https://github.com/carbon-design-system/carbon-components-svelte/tree/master/src/Copy) is exported and available to use, but it's not actually documented. Running `yarn build:docs` doesn't seem to create any docs either.

`Copy` is also a poor name since it doesn't actually have any of the copying logic. It appears to be a component that provides feedback via a popover (not the popover component, to be clear) when clicked. `CopyButton` uses `Copy` as a wrapper and provides the actual [copying logic here](https://github.com/carbon-design-system/carbon-components-svelte/blob/853942f998b656593afc8801970489aa10369ac9/src/CopyButton/CopyButton.svelte#L17).

**Comment by metonym** [comment]
`Copy` has been removed in [v0.62.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.62.0).
