### ISSUE TITLE
button iconDescription

### ISSUE THREAD

**Issue by pjebs** [carbon-design-system/carbon-components-svelte#1164]
when `iconDescription` is not set (i.e. `undefined`), the tooltip says "undefined" instead of being disabled.

**Comment by metonym** [comment]
[Per the docs](https://carbon-components-svelte.onrender.com/components/Button#icon-only-button), `iconDescription` must be provided for an icon-only button.

**Comment by pjebs** [comment]
Is there a workaround?

**Comment by metonym** [comment]
The workaround is to manually override styles using CSS. You can inspect the tooltip styles and write CSS to hide them.

Of course – as this library is open source – you can always copy the source code into a local file and make modifications as you see fit.
