### ISSUE TITLE
Button spreads $$restProps to the button | a | div element.

### ISSUE THREAD

**Issue by pjebs** [carbon-design-system/carbon-components-svelte#1165]
Despite documentation,

`on:touchstart` props are not getting spread to underlying button element.

**Comment by metonym** [comment]
Events are not passed through `$$restProps`; only [props not specifically exported](https://svelte.dev/docs#template-syntax-attributes-and-props) are passed.

Events – such as `on:touchstart` – would have to be forwarded.

I would recommend using the [custom button](https://carbon-components-svelte.onrender.com/components/Button#custom-element), where you can use a native element and use the touchstart event:

```svelte
<Button as let:props>
  <button {...props} on:touchstart>Custom element</button>
</Button>
```

**Comment by pjebs** [comment]
How would I transfer the originally intended CSS and icon then?
