### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by zfranco55** [carbon-design-system/carbon-components-svelte#1178]
there is documentation in pdf, or is there a way to create a pdf file ?

**Comment by metonym** [comment]
Currently, documentation does not exist as a PDF.

If you want a single file, there is [`COMPONENT_INDEX.md`](https://github.com/carbon-design-system/carbon-components-svelte/blob/ceb7abf2e9e7bdaced97175fdb096da3d7535639/COMPONENT_INDEX.md), which documents just the component API but not does provide usage or examples.
