### ISSUE TITLE
ToolbarSearch without DataTable

### ISSUE THREAD

**Issue by Tihomir971** [carbon-design-system/carbon-components-svelte#1189]
I used ToolbarSearch with TreeView. In last version it stop working.
Can we enable it again and is it posible Toolbar to have same functionality in TreeView like with DataTable ("shouldFilterNodes" similar to shouldFilterRows)

**Comment by metonym** [comment]
Hot fixed in [v0.62.1](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.62.1)
