### ISSUE TITLE
Datepicker not showing

### ISSUE THREAD

**Issue by pwwang** [carbon-design-system/carbon-components-svelte#1194]
It's not showing on the documentation page:

https://carbon-components-svelte.onrender.com/components/DatePicker

Tried on Chrome and Edge.

CCS version: 0.62.1

**Comment by metonym** [comment]
Strange – it's loading for me. Are you able to see this page? https://carbon-components-svelte.onrender.com/framed/DatePicker/DatePickerSingle?theme=white

**Comment by pwwang** [comment]
That page works for me.

**Comment by metonym** [comment]
So only https://carbon-components-svelte.onrender.com/components/DatePicker#single doesn't load?

**Comment by pwwang** [comment]
And the calendar icon does not show, either, if it is the default setting.

![image](https://user-images.githubusercontent.com/1188067/159384346-ded3c9dd-e354-44e7-af72-4b39a5e1e869.png)

**Comment by pwwang** [comment]
> So only https://carbon-components-svelte.onrender.com/components/DatePicker#single doesn't load?

The opposite, only the single one works.

**Comment by metonym** [comment]
That's by design; `datePickerType="simple"` does not have a dropdown calendar to choose from.

Only `"single"` and `"range"` types use flatpickr.

**Comment by pwwang** [comment]
I see. Thanks for the explanation.

**Comment by metonym** [comment]
The [`DatePicker` docs ](https://carbon-components-svelte.onrender.com/components/DatePicker)now feature the calendar variants more prominently (https://github.com/carbon-design-system/carbon-components-svelte/pull/1298/commits/39b74480146726eb88bac2f532d52e57f95eeca3).
