### ISSUE TITLE
flatpickrProps on DatePicker do not override default options

### ISSUE THREAD

**Issue by flut1** [carbon-design-system/carbon-components-svelte#1197]
I wanted to be able to set `disableMobile: false` on [flatpickr options](https://flatpickr.js.org/options/) for my DatePicker component. I used the `flatpickrProps` property like so:

```
<DatePicker datePickerType="single" flatpickrProps={{disableMobile: false}}>
  <DatePickerInput labelText="..." placeholder="mm/dd/yyyy" />
</DatePicker>
```

These options are properly forwarded to `createCalendar.js`, but the [options are spread](https://github.com/carbon-design-system/carbon-components-svelte/blob/912d3796f0b011648a055ed14d30b765100bb1b1/src/DatePicker/createCalendar.js#L71) before applying the default options from `carbon-components-svelte`. In order to be able to override the defaults from this library, the `...options` statement needs to be placed below the default options.

**Comment by metonym** [comment]
Released in [v0.62.2](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.62.2)
