### ISSUE TITLE
DataTable: zebra cannot be used with expandable

### ISSUE THREAD

**Issue by wilriker** [carbon-design-system/carbon-components-svelte#1199]
When using both `zebra` and `expandable` on a `DataTable` it will not render with zebra stripes. Removing `expandable` lets the table get rendered with zebra stripes.

If this is intended behavior, please amend documentation.

**Comment by metonym** [comment]
Thanks for point this out – this is fixed in [v0.62.2](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.62.2).

Example: https://carbon-components-svelte.onrender.com/components/DataTable#expandable-zebra-styles
