### ISSUE TITLE
DataTable: expanded rows always visible

### ISSUE THREAD

**Issue by wilriker** [carbon-design-system/carbon-components-svelte#1206]
Together with the fix for #1199 one line was modified at https://github.com/carbon-design-system/carbon-components-svelte/commit/53fdbdf99129ef342df06399f95723fe310b4ecb#diff-e1e14fa75f6c4b3da71cb7eff121f0ce58ba5f7d37999df963c5bb55c90c1002L486. This change - so I assume - leads to expanded rows being always visible and populated as soon as `expandable` is defined on the `DataTable`. At least all my DataTables with `expandable` are suddenly showing the expanded rows on load. If I click on the chevron the same content will be slightly shifted to the right (where it usually appears when expanding) and returns to initial position when clicking the chevron again to collapse. But the content is always visible.

Downgrading to 0.62.1 solves the issue for me - but leaves me without zebra stripes on `expandable` DataTables.

**Comment by metonym** [comment]
Can you modify this Svelte REPL to provide a repro?

https://svelte.dev/repl/890a282ef52d4971bdd462d2018b9501?version=3.46.4

**Comment by wilriker** [comment]
This was a fault on my end. There was some CSS that prevented setting the height to 0. Sorry for the noise.
