### ISSUE TITLE
0.62.2: DataTable: expanded rows are eagerly instantiated

### ISSUE THREAD

**Issue by wilriker** [carbon-design-system/carbon-components-svelte#1209]
Before 0.62.2 expanded rows of `DataTable` have been lazy-loaded when the row was expanded. With 0.62.2 all expandable row content will be loaded eagerly.

Minimal example: https://svelte.dev/repl/88b54d36965c40d0883f34bc79997176?version=3.46.4
(see Console for a message when the content of an expanded row is instantiated.

This can have severe consequences in case of expanded row doing heavy background work, e.g. loading massive data from a DB which can bring your DB down in case your table shows hundreds of rows.

As in my my-fault-issue #1206 I assume this change to be the source: https://github.com/carbon-design-system/carbon-components-svelte/commit/53fdbdf99129ef342df06399f95723fe310b4ecb#diff-e1e14fa75f6c4b3da71cb7eff121f0ce58ba5f7d37999df963c5bb55c90c1002L486.

**Comment by metonym** [comment]
Fixed in [v0.62.3](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.62.3)
