### ISSUE TITLE
Programmatically expand/collapse TreeView nodes

### ISSUE THREAD

**Issue by Tihomir971** [carbon-design-system/carbon-components-svelte#1214]
Example in documentation "Expand a subset of nodes" dosn't work as expected.
Try to change IBM in /^IBM/.test(node.text) with anything else. All frist level nodes are expanded.

**Comment by metonym** [comment]
Fixed in [v0.62.3](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.62.3).

See the REPL for a kitchen sink example: https://svelte.dev/repl/2dee96a1f04448cab97580c9f4830b71?version=3.46.4

**Comment by Tihomir971** [comment]
> Fixed in [v0.62.3](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.62.3).
> 
> See the REPL for a kitchen sink example: https://svelte.dev/repl/2dee96a1f04448cab97580c9f4830b71?version=3.46.4

Do you have some example how to expand parent node? It's more usefull when searching for some node.

**Comment by metonym** [comment]
If you have the node `id`, you can filter by that.
