### ISSUE TITLE
`DataTable` with `stickyHeader` scrolls back to the top when selecting rows

### ISSUE THREAD

**Issue by Lucide** [carbon-design-system/carbon-components-svelte#1228]
I am using a `DataTable` with `selectable` (or `batchSelection`) and `stickyHeader`.
Whenever a checkbox is selected, it scrolls back to the top.

I've found a related _resolved_ issue on carbon core: [[Bug]: DataTable with stickyHeader inside a ComposedModal scrolls back to the top when selecting rows at the bottom](https://github.com/carbon-design-system/carbon/issues/10307).

**Comment by metonym** [comment]
Released in [v0.63.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.63.0).

Note on upgrading: if using `carbon-preprocess-svelte`, upgrade to version 0.9.0.
