### ISSUE TITLE
`StructuredList` border collapse in Safari

### ISSUE THREAD

**Issue by tmarsik42** [carbon-design-system/carbon-components-svelte#1229]
Styling issue with `bottom-border` of `StructuredList` in Safari.
When cells contain some other component, like `Link` or icon, the height of cells is different and Safari fails to apply border-collapse, resulting in the double border.

[Repl](https://svelte.dev/repl/f8b449732f8649e68a4a2473949571c5?version=3.46.6)

Screenshot of repl from Safari

<img width="893" alt="Snímek obrazovky 2022-04-04 v 8 50 00" src="https://user-images.githubusercontent.com/95856146/161488560-2ac88c44-86b5-4645-9386-09f5882af0e6.png">

**Comment by metonym** [comment]
Is this still an issue? I'm unable to repro in Safari 15.2:

<img width="1395" alt="Screen Shot 2022-06-25 at 6 19 13 AM" src="https://user-images.githubusercontent.com/10718366/175775261-0e46a8c8-3833-43c0-9d1b-001e88fc9d4b.png">

**Comment by tmarsik42** [comment]
Hey, thanks and sorry about not replying sooner. It seems this is not an issue anymore.
