### ISSUE TITLE
ClickableTile component styled width not respected

### ISSUE THREAD

**Issue by ekampp** [carbon-design-system/carbon-components-svelte#1231]
When I create a ClickableTile component, and I add `style="width: 60px"`; it seems that it's not respected.

It's possible to increase the width, but at a certain point, it seems that it's not possible to decrease the width.

**Comment by metonym** [comment]
You can always override the style on the class selector:

```css
:global(.bx--tile) {
  min-width: 0;
}
```

**Comment by ekampp** [comment]
@metonym, nice! I didn't know that. 

But that should be overridden by inline style, right? Inline styling should take precedence over CSS styling, right?

**Comment by brunnerh** [comment]
The tile component has a `min-width`, so setting only `width` will be limited by that.

[REPL](https://svelte.dev/repl/06ea960e3bcf454aad48a6176ca284b0?version=3.46.6)

**Comment by ekampp** [comment]
It's unexpected that the tile has a min-width. Does anyone know the rationale behind that?

**Comment by metonym** [comment]
@ekampp You can raise that question upstream in the [Carbon repo.](https://github.com/carbon-design-system/carbon) That's a question best answered by the designers.
