### ISSUE TITLE
Allow the usage of sveltekit:prefetch for links

### ISSUE THREAD

**Issue by jakob-kruse** [carbon-design-system/carbon-components-svelte#1232]
I would like to use svelte kit's prefetch functionality with links. It is working, but the type does not exist. Is that something that should be added?

I guess for non-sveltekit, svelte sites this could cause some confusion

**Comment by metonym** [comment]
Released in [v0.63.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.63.0).

Components that extend `a` attributes now support `sveltekit:prefetch`, `sveltekit:noscroll`, and `sveltekit:reload` atttributes.

Note on upgrading: if using `carbon-preprocess-svelte`, upgrade to version 0.9.0.
