### ISSUE TITLE
Change default icon size for header actions/expose as prop

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#1240]
The intended default size for icons in `HeaderGlobalAction`/`HeaderAction` appears to be 20px. With v11 of the icons library the slot has to be used to get the icon to assume this size (as the default is 16px).

![image](https://user-images.githubusercontent.com/834235/162707116-ae8bdc5f-566b-443b-9a92-236b1e0f2157.png)

(If an additional prop were to be added to control the size, `HeaderAction` may need two such props, as it has a separate `closeIcon`)

Related issue https://github.com/carbon-design-system/carbon-icons-svelte/issues/140

**Comment by metonym** [comment]
Good thinking, but the default size is already set to `20` in both the [`HeaderAction`](https://github.com/carbon-design-system/carbon-components-svelte/blob/2d26ce115d412738dc4dc1fc75bf1fcfdf16a2b7/src/UIShell/HeaderAction.svelte#L70) and `HamburgerMenu` components.

**Comment by brunnerh** [comment]
Shouldn't the default size also be 20 for [`HeaderActionGlobal`](https://github.com/carbon-design-system/carbon-components-svelte/blob/2d26ce115d412738dc4dc1fc75bf1fcfdf16a2b7/src/UIShell/HeaderGlobalAction.svelte)? It appears to not be set there.

[REPL](https://svelte.dev/repl/ef6496292d0b4b10bb5a826e76ba1119?version=3.47.0)

**Comment by metonym** [comment]
Fixed in [v0.63.1](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.63.1)
