### ISSUE TITLE
Tag interactive variant use "submit" inside forms

### ISSUE THREAD

**Issue by rkakrik** [carbon-design-system/carbon-components-svelte#1243]
I use tags inside the form, the interactive type is good by design, but when you click on the tag, the form is reset.
Is it possible to add type="button" as default?

**Comment by metonym** [comment]
Released in [v0.63.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.63.0). If using `carbon-preprocess-svelte`, upgrade to version 0.9.0.
