### ISSUE TITLE
Custom component is not a valid Carbon component

### ISSUE THREAD

**Issue by draccagni** [carbon-design-system/carbon-components-svelte#1245]
I'm trying to develop a new component in [AutoComplete](https://github.com/draccagni/carbon-components-svelte/tree/AutoComplete_component) fork. It works fine in the `docs` project, but when I try to use it in examples  (ex: `sapper`) the following error is raised:
```
[carbon:optimizeImports] AutoComplete is not a valid Carbon component
[carbon:optimizeImports] AutoComplete is not a valid Carbon component
• server
src/routes/index.svelte
'AutoComplete' is not defined
4: </script>
5:
6: <AutoComplete
   ^
7:   titleText="Contact"
8:   selectedId="0"
• client
src/routes/index.svelte
'AutoComplete' is not defined
4: </script>
5:
6: <AutoComplete
   ^
7:   titleText="Contact"
8:   selectedId="0"
```
If I change the import as below it works properly.
```
<script>
  import { AutoComplete } from "carbon-components-svelte/src";
</script>

<AutoComplete
  titleText="Contact"
  selectedId="0"
  items="{[
    { id: '0', text: 'Slack' },
    { id: '11', text: 'Email1' },
    { id: '12', text: 'Email2' },
    { id: '2', text: 'Fax' },
  ]}"
/>
```
The compoenent has been added to `index.js` file.

**Comment by metonym** [comment]
The component index for `optimizeImports` from `carbon-preprocess-svelte` is [generated ahead-of-time](https://github.com/carbon-design-system/carbon-preprocess-svelte/blob/92f7246c6e1387aa733f996234976c56805ce5f7/src/carbon-components-svelte.js). The preprocessor won't pick up newly added components until it's rebuilt.

You can either:

- remove the `optimizeImports` preprocessor
- fork https://github.com/carbon-design-system/carbon-preprocess-svelte and generate the map for the components
