### ISSUE TITLE
Strange Scrollbar when using PasswordInput in Modal

### ISSUE THREAD

**Issue by Heptalon** [carbon-design-system/carbon-components-svelte#1252]
A normal Modal with a `TextInput` looks like this:

![image](https://user-images.githubusercontent.com/6977095/163781191-e8146c06-fbb6-4cc4-8f13-3879b9c0e63a.png)

```html
<Modal open modalHeading="Benutzer Hinzufügen" primaryButtonText="Save" secondaryButtonText="Cancel">
        <TextInput labelText="Benutzername"></TextInput>
</Modal>
```
<hr>
When I use a `PasswordInput` instead it looks like this:

![image](https://user-images.githubusercontent.com/6977095/163781321-46517d00-fb48-4501-b174-7d8d74599516.png)

```html
<Modal open modalHeading="Benutzer Hinzufügen" primaryButtonText="Save" secondaryButtonText="Cancel">
        <PasswordInput labelText="Passwort"></PasswordInput>
</Modal>
```
<hr>
This behavior seems to affect mobile and desktop in all resolutions.

I would expect that there are no extra scroll bars when using a `PasswordInput` inside of a modal. If this is intended behavior or I am just overlookig something here, feel free to close the issue.

**Comment by brunnerh** [comment]
Probably this: #545

**Comment by Heptalon** [comment]
You are right. It is a duplicate of #545.
