### ISSUE TITLE
When will Carbon v11 be available for Svelte?

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon-components-svelte#1253]
(title).
Thanks.

**Comment by joshblack** [comment]
Let me know if you want to sync up on this @metonym! Let me know how we can help

**Comment by Sheepux** [comment]
Seeing the topic, I would like to take some time and exceptionally abuse squatting this issue just for a single message :
Thank you for your dedicated work all those years for the svelte component (and kudos to the carbon team as well).

**Comment by metonym** [comment]
Thanks @joshblack, I'll reach out on Discord.

**Comment by FlipOneForEtx** [comment]
Really would be nice to know when the Svelte components will be using v11. Or is Svelte really not a priority for such updates?

**Comment by Negaron** [comment]
Can't wait too

**Comment by RadioRambo** [comment]
any update?

**Comment by eytanProxi** [comment]
@metonym 😃

**Comment by jqlio18** [comment]
I would like to work on the update. I know I'm kinda new on GitHub but not new to programming. Let me know if you need anything.

**Comment by theetrain** [comment]
We're currently coming up with a roadmap for carbon-components-svelte v1, which includes Carbon v11 feature parity. Stay tuned. 😃

**Comment by theetrain** [comment]
Hello, followers of this issue. Our v1 roadmap has been announced! https://github.com/carbon-design-system/carbon-components-svelte/discussions/1614

**Comment by theetrain** [comment]
Thanks for following this ticket. Implementation details are being tracked in #1629 so I'm closing this ticket in favour of that. Feel free to subscribe to #1629 for progress on Carbon v11 style adoption.
