### ISSUE TITLE
DataTable `selectableRowIds` is empty if `rows` is set one more time

### ISSUE THREAD

**Issue by n-peugnet** [carbon-design-system/carbon-components-svelte#1254]
See this [REPL demo](https://svelte.dev/repl/9153c47d0e1f4262b4edf3144826ce27?version=3.47.0).

The batch selection is broken because `selectableRowIds` is empty.

It is empty because of [this change](https://github.com/carbon-design-system/carbon-components-svelte/commit/2df7b922692623b4f15d1754d1fcfaf1bff47333#diff-e1e14fa75f6c4b3da71cb7eff121f0ce58ba5f7d37999df963c5bb55c90c1002R198-R207):
https://github.com/carbon-design-system/carbon-components-svelte/blob/c2568ec5d49bfda26f6ea4ebad7e4a3a3a8d9db5/src/DataTable/DataTable.svelte#L198-L207

As no `=` is used, the reactivity is not propagated to the statements that depends on `tableRows`, especially this one: https://github.com/carbon-design-system/carbon-components-svelte/blob/c2568ec5d49bfda26f6ea4ebad7e4a3a3a8d9db5/src/DataTable/DataTable.svelte#L178

This can be fixed by setting the value of `tableRows` this way:

```diff
--- node_modules/carbon-components-svelte/src/DataTable/DataTable.svelte	2022-04-18 19:07:22.145301315 +0200
+++ DataTable.svelte	2022-04-18 19:07:16.805276869 +0200
@@ -195,16 +195,14 @@
   $: if (radio || batchSelection) selectable = true;
   $: tableSortable.set(sortable);
   $: headerKeys = headers.map(({ key }) => key);
-  $: tableRows.set(
-    rows.map((row) => ({
-      ...row,
-      cells: headerKeys.map((key, index) => ({
-        key,
-        value: resolvePath(row, key),
-        display: headers[index].display,
-      })),
-    }))
-  );
+  $: $tableRows = rows.map((row) => ({
+    ...row,
+    cells: headerKeys.map((key, index) => ({
+      key,
+      value: resolvePath(row, key),
+      display: headers[index].display,
+    })),
+  }));
   $: sortedRows = [...$tableRows];
   $: ascending = $sortHeader.sortDirection === "ascending";
   $: sortKey = $sortHeader.key;
```

I believe other similar assignments should also be fixed, but this change was enough to fix the batch selection bug I had.

**Comment by metonym** [comment]
Fixed in [v0.63.1](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.63.1)
