### ISSUE TITLE
DatePicker inside Modal does not open the calendar

### ISSUE THREAD

**Issue by gatapia** [carbon-design-system/carbon-components-svelte#1256]
When a DatePicker is inside a Modal then the pop-up calendar does not show.

[Repl Link](https://svelte.dev/repl/9483420f7e134b77b630bd394aa1b78d?version=3.47.0)

This can be reproduced in the REPL by clicking the datapicker, see that the calendar opens as expected.

Then  click the 'Open' button.  This opens a Modal with another date picker.  Clicking in this date picker does not open the calendar.

**Comment by metonym** [comment]
Thanks for providing a repro.

For a `DatePicker` in a `Modal`, you will need to set `flatpickrProps.static` to `true`.

```svelte
<DatePicker bind:value={date} datePickerType="single" dateFormat="Y-m-d"  flatpickrProps={{ static: true }}>
  <DatePickerInput labelText="Start" />
</DatePicker>
```

[Updated REPL](https://svelte.dev/repl/cc3b9a8fa16343ab9cf58a9c08c243e7?version=3.47.0)

See the [documentation](https://carbon-components-svelte.onrender.com/components/DatePicker#datepicker-in-a-modal).
