### ISSUE TITLE
ToolbarSearch doesn't open again after closing

### ISSUE THREAD

**Issue by TheophileMot** [carbon-design-system/carbon-components-svelte#1258]
If you close a search bar, then clicking on the search icon fails to open the search bar again.

To reproduce:

1. Find a component with a search bar, e.g., a DataTable.
2. Click the search icon.
3. Type some text.
4. Close the search bar.
5. Click the search icon again. It will fail.

The search button will only work again after first clicking somewhere else.

![Apr-19-2022 13-48-22](https://user-images.githubusercontent.com/34871447/164065530-1fb161ea-45eb-48e0-ba66-02165bf7742d.gif)

Here's the workaround we're using:

```
// Search.svelte
    <input
      ...
      on:click={() => dispatch('reclick')}
    />

// ToolbarSearch.svelte
<Search
  ...
  on:reclick="{expandSearch}"
/>
```

**Comment by metonym** [comment]
Fixed in [v0.63.2](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.63.2)
