### ISSUE TITLE
CheckmarkFilled is not a valid Carbon component

### ISSUE THREAD

**Issue by rkakrik** [carbon-design-system/carbon-components-svelte#1272]
In this example (https://carbon-components-svelte.onrender.com/components/StructuredList#selectable-rows) I got this error:
```
[carbon:optimizeImports] CheckmarkFilled is not a valid Carbon component
```
Is it possible to use selectable StructuredList in some other way?

**Comment by metonym** [comment]
This is a bug in the docs. `CheckmarkFilled` should be imported from `carbon-icons-svelte`.

Can you install `carbon-icons-svelte` and import it like so?

```js
import CheckmarkFilled from "carbon-icons-svelte/lib/CheckmarkFilled.svelte";
```

**Comment by metonym** [comment]
Thanks for catching this – the docs are updated with the correct icon imports.
