### ISSUE TITLE
Tabs trigger on:change before selected is updated

### ISSUE THREAD

**Issue by cupcakearmy** [carbon-design-system/carbon-components-svelte#1278]
Demo: https://svelte.dev/repl/67e70de725e04190b251580a301c0c75?version=3.48.0

The issue is that the `on:change` event is fired before the actual `selected` prop is updated. I assume it's because it's updated in an `afterUpdate` call. Is there a reason for that?

https://github.com/carbon-design-system/carbon-components-svelte/blob/2cc54c1a53cb193977bd1b1a3ab095cff258719e/src/Tabs/Tabs.svelte#L85-L87

Edit: the `on:change` passes the new index in the `event.detail` but your logic relies on the `selected` prop it's problematic.

**Comment by metonym** [comment]
`selected = currentIndex` exists in the `afterUpdate` hook to avoid a cyclical dependency error:

https://github.com/carbon-design-system/carbon-components-svelte/blob/2cc54c1a53cb193977bd1b1a3ab095cff258719e/src/Tabs/Tabs.svelte#L92

Previously, the "change" event was dispatched whenever `currentIndex` changed. However, this caused the event to fire on initial load. [This PR](https://github.com/carbon-design-system/carbon-components-svelte/pull/882/files) moved the dispatch calls to the click/keydown handlers.

It's definitely a bug that the change event can fire multiple times, even if the index hasn't actually changed.

**Comment by metonym** [comment]
Fixed in [v0.63.5](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.63.5)

Updated the [Svelte REPL](https://svelte.dev/repl/38d3e6b6d60a421494cf5906bb06d450?version=3.48.0) to use the latest version.

**Comment by cupcakearmy** [comment]
Thanks for the instant fix!
