### ISSUE TITLE
Dropdown, Combobox, etc. broken with transitions

### ISSUE THREAD

**Issue by TheophileMot** [carbon-design-system/carbon-components-svelte#1281]
In my app, I have a panel that's conditionally rendered; it opens and closes with a transition. When a Dropdown (or similar component) is open during this transition, the app crashes with `translateWithId is not a function`.

In short, the problem is this combination:

```
{#if isPanelVisible}
  <div transition:fly>
    <Dropdown />
```

Here is a [minimal REPL](https://svelte.dev/repl/b8fff4e61a5a444b8e055d582b07d9e1?version=3.48.0).

**Comment by metonym** [comment]
Fixed in [v0.63.6](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.63.6)
