### ISSUE TITLE
custom cell in DataTable

### ISSUE THREAD

**Issue by MarcDAFrame** [carbon-design-system/carbon-components-svelte#1287]
```
<script>
    headers = [
		{ key: "", value: "", display: () => <Button />},
		{ key: "id", value: "Id" },
		{ key: "name", value: "name" },
    ]
</script>
<DataTable
	sortable 
	{headers}
	{rows}>
...
</DataTable>
```

is it possible to have custom components as a cell like above?

Most component libraries allow this in some form.

**Comment by metonym** [comment]
Yes, through [slotted cells](https://carbon-components-svelte.onrender.com/components/DataTable#slotted-cells).

**Comment by MarcDAFrame** [comment]
thanks @metonym !
