### ISSUE TITLE
Unable to dev with Contributing guide

### ISSUE THREAD

**Issue by Mattchine** [carbon-design-system/carbon-components-svelte#1290]
Following [CONTRIBUTE.MD](https://github.com/carbon-design-system/carbon-components-svelte/blob/master/CONTRIBUTING.md)

When running `yarn dev` there is no error in the terminal.
But `localhost:3000` in my browser shows only blank page.

Browser console shows
`Uncaught (in promise) TypeError: error loading dynamically imported module`
Along with multiple `Loading failed for the module with source <some_path>`

My system:
- OS: Linux, Fedora 35
- VSCode
- yarn: 1.22.18
- node: 17.9.0

**Comment by metonym** [comment]
To verify, do you see this in your terminal when running `yarn dev`?

```
vite v2.9.1 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

ready in 518ms.
```

But you don't see this in your browser?

```
[vite] connecting...
client.ts:53 [vite] connected.
```

**Comment by Mattchine** [comment]
I do see both of them in the terminal and browser console, respectively.
Errors come after 
```
[vite] connecting...
[vite] connected.
```
```
Loading failed for the module with source “http://localhost:3000/node_modules/carbon-icons-svelte/lib/Analytics.svelte”.
Loading failed for the module with source “http://localhost:3000/node_modules/carbon-icons-svelte/lib/Bullhorn.svelte”.
Uncaught (in promise) TypeError: error loading dynamically imported module
```

**Comment by metonym** [comment]
In the browser, does the tab title say "Carbon Components Svelte"? It may take 20-30 seconds to load.

<img width="969" alt="Screen Shot 2022-05-13 at 6 44 29 PM" src="https://user-images.githubusercontent.com/10718366/168406317-136e22b7-afa1-4e2b-bfe0-7fa92a55ffc4.png">
