### ISSUE TITLE
DataTable th elements have id attributes that are not unique in a document

### ISSUE THREAD

**Issue by berndfuhrmann** [carbon-design-system/carbon-components-svelte#1294]
This is a screenshot from https://carbon-components-svelte.onrender.com/components/DataTable:
![image](https://user-images.githubusercontent.com/19353115/168233911-5f285e55-8fbb-43ac-bd9d-f27ce46b03ff.png)
DataTable will add `id` attributes to each `th` element, but those ids are just the column names. You could (like on the example page) have multiple DataTable instances with similar column names, which would lead to multiple HTML elements with the same `id` in the same DOM tree.

https://html.spec.whatwg.org/multipage/dom.html#global-attributes says: 
When specified on [HTML elements](https://html.spec.whatwg.org/multipage/infrastructure.html#html-elements), the [id](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute) attribute value must be unique amongst all the [IDs](https://dom.spec.whatwg.org/#concept-id) in the element's [tree](https://dom.spec.whatwg.org/#concept-tree) and must contain at least one character. The value must not contain any [ASCII whitespace](https://infra.spec.whatwg.org/#ascii-whitespace).

This might interfere with `document.getElementById` or styling and lead to unexpected results.

The `tr` elements also have `id`s that could lead to such clashes.

**Comment by metonym** [comment]
Fixed in [v0.64.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.64.0).

Instead of using an id, the `data-header` and `data-row` are used for the headers and rows, respectively.
