### ISSUE TITLE
Popover Not Working

### ISSUE THREAD

**Issue by patagoniapy** [carbon-design-system/carbon-components-svelte#1301]
I can't seem to get the Popover working in multiple tests, but obviously it does work as evidenced by the docs. What am I missing?

```svelte
<script>
     import { Button, Dropdown, Popover } from "carbon-components-svelte";
</script>

<div>
      Parent
	<Popover open={true}>
		<div>test</div>
	</Popover>
</div>
```

I know I'm properly importing the css as evidenced by a handful of other components working for me in the same `.svelte` file I'm working in.

**Comment by metonym** [comment]
What version are you using?

Please see this REPL: https://svelte.dev/repl/8bae021a50f64b5aaca6a7570508a2f4?version=3.48.0

**Comment by patagoniapy** [comment]
Turns out it was just showing up in weird areas on the page. Thanks for the quick response!

**Comment by m93a** [comment]
The [REPL](https://svelte.dev/repl/8bae021a50f64b5aaca6a7570508a2f4?version=3.48.0) shows as the following to me:
![image](https://user-images.githubusercontent.com/1671665/203172916-1e173a39-7632-445f-a55b-7f6a4a3bb7a2.png)

This looks very different from the [Popover live demo](https://carbondesignsystem.com/components/popover/usage/#live-demo):
![image](https://user-images.githubusercontent.com/1671665/203175451-5efe5127-1cff-4ba0-b619-ed8264f0dbff.png)
