### ISSUE TITLE
DataTable stickyHeader and custom width columns seems to be incompatible

### ISSUE THREAD

**Issue by ivarlovlie** [carbon-design-system/carbon-components-svelte#1303]
`stickyHeader` applies `display: block` to the table node and setting a custom column width applies `table-layout: fixed` to the table node, but since the table does not have a display value of `table` when using sticky headers the `table-layout: fixed` rule does not get applied. I don't really know if the settings can be compatible, but i think we should consider adding a note in the docs regardless.

**Comment by bhavers** [comment]
I've applied a css workaround by applying a sticky to the table headers. Not as nice, but does the job.

```
<style>
:global(.bx--data-table thead) {
  height: 32px;
  position: sticky;
  inset-block-start: 0;
  z-index: 1; /* Otherwise elements like checkboxes scroll over the header */

/* if you have a toolbar you also might need this */
:global(.bx--table-toolbar) {
  z-index: 3 !important;
}
</style>
```
