### ISSUE TITLE
Question: Help with theme component with SvelteKit

### ISSUE THREAD

**Issue by cananda** [carbon-design-system/carbon-components-svelte#1304]
Hello!

I'm trying to use theme component on SvelteKit in the following way 

```
// settings.svelte
<script>
	import { Content, Grid, Row, Column } from 'carbon-components-svelte';
	import { Theme } from 'carbon-components-svelte';
</script>

<Content>
	<Grid>
		<Theme
			render="toggle"
			toggle={{
				themes: ['white', 'g80'],
				hideLabel: true
			}}
		>
			<Row>
				<Column>
					<p>Hello</p>
				</Column>
			</Row>
		</Theme>
	</Grid>
</Content>
```

i have imported both the white.css and g80.css in __layout,svelte.  The toggle is not working and maybe I'm going about this all wrong

**Comment by metonym** [comment]
The `Theme` component only works with the `all.css` StyleSheet.

```html
<!-- __layout.svelte -->
<script>
  import "carbon-components-svelte/css/all.css";
</script>
```

This is missing from the docs and should be added.

**Comment by metonym** [comment]
The [documentation](https://carbon-components-svelte.onrender.com/components/Theme) has been updated to state that `all.css` is required to be used with `Theme`.
