### ISSUE TITLE
DataTable Jumps to Top of Page when using Selectable.

### ISSUE THREAD

**Issue by recon2710** [carbon-design-system/carbon-components-svelte#1312]
When using Datatable selectable. If page is scrolled down past view of ToolBar and Row is selected; The page jumps to the top. Thus if trying to select multiple rows from bottom of page your constanty jumping to top and need to scroll down down to select additional rows. 

I though it was my implementation, but I was able to replicate with examples provided in docs by just adding more data to rows.

Thank you for this great lib.

**Comment by metonym** [comment]
What version are you using?

This was a known bug that should have been [fixed in v0.63.0.](https://github.com/carbon-design-system/carbon-components-svelte/pull/1230)

**Comment by recon2710** [comment]
Using v0.58. Got it TY
