### ISSUE TITLE
DataTable width doesn't seem to work if empty:true

### ISSUE THREAD

**Issue by halindraprakoso** [carbon-design-system/carbon-components-svelte#1313]
hello,

setting the DataTable width in the headers doesn't seem to work if the `empty` property is set to `true`. 
On version `0.64.1`

A workaround is by using slotted cells

**Comment by metonym** [comment]
Thanks for reporting. Fixed in [v0.64.2](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.64.2).
