### ISSUE TITLE
I'm clearly doing something wrong, this cant be real.

### ISSUE THREAD

**Issue by ohbob** [carbon-design-system/carbon-components-svelte#1316]
Hello guys, i just started using this library and wanted to say its amazing, but i have some issues with it loading everything or me not understanding how to load it properly.

I'm loading one component, with the default white theme and I'm getting 6mb on a almost blank page..  As you see in the screen, it seems to be loading all components??

![right](https://user-images.githubusercontent.com/47858537/170831988-44311eae-d24f-42e9-b6a5-03c181977ddc.png)

Please guide me in the right direction.

**Comment by metonym** [comment]
That's in development and it's because the `index.js` exposes 150+ components. If you're using a bundler, only the component that you actually use should be included in the final bundle.

As outlined in the README, I'd recommend using the Carbon [`optimizeImports` preprocessor](https://github.com/carbon-design-system/carbon-components-svelte#preprocessors) to optimize the imports for the development. It will rewrite the imports to resolve to the source component.

**Comment by ohbob** [comment]
> That's in development and it's because the `index.js` exposes 150+ components. If you're using a bundler, only the components that you actually use should be included in the final bundle.
> 
> As outlined in the README, I'd recommend using the Carbon [`optimizeImports` preprocessor](https://github.com/carbon-design-system/carbon-components-svelte#preprocessors) to optimize the imports for the development. It will rewrite the imports to resolve to the source component.

That seemed to fix the problem with the components, thank you! What about css, can we some how get rid of the 600kb not used css? And only add to the build the ones that are used?

**Comment by metonym** [comment]
To only include CSS you need, you'll have to use SCSS with the `carbon-components` package.

See the official guide here: https://github.com/carbon-design-system/carbon/blob/3536b86f990a6016dfbeac9dd118fc21c4431dcb/docs/guides/sass.md#optimizing-your-sass-builds

Essentially, in addition to the global and reset styles, you'll need to import SCSS per component. This will indeed be produce a smaller CSS bundle size if you only use a subset of the components.

```css
$css--font-face: true;
$css--helpers: true;
$css--body: true;
$css--use-layer: true;
$css--reset: true;
$css--default-type: true;
$css--plex: true;

// Include defaults typically provided through the `styles.scss` entrypoint
@import 'carbon-components/scss/globals/scss/_css--reset.scss';
@import 'carbon-components/scss/globals/scss/_css--font-face.scss';
@import 'carbon-components/scss/globals/scss/_css--helpers.scss';
@import 'carbon-components/scss/globals/scss/_css--body.scss';

// Optionally include the grid
@import 'carbon-components/scss/globals/grid/_grid.scss';

// Optionally include components that you need
@import 'carbon-components/scss/components/button/button';
```

**Comment by ohbob** [comment]
Thank you. Just a dumb thought, that the imports should be already in each of the components, to make life more easy for people with out the overhead.
