### ISSUE TITLE
Body scrollbar is restored when closing overlaying Modal

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#1324]
When a Modal is opened the `bx--body--with-modal-open` class gets added to the body, which prevents scrolling. If multiple Modals are shown and the topmost Modal is closed, the class gets removed, even though there are still modals open.

[REPL](https://svelte.dev/repl/693091ac1b344df5974353578633c1f3?version=3.48.0)

(If all modals would have to be in a strict hierarchy, this probably could be solved using a context within the modal component, but as shown in the REPL, the Modals can also be next to each other in the DOM, if the order is correct.)

**Comment by metonym** [comment]
Fixed in [v0.65.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.65.0)
