### ISSUE TITLE
Placeholder prop in `ToolbarSearch` component...

### ISSUE THREAD

**Issue by Addeuz** [carbon-design-system/carbon-components-svelte#1351]
I think a placeholder prop for the `ToolbarSearch` component would be easy to add since the component basically just wraps the `Search` component which takes the placeholder prop...

And we would like to use it since our app is in Swedish so "Search..." isn't the best for us..

**Comment by metonym** [comment]
It seems that `$$restProps` is already spread to the `Search` component, so the `placeholder` prop should work.

https://svelte.dev/repl/fab1182fb1ca4391a991793f1b253931?version=3.48.0

Is it because there is not TS support/highlighting?

**Comment by Addeuz** [comment]
I must've been blind when testing the component. That works of course. But it also has the `placeholder` prop from this part in the `ToolBarSearch.svelte.d.ts` file: `extends svelte.JSX.HTMLAttributes<HTMLElementTagNameMap["input"]>`...

I feel so stupid 😅
