### ISSUE TITLE
Cannot read properties of null (reading 'querySelector') on ComposedModal.svelte

### ISSUE THREAD

**Issue by rkakrik** [carbon-design-system/carbon-components-svelte#1360]
I see this message in the logs:
`
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelector')
    at focus (ComposedModal.svelte? [sm]:69:31)
    at ComposedModal.svelte? [sm]:82:7
`
But the ComposedModal works fine. Need to change something?
P.S.: ComposedModal placed before slot for login

**Comment by metonym** [comment]
Fixed in [v0.66.1](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.66.1)
