### ISSUE TITLE
Treeview: Display node explicitly

### ISSUE THREAD

**Issue by furunameko** [carbon-design-system/carbon-components-svelte#1377]
Is there a function like the see method in Tkinter's Treeview?
https://docs.python.org/3/library/tkinter.ttk.html#tkinter.ttk.Treeview.see

Thanks.

**Comment by metonym** [comment]
A `showNode` accessor has been added in [v0.82.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.82.0).

The method accepts a `node.id` and will expand, focus, and select the matching node.

[Docs.](https://svelte.carbondesignsystem.com/components/TreeView#show-a-specific-node)
