### ISSUE TITLE
the content of the  overfolwmenu  component is obscured.

### ISSUE THREAD

**Issue by dybxin** [carbon-design-system/carbon-components-svelte#1378]
the content of the  overfolwmenu  component is obscured.
![Screenshot from 2022-06-29 11-41-22](https://user-images.githubusercontent.com/14888437/176347316-5d6c52f9-1a5f-442d-935c-27968ee37b37.png)

**Comment by metonym** [comment]
In this case, you can set `flipped` to `true` so that the menu is anchored on the right side.

[Docs](https://carbon-components-svelte.onrender.com/components/OverflowMenu#flipped)

```svelte
<OverflowMenu flipped>
  ...
</OverflowMenu>
```

**Comment by dybxin** [comment]
@metonym thanks a lot.
