### ISSUE TITLE
shouldFilterRows Does Not Display Correct Number of Results

### ISSUE THREAD

**Issue by JuliaBonita** [carbon-design-system/carbon-components-svelte#1393]
Hello, thank you for this project. I'm learning how to use the dataTable component. One issue I noticed is that when using the `shouldFilterRows` feature, the "1–x of x items" footer message is not accurate after filtering because it doesn't get updated with the currently visible number of filtered results. For example, let's say I have 100 items in the table and the filtered results displays 3 rows, that footer message should display: "1–3 of 3 items (filtered)". 

I experimented with various custom functions for the `shouldFilterRows` prop because I thought maybe I could use some custom logic to update the `totalItems` prop with the `rows.length` value, but I don't see any `onUpdate` event attached to the Pagination or dataTable components that would enable me to update `totalItems` when the filtered results change. (The Pagination component's existing `onUpdate` event only fires when the user manually changes the pagination parameters, not when the results are filtered.)

Does anybody know how to update the filtered result count without modifying the library's source code?

**Comment by MrPurple6411** [comment]
I came here to make this same report and ask if it would be possible to expose the filtered count so that we can bind it to the same variable we bind the pagination total to which should allow it to update properly.

or even better just detect if the table has a pagination component attached and if it does then just auto set it.

**Comment by metonym** [comment]
Thanks for raising this. What's tricky is that – if using a paginated datatable – the `DataTable` and `Pagination` are sibling components. As a result, context wouldn't be applicable (unless another shared ancestor component is introduced).

However, your suggestion of binding to the total filtered rows and passing it to `Pagination` should work.

**Comment by metonym** [comment]
Supported in [v0.70.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.70.0).

Bind to the `filteredRowIds` prop in `ToolbarSearch` and pass its length to `totalItems` in `Pagination`:

```svelte
<ToolbarSearch
  value="round"
  shouldFilterRows
  bind:filteredRowIds
/>

<Pagination
  bind:pageSize
  bind:page
  totalItems="{filteredRowIds.length}"
  pageSizeInputDisabled
/>

```

Refer to the [updated "Filterable" example](https://carbon-components-svelte.onrender.com/components/DataTable#filterable) for a full example.
