### ISSUE TITLE
ContextMenu doesn't actually function as a component

### ISSUE THREAD

**Issue by Gilgahex** [carbon-design-system/carbon-components-svelte#1404]
When I import ContextMenu it doesn't seem to attach properly and just displays the options as raw HTML

I'm using @sveltejs/kit@1.0.0-next.355

![Screenshot_2022-07-16_13-15-09](https://user-images.githubusercontent.com/30332451/179370721-a09fcc57-63d8-4a99-8702-c1c481e39774.png)

![Screenshot_2022-07-16_13-15-53](https://user-images.githubusercontent.com/30332451/179370722-c34b0f54-6c96-43c4-82ff-6f19c8e5949a.png)

**Comment by metonym** [comment]
Where are you importing the Carbon styles?

**Comment by Gilgahex** [comment]
> Where are you importing the Carbon styles?

I only want the ContextMenu where it makes sense in the webApp and not on every page like the blog entries

**Comment by metonym** [comment]
Styles must be imported separately. See https://github.com/carbon-design-system/carbon-components-svelte#styling
