### ISSUE TITLE
Bug in filterable ComboBox: "undefined" instead of custom label

### ISSUE THREAD

**Issue by hffmr** [carbon-design-system/carbon-components-svelte#1405]
The filterable ComboBox using `shouldFilterItem` doesn't fully support the custom label set by `itemToString` when displaying the selected item in the input field and displays `undefined` instead:

![Illustration of the issue](https://user-images.githubusercontent.com/9038185/179599455-33545f13-5aab-4506-88d4-92fe713c7284.gif)

I traced it down to lines like the following (there are multiple occurrences):

https://github.com/carbon-design-system/carbon-components-svelte/blob/f8e400f2edd971f41dacfbc21bfff4ee059e5163/src/ComboBox/ComboBox.svelte#L297

In my opinion, this line should make use of the `itemToString`, e.g., `value = itemToString(filteredItems[highlightedIndex]);` similar to this line:
https://github.com/carbon-design-system/carbon-components-svelte/blob/f8e400f2edd971f41dacfbc21bfff4ee059e5163/src/ComboBox/ComboBox.svelte#L394

Should I create a pull request for this?

**Comment by metonym** [comment]
Thanks for flagging – PRs welcome.

**Comment by hffmr** [comment]
Hi @metonym! I created a PR and linked it to this issue. Please let me know if this works for you or if I can be of any more assistance.

**Comment by metonym** [comment]
Fixed in [v0.67.2](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.67.2).
