### ISSUE TITLE
Upgrading from 0.41 results in "Cannot read properties of undefined (reading ‘$$’)"

### ISSUE THREAD

**Issue by NigelCunningham** [carbon-design-system/carbon-components-svelte#1427]
Hi there.

I'm trying to upgrade my (previously working) project to use newer versions of the dependencies. I've been using Carbon components and am running into the above error message. I've done a fair bit of Googling, without success so far, but I have manged to make a set of minimal steps to reproduce the issue:

1. With Meteor 2.7.3 (I'm using the git repo, on tag release/METEOR@2.7.3), run meteor create test --svelte
2. meteor run
3. meteor npm i --save carbon-components-svelte
4. Edit imports/ui/App.svelte, adding:
    import { Button } from 'carbon-components-svelte';
5. Modify button to Button in both places on line 14.

Things that I've tried:
1. Update svelte to ^3.48 (https://github.com/carbon-design-system/carbon-components-svelte says it requires this)
2. Downgrade carbon-components-svelte to 0.60 or 0.50, both without success.

The working version is using carbon-components-svelte 0.41.

I'm thinking the issue is in carbon-components-svelte because if I just upgrade carbon-components-svelte, that's what breaks my build. I can of course find the issue reported elsewhere, but not a solution that is helping in this case.

Can someone help, please? Thanks in advance!

**Comment by metonym** [comment]
This seems like a similar error to #896.

Can you try the approach suggested in this [comment](https://github.com/carbon-design-system/carbon-components-svelte/issues/896#issuecomment-1009389564)?

**Comment by NigelCunningham** [comment]
Thanks for the reply. Do I make that change in the package.json for this repo (do something like forking the repo and install my fork?)

**Comment by NigelCunningham** [comment]
Yes, doing the above does the trick.
