### ISSUE TITLE
Bug in the v0.67.6 release.

### ISSUE THREAD

**Issue by stilet** [carbon-design-system/carbon-components-svelte#1433]
Expandable style in DateTable does not work in production
![fixCarbonComponentSvelte2](https://user-images.githubusercontent.com/99677/183829522-215d062a-e784-43b3-b271-0eb58e5b89c1.png)
Arrows don't work

**Comment by metonym** [comment]
Can you provide a minimal repro?

The [Expandable and selectable example](https://carbon-components-svelte.onrender.com/components/DataTable#expandable-and-selectable) in the docs appears to work.
