### ISSUE TITLE
Show Datatable Toolbar with No Selection (expose as optional)

### ISSUE THREAD

**Issue by naegelin** [carbon-design-system/carbon-components-svelte#1437]
Currently the datatable batch action toolbar hides when no items are selected in batch selection mode. This is an incorrect assumption imho. 

Hypothetical scenario - A user wants to remove all load balancer associations and 'save' 

1. Go to: https://carbon-components-svelte.onrender.com/framed/DataTable/DataTableBatchSelectionToolbar?theme=white
2. User unchecks all the load balancers
3. User needs to save this state (does not want any load balancers).

**Comment by metonym** [comment]
Released in [v0.68.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.68.0)
