### ISSUE TITLE
Pressing Cancel on Datatable toolbarbatchactions sets selectedRowIds to empty list

### ISSUE THREAD

**Issue by naegelin** [carbon-design-system/carbon-components-svelte#1438]
When using the DataTable along with a toolbar + toolbarbatchactions, the datatable may be initialized with a set of selectedRowIds. For example, a data store of already selected "load balancers" is rendered. 

When batchSelection is enabled and a user makes changes to the pre-loaded selection and decides to "cancel",  the initially selectedRowIds are cleared.

Since the user clicked 'cancel' to negate his changes, the selectedRowIds should probably be restored to the selection prior to any changes and not simply an empty list.

Since there is no way to bind to the cancel button's on:click from the toolbarbatchactions.svelte , the cancel button becomes a "clear selection" button instead of a true "cancel". 

I would recommend exposing the on:click event of the cancel button in the toolbarbatchactions component file so that the behavior can be developer defined.  

Update:  A demo of this behavior can be seen here: https://carbon-components-svelte.onrender.com/framed/DataTable/DataTableBatchSelectionToolbar?theme=white

**Comment by metonym** [comment]
Released in [v0.68.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.68.0)
