### ISSUE TITLE
TreeView expandNodes

### ISSUE THREAD

**Issue by Tihomir971** [carbon-design-system/carbon-components-svelte#1439]
I'm trying to use something like this:
on:select={(e) => {
    if (e.detail.leaf === false) {
        if (e.detail.expanded === false) {
            treeview?.expandNodes((node) => node.id === activeId);
	} else {
	    treeview?.collapseNodes((node) => node.id === activeId);
	}
} 

It works on first and second level node but on third level it colapse first level

**Comment by metonym** [comment]
Have a look at the new [`showNode`](https://svelte.carbondesignsystem.com/components/TreeView#show-a-specific-node) accessor (added in [v0.82.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.82.0)), which I think may address this use case. The method accepts a `node.id` and will expand, focus, and select the matching node.
