### ISSUE TITLE
Nested <li> in <ol> are not displayed in an indented outline format.

### ISSUE THREAD

**Issue by keehun** [carbon-design-system/carbon-components-svelte#1460]
I have some raw HTML content coming from my CMS backend (this is an exception rather than the norm, and the allowed HTML is very strictly controlled on the backend). I am embedding this into a Svelte component by doing: `{@html object.description}`.

This has been working really well for me. However, when Svelte/Carbon renders it for a nested ordered list like this:
```html
<p>Movements:</p>
<ol>
	<li>GROUP 1
	<ol type="a">
		<li>Prelude</li>
		<li>Carol</li>
		<li>Christmas Dance</li>
	</ol>
	</li>
	<li>GROUP 2
	<ol type="a">
		<li>Ballad</li>
		<li>Moto perpetuo</li>
	</ol>
	</li>
	<li>GROUP 3
	<ol type="a">
		<li>Musette</li>
		<li>Polka melancolique</li>
		<li>Galop</li>
	</ol>
	</li>
</ol>
```

It gets rendered like so:
<img width="545" alt="Screen Shot 2022-08-21 at 20 00 45" src="https://user-images.githubusercontent.com/77378/185819778-718341a4-9be6-469c-b903-01b627b051e9.png">

The `{@html}` content is below the "Notes" heading.

How can I get a truly indented nested list as I would expect? (Please don't mind the `<ol>` being turned into square bullets—that's currently on purpose but may later change.)

**Comment by metonym** [comment]
This is because Carbon resets `ul` and `ol` styles and re-styles them with "bx--list--ordered" and "bx--list__item" classes.

Two solutions come to mind:

- write a preprocessor that applies the expected Carbon classes to the `ol` and `li` markup
- re-apply the Carbon styles to the markup

```css
.ol:not(ol ol) {
  counter-reset: item;
}
```

**Comment by keehun** [comment]
Thanks @metonym!

Turns out the real reason the nested lists were showing up "flat" was due to the numerous `padding: 0` rules.

When I wrote:
```css
li > ol {
    padding: revert !important;
}
```

The nested list displayed the way I expected it to.
