### ISSUE TITLE
`<Content>`'s style tag breaks if false

### ISSUE THREAD

**Issue by tmarsik42** [carbon-design-system/carbon-components-svelte#1467]
https://github.com/carbon-design-system/carbon-components-svelte/blob/6ec48312ffa1a31c0e366d9bd74b8a1f4d46292c/src/UIShell/Content.svelte#L21

1. if `unsetLeftMargin && 'margin-left: 0;'` results to false `&&restProps.style` wont get applied, because the whole style tag is invalid
2. one more closing brace

[simple repro](https://svelte.dev/repl/7d2b6b1bb3384c13a25b2828e06d056d?version=3.49.0)

Proposed solution:
`style="{unsetLeftMargin ? 'margin-left: 0;' : ''} {$$restProps.style}"`

I'd make a PR but I couldn't make symlinks to work with yarn berry and don't have time currently to fiddle with it.

Thanks!

**Comment by metonym** [comment]
Thank you for the repro and suggestion.

**Comment by metonym** [comment]
Fixed in [v0.70.2](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.70.2).
