### ISSUE TITLE
`Modal` - submitting with `primaryButtonDisabled`

### ISSUE THREAD

**Issue by tmarsik42** [carbon-design-system/carbon-components-svelte#1485]
Modal's `primaryButtonDisabled` and  `shouldSubmitOnEnter` both set to true, results in being able to submit Modal with primary button disabled.

Expected behavior:
- primary btn disabled = can't submit
- primary btn enabled = can submit

[Repl](https://svelte.dev/repl/acd821474a1648f688597ce4ffd4004b?version=3.50.1)
- open console
- open modal (`primaryButtonDisabled` is set to true)
- press enter
- on:submit logs in console

I can make a PR if I find a few mins.

**Comment by metonym** [comment]
Fixed in [v0.70.7](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.70.7)
