### ISSUE TITLE
Pagination: add `change` event

### ISSUE THREAD

**Issue by theetrain** [carbon-design-system/carbon-components-svelte#1491]
Thanks as always for maintaining.

I'm making use of pagination's `update` event to listen to whenever the user clicks on the next page button, previous page button, or changes page via dropdown. Though I noticed the `update` event actually gets called whenever `pageSize` or `page` changes:

https://github.com/carbon-design-system/carbon-components-svelte/blob/17db8e25d388759005e957805c085be4c8a200dc/src/Pagination/Pagination.svelte#L89

If I have 2 pagination toolbars on a page, such as one above and one below a DataTable, then the `update` handler will get called twice when the user changes page on either Pagination toolbar. I'm not using 2-way data binding because I'm fetching page data asynchronously after the user changes the page.

I propose a new `change` event to dispatch:

- `change`: dispatches whenever the user interacts with pagination, either by clicking the next/prev buttons, or changing the value in the page Select

With `on:change` I'll be able to make a remote `fetch` to update my DataTable without a concern for `update` dispatching more than once.

I'd be happy to contribute if you approve this proposal.

**Comment by metonym** [comment]
Thank you for explaining the use case.

I agree that it would be nice to have an event that wasn't triggered if either `pageSize` or `page` change – rather, an event should fire for the specific interaction.

The component already dispatches `click:button--previous` and `click:button--next` events. However, it's missing events when changing the value in both the page size `Select` and current page `Select`. It sounds like having a generic `change` event only triggered through the UI would be useful to hook into. A PR would be welcome.

**Comment by theetrain** [comment]
Released in [v0.71.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.71.0)
