### ISSUE TITLE
DatePicker does not show warning state triangle if datePickerType is 'single'

### ISSUE THREAD

**Issue by cubic3d** [carbon-design-system/carbon-components-svelte#1498]
Using the example code from the docs
```
<DatePicker>
  <DatePickerInput
    warn
    warnText="This info will not be stored"
    labelText="Date of birth"
    placeholder="mm/dd/yyyy"
  />
</DatePicker>
```
shows the correct warning state
![image](https://user-images.githubusercontent.com/4047015/192469635-37573af1-0248-4f28-8a39-3c6021476954.png)

but adding `datePickerType="single"` to DatePicker only shows the text under it and no yellow triangle or other visual indication of the warning.
![image](https://user-images.githubusercontent.com/4047015/192470329-d9863d50-580b-439f-a531-729d7755a6aa.png)

**Comment by metonym** [comment]
Fixed in [v0.70.10](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.70.10)
