### ISSUE TITLE
HeaderSearch wrong layout

### ISSUE THREAD

**Issue by farfromrefug** [carbon-design-system/carbon-components-svelte#1504]
In the latest version of the svelte components the `HeaderSearch` seems to be wrongly layed out
https://carbon-components-svelte.onrender.com/components/UIShell#header-with-global-search
<img width="535" alt="Screenshot 2022-10-02 at 15 01 52" src="https://user-images.githubusercontent.com/655344/193455399-508234f1-95f0-485d-a94d-1ebe60ac0fda.png">
It is supposed to be on the same "line", right? With the current layout when there is  a search layout it hides the input and the close button

**Comment by metonym** [comment]
Fixed in [v0.70.10](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.70.10)
