### ISSUE TITLE
Dropdown component has keyboard accessibility issues

### ISSUE THREAD

**Issue by TheophileMot** [carbon-design-system/carbon-components-svelte#1505]
The `Dropdown` component doesn't work very well with the keyboard: in particular, when it's closed, then using the arrow keys leads to strange behaviour and will typically make the component crash with the following error:
```
Cannot read properties of null (reading 'scrollIntoView')
```

**To reproduce:**
1. Press the up/down arrow keys when the Dropdown is closed;
2. Press enter or space.

Here is a [REPL](https://svelte.dev/repl/a2b86570aa6845f19ce23b2fb5a083c6?version=3.46.4).

**Comment by metonym** [comment]
Thanks for the detailed repro – fixed in [v0.70.10](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.70.10).

**Comment by TheophileMot** [comment]
@metonym Thank you for swiftly addressing this, as always.

I think the latest changes address the critical issue of the component crashing (`reading 'scrollIntoView'`), but the keyboard behaviour is still a bit mysterious.

On the same [REPL](https://svelte.dev/repl/a2b86570aa6845f19ce23b2fb5a083c6?version=3.46.4), if you hit the up/down arrows on the Dropdown when it's closed, then hit enter, it will choose a new element, but it isn't really clear how this happens.

For example:
* Suppose the currently selected element is A.
* With the Dropdown closed, hit [up].
* Hit [enter].

Now the selected element will be C: in other words, hitting [up] has jumped from the top to the bottom of the list. Furthermore, there's no indication of a change until the user hits [enter].

**Comment by TheophileMot** [comment]
Similar examples to show how the behaviour is mysterious:

Again on the same REPL,

* Start at A.
* Hit [up] twice, then [enter].
* Now the result is B.

or:

* Start at A.
* Hit [down] once, then [enter].
* The dropdown opens.

etc.
