### ISSUE TITLE
`NumberInput`: unintuitive interaction between `allowEmpty` and `min` props

### ISSUE THREAD

**Issue by malinowskip** [carbon-design-system/carbon-components-svelte#1510]
Currently, if the `allowEmpty` option is set to `true` and the `min` prop is set to a positive integer, but the value is empty (`null`), the component displays an error. I think the intuitive behavior in this case would be for the `allowEmpty` prop to take precedence, i.e. the component should tolerate a `null` value.

**Comment by metonym** [comment]
Fixed in [v0.70.11](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.70.11)
