### ISSUE TITLE
Consistent page indexing between Pagination and PaginationNav

### ISSUE THREAD

**Issue by theetrain** [carbon-design-system/carbon-components-svelte#1513]
## Issue

I noticed the [`<Pagination />`](https://carbon-components-svelte.onrender.com/components/Pagination) and [`<PaginationNav />`](https://carbon-components-svelte.onrender.com/components/PaginationNav) components both have a `page` prop, except they have different indexing:

- `Pagination`'s `page` prop is 1-indexed
- `PaginationNav`'s `page` prop is 0-indexed

Would it be a good idea to have both of these `page` props be consistent? 

## Proposal

I would elect for 1-indexed counting since it's more indicative of the active and visible page number, and would line up with potential `url.searchParams` if used such as `?page=1`. Any JS arrays or database rows that are 0-indexed could have some `+1` math added to them. It would help for applications that make use of both `Pagination` and `PaginationNav` without having to maintain off-by-one logic between the two. Either way, this would be a breaking change if implemented.

Thanks for maintaining.

**Comment by metonym** [comment]
Good catch. Your reasoning is sound. I'm on board with changing `page` in `PaginationNav` to be 1-indexed.

**Comment by theetrain** [comment]
Sounds good! I can help contribute a PR sometime in the following week.

**Comment by theetrain** [comment]
Released in [v0.71.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.71.0)
