### ISSUE TITLE
Add icon description to InlineNotification icon

### ISSUE THREAD

**Issue by theetrain** [carbon-design-system/carbon-components-svelte#1563]
On this line:

https://github.com/carbon-design-system/carbon-components-svelte/blob/ae3445158315f7f834ae7f4be75bfd79aea5a299/src/Notification/InlineNotification.svelte#L85

Depending on the value of `kind`, I would like to provide this icon a default description per kind, rather than the default "Closes notification" since it isn't interactive. For example:

* `kind` === `error`, icon description "no-entry icon"
* `kind` === `warning-alt`, icon description "warning triangle"

**Comment by brunnerh** [comment]
Related: #672

**Comment by theetrain** [comment]
Released in [v0.71.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.71.0)
