### ISSUE TITLE
Vite 4 + SvelteKit building error

### ISSUE THREAD

**Issue by tiagoapp** [carbon-design-system/carbon-components-svelte#1586]
I've recently updated SvelteKit to stable 1.0 / Vite 4.0.1 and I'm keep getting this error when trying to build, which wasn't happening before.

```
[vite-plugin-sveltekit-setup] Unexpected token (279:14) in  /node_modules/carbon-components/es/components/modal/modal.js
/node_modules/carbon-components/es/components/modal/modal.js:279:14
277: 
278:           if (process.env.NODE_ENV !== "production") {
279:             process.env.NODE_ENV !== "production" ? warning(focusableItem, "Modals need to contain a focusable element by either using " + "`".concat(_this2.options.selectorPrimaryFocus, "` or settings.selectorTabbable.")) : void 0;
                   ^
280:           }
281:         }
```

I'm not really even using the Modal component anywhere... any ideas?

**Comment by metonym** [comment]
The library it's warning about is `carbon-components`, not `carbon-components-svelte`. I assume you're using `carbon-components` for the SCSS.

My first guess would be to instruct Vite to ignore optimizing `carbon-components`:

```js
optimizeDeps: {
  exclude: ["carbon-components"]
}
```

**Comment by tiagoapp** [comment]
> The library it's warning about is `carbon-components`, not `carbon-components-svelte`. I assume you're using `carbon-components` for the SCSS.
> 
> My first guess would be to instruct Vite to ignore optimizing `carbon-components`:
> 
> ```js
> optimizeDeps: {
>   exclude: ["carbon-components"]
> }
> ```

Thanks! That solved the problem indeed!
