### ISSUE TITLE
Refactor: use `style:` directive

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon-components-svelte#1604]
`style:` directives have been supported for almost a year ([3.46](https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md#3460)). We should refactor existing code so that `$$restProps.style` can be eliminated.

```diff
{...$$restProps}
- style="left: {x}px; top: {y}px; {$$restProps.style}"
+ style:left="{x}px"
+ style:top="{y}px"
```

Using style directives with `$$restProps` is cleaner. However, there is a breaking change: consumers will not be able to override style properties set as directives.

**Comment by theetrain** [comment]
Maybe we can support both: forward `class` and `style`, and use `style:` for internal code so that logic is more maintainable.
