### ISSUE TITLE
[TreeView] Make children reactive

### ISSUE THREAD

**Issue by cubic3d** [carbon-design-system/carbon-components-svelte#1637]
I would really like to see the `children` property of TreeView to be reactive and bindable. This would allow to apply dynamic icons to entries and remove/add those in case they represent e.g. directories and files.

What do you think?

**Comment by theetrain** [comment]
Hi @cubic3d; I put together this REPL to demonstrate dynamically-added children https://svelte.dev/repl/624009128498470daa067188def4e874?version=3.55.1

Is this what you're trying to achieve? So long as you reassign the value provided to the `children` prop, it should be reactive. Let me know if I misunderstood.

**Comment by cubic3d** [comment]
@theetrain This is actually more or less the behaviour I wanted to achieve. Thank you very much for the help, seems like I got into the reactive assignment trap - it works now as expected and children can be modified. Somehow expected that it would need a change on component level ;)
