### ISSUE TITLE
DropDown "selectedItem" is the last selection, not the current

### ISSUE THREAD

**Issue by chipnetics** [carbon-design-system/carbon-components-svelte#1645]
Unsure if this is expected behaviour and the wording is just misleading.  But if you print `console.log(e.detail)` when selecting an element in a DropDown component, the `selectedId` is correct and properly reflects the active selection.  However `selectedItem` appears to be what you _last_ had selected (i.e. the selection you moved away from).

**Comment by theetrain** [comment]
This is now available in [v0.72.2](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.72.2).
