### ISSUE TITLE
BUG on docs page

### ISSUE THREAD

**Issue by dsm-72** [carbon-design-system/carbon-components-svelte#1649]
Please view this page
https://carbon-components-svelte.onrender.com/components/UIShell

Notice that the right side bar is off the screen.
Not sure if I should use the UI library if the UI library breaks.

**Comment by brunnerh** [comment]
I have no idea what you are referring to.
Please at least describe what you mean and ideally add a screenshot + browser version.

**Comment by dsm-72** [comment]
@brunnerh 
<img width="1435" alt="Screenshot 2023-02-04 at 9 18 14 AM" src="https://user-images.githubusercontent.com/100158155/216772552-7ea1c938-3afc-4f35-b187-74e70402241d.png">

**Comment by dsm-72** [comment]
Note this holds for Firefox too!
![Screenshot 2023-02-04 at 09-50-59 UIShell](https://user-images.githubusercontent.com/100158155/216773912-3d91e536-91b5-4e06-ac44-8fbc191a90eb.png)

**Comment by brunnerh** [comment]
This only happens on "smaller" screens which is why I did not see it.
Some page content is not shrinking correctly (which has nothing to do with the component library itself, it's just the docs).

**Comment by dsm-72** [comment]
@brunnerh strange. Can the docs be fixed then? As "smaller" is like full-size laptop (14") and it is only on this page, suggesting it is the UIShell component taking up too much horizontal space (e.g. using width:vh)

**Comment by brunnerh** [comment]
Well, I work on 27" screens (of course the resolution and system/browser scale settings are more important than the physical size).
Does not look like this is isolated; the [`Accordion`](https://carbon-components-svelte.onrender.com/components/Accordion) page also overflows for me if I reduce the width.

Should be fixable by adjusting the layout.

**Comment by theetrain** [comment]
I've noted the bug and we'll fix it in time. Since responsive design impacts usability, I agree it should be fixed.

**Comment by chipnetics** [comment]
I can see similar behaviour on https://carbon-components-svelte.onrender.com/components/OrderedList as well, the numbering is outside the bounding box. That said, this probably isn't a component that gets much use anyhow....
