### ISSUE TITLE
Text input: icons overlap when `readonly` and `invalid`

### ISSUE THREAD

**Issue by ptrxyz** [carbon-design-system/carbon-components-svelte#1664]
If a text input is `readonly` and `invalid` at the same time, the icons overlap:

```tsx
<TextInput
  name="mybox"
  readonly
  invalid={true}
/>
```

will result in this:

![image](https://user-images.githubusercontent.com/209056/219982050-07c0ad9f-0913-435b-b6f4-e8347d4b4cd6.png)

(see the icons on the right overlapping)

**Comment by theetrain** [comment]
I see what you mean; I reproduced this in a REPL: https://svelte.dev/repl/c50124bd12e446acbb0183c902013197?version=3.55.1

I see that the React component displays the `readOnly` state when both `readOnly` and `invalid` are defined:

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/12798751/219989380-dfa8da4c-7445-4942-8662-7a52dd763c2f.png">

Let's implement the same behaviour in Svelte. Let us know if you'd like to contribute this!

**Comment by theetrain** [comment]
Fixed in [v0.73.2](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.73.2).
