### ISSUE TITLE
Loading and InlineLoading — find a better way to announce description

### ISSUE THREAD

**Issue by theetrain** [carbon-design-system/carbon-components-svelte#1670]
Currently on Safari + VoiceOver, the following code:

```html
<InlineLoading description="Finding products..." />
```

Announces:

> Active loading indicator. Active loading indicator. Active loading indicator.

A few ways we can improve this:

- toggle `aria-busy` depending on state
- have the SVG icon's `<title>` indicate the loading state in English, and can be overridden with a prop for every state
- ensure the `description` prop gets announced

**Comment by metonym** [comment]
Fixed in [v0.79.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.79.0)
