### ISSUE TITLE
The label element will be rendered in the Slider component even if the title parameter is not passed

### ISSUE THREAD

**Issue by siaikin** [carbon-design-system/carbon-components-svelte#1682]
https://github.com/carbon-design-system/carbon-components-svelte/blob/d2e471bbecbbaf24cad8fe1589e6363354a35471/src/Slider/Slider.svelte#L142

Because the label element had a 0.5 rem marginBottom, I was unable to align the Slider with the other form controls.

![image](https://user-images.githubusercontent.com/24749324/224368899-bf2e4c34-ef78-4d4c-b51a-f97110541dee.png)

**Comment by metonym** [comment]
Released in [v0.79.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.79.0)
