### ISSUE TITLE
[ProgressStep] aria-disabled not supported by implied role 'listitem'

### ISSUE THREAD

**Issue by theetrain** [carbon-design-system/carbon-components-svelte#1683]
Svelte 3.56.0 yields this warning:

> A11y: The attribute 'aria-disabled' is not supported by the role 'listitem'. This role is implicit on the element `<li>`

And it calls out this line:

https://github.com/carbon-design-system/carbon-components-svelte/blob/d2e471bbecbbaf24cad8fe1589e6363354a35471/src/ProgressIndicator/ProgressStep.svelte#L55-L58

We should address the warning; Carbon react does not use `aria-disabled` and instead makes use of `tabindex="-1"` on list buttons that are disabled.

**Comment by theetrain** [comment]
References: 
- https://www.w3.org/WAI/tutorials/forms/multi-page/#using-step-by-step-indicator
- https://designsystem.digital.gov/components/step-indicator/

Takeaways
- Use `aria-current="true"`
- Have visually-hidden text indicate completed, current, next, and disabled steps

Out of scope
- Allow hyperlinks to be added for progressive enhancement #1622

**Comment by pwwang** [comment]
It's not only `ProgressIndicator/ProgressStep` that is affected. Here is a list of components that are affected:

- ContextMenu
- OverflowMenu
- UIShell/HeaderNavMenu
- UIShell/SideNavMenu
- UIShell/HeaderSearch
- UIShell/HeaderNav
- Tabs
- TreeView/TreeView
- TreeView/TreeViewNodeList
- TreeView/TreeViewNode

**Comment by metonym** [comment]
@pwwang Thank you for flagging this. I submitted a PR here: https://github.com/carbon-design-system/carbon-components-svelte/issues/1683

**Comment by theetrain** [comment]
Resolved in [v0.73.5](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.73.5).
