### ISSUE TITLE
PasswordInput leaves an empty container below the input for non-existing helper text

### ISSUE THREAD

**Issue by gabrielleecredera** [carbon-design-system/carbon-components-svelte#1684]
When using the PasswordInput component, without providing a helper text, the component renders a container below the input, creating a 0.25rem gap in height (screenshot)
<img width="700" alt="Screenshot 2023-03-11 at 13 02 22" src="https://user-images.githubusercontent.com/92097847/224486100-e4b48e84-723f-4e77-a6d5-c35d34db33ac.png">
<img width="700" alt="Screenshot 2023-03-11 at 13 02 29" src="https://user-images.githubusercontent.com/92097847/224486101-b2e5f8ac-5e8c-42fd-bd74-d1cd926f41dd.png">

I believe that's a bug as the TextInput component does not have a 0.25rem gap below it when helper text is not provided
<img width="700" alt="Screenshot 2023-03-11 at 13 01 49" src="https://user-images.githubusercontent.com/92097847/224486063-657eebd3-4509-49b3-9950-f438f924cf8a.png">

**Comment by theetrain** [comment]
Good catch, the PasswordInput is missing this wrapper code as seen in TextInput

https://github.com/carbon-design-system/carbon-components-svelte/blob/d2e471bbecbbaf24cad8fe1589e6363354a35471/src/TextInput/TextInput.svelte#L118-L143

Whether or not `helperText` is defined, PasswordInput contains helperText's empty space.

**Comment by gabrielleecredera** [comment]
@theetrain thx for confirming the issue, i've raised a PR for this very straight forward fix that also adds an example in the docs. :)

**Comment by theetrain** [comment]
Now available in [v0.73.3](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.73.3).
