### ISSUE TITLE
[ContentSwitcher] - selecting breaks in svelte 3.56.0

### ISSUE THREAD

**Issue by tmarsik42** [carbon-design-system/carbon-components-svelte#1689]
ContentSwitcher's reactive variable 'selected' nor style do not work.

Broken repro
https://svelte.dev/repl/f5161c55d4ba42868b602c9cd30b67ba?version=3.56.0

Working repro
https://svelte.dev/repl/f5161c55d4ba42868b602c9cd30b67ba?version=3.55.1

Maybe it's a svelte issue related to this? https://github.com/sveltejs/svelte/issues/8374

**Comment by theetrain** [comment]
Yeah it's possibly related to the linked ticket. The maintainers intend to revert it here: https://github.com/sveltejs/svelte/pull/8382

Let's see if the issue resolves in the next Svelte patch.

**Comment by tmarsik42** [comment]
Works in 3.57.0 so I'll close.

https://svelte.dev/repl/f5161c55d4ba42868b602c9cd30b67ba?version=3.57.0
