### ISSUE TITLE
MultiSelect does not have a label/titleText slot

### ISSUE THREAD

**Issue by sachinbhutani** [carbon-design-system/carbon-components-svelte#1747]
Most of the other components, labels text is defined as a slot, hence I can do something like this to add icons to labels or to make labels bold: 
```
<NumberInput value={0} >
  <p slot="label"><strong>Enter a number</strong> <Add /></p>
</NumberInput>

<Select>
  <SelectItem value="white" />
  <SelectItem value="g10" />
  <SelectItem value="g80" />
  <SelectItem value="g90" />
  <SelectItem value="g100" />
  <p slot="labelText"><strong>Select a carbon theme<strong> <Add /></p>
</Select>
```

but MultiSelect component label(titleText) is not available as a slot

**Comment by theetrain** [comment]
Now available in [0.76.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.76.0)
