### ISSUE TITLE
Svelte `4.0.0`

### ISSUE THREAD

**Issue by ibilux** [carbon-design-system/carbon-components-svelte#1753]
**A lot of components showing errors when updated svelte to version `4.0.0`.**

**Comment by Mike968** [comment]
Expanding on this - Svelte depreciated SvelteComponentTyped

The PR: https://github.com/sveltejs/svelte/pull/8512

The types will need to be updated in account for this change.

**Comment by theetrain** [comment]
Thanks, everyone. I'm actively working to test carbon-components-svelte with Svelte 4. It requires a bit of work:

- upgrade dependencies and documentation to use ESM syntax
- add Svelte `^3.20.0 || ^4.0.0` to `peerDependencies`
- Update types (along with sveld)

I'll track this issue once a PR is ready.

**Comment by emehrkay** [comment]
I know you're working on fixing this, but is it possible to tell the svelte compiler to ignore these errors in the meantime?

**Comment by TrungRueta** [comment]
> I know you're working on fixing this, but is it possible to tell the svelte compiler to ignore these errors in the meantime?

I think you can temporary fix this issue with 2 things:

1. in `tsconfig.json` add `skipDefaultLibCheck: true` and `skipLibCheck: true`.
2. instance version svelte@^3 to package dependencies . `npm I svelte@^3`.

it can temporary disable incorrect check.

**Comment by TrungRueta** [comment]
Hi everyone, do we have any updated version to support this? 
When creating a new Sveltekit project, we must re-install Svelte version 3 to bypass the issue.

**Comment by metonym** [comment]
This library now supports Svelte 4 for TypeScript users in [v0.78.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.78.0).

The type definitions are still backward compatible with Svelte version 3; however, the minimum Svelte version is now 3.55 for TypeScript users.

## For TypeScript Users using Svelte 4

If you're using Svelte 4 with the icons/pictograms packages, you must upgrade them as well:

- Upgrade `carbon-icons-svelte` to version [12.1.0](https://github.com/carbon-design-system/carbon-icons-svelte/releases/tag/v12.1.0)
- Upgrade `carbon-pictograms-svelte` to version [12.6.0](https://github.com/carbon-design-system/carbon-pictograms-svelte/releases/tag/v12.6.0)
