### ISSUE TITLE
FileUploader: Unset label/description cause blank space

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#1775]
There are two elements for the properties `labelTitle` and `labelDescription` which always exist, even if the corresponding property is not set. This can cause unnecessary blank space internally or in relation to other content.

![image](https://github.com/carbon-design-system/carbon-components-svelte/assets/834235/dee0bc7a-5583-410b-a6e8-089f05c66fd9)
![image](https://github.com/carbon-design-system/carbon-components-svelte/assets/834235/5f521294-79fa-43c7-9a6c-71fb39747c5a)

Maybe the elements should be hidden or removed if the property is unset.

**Comment by metonym** [comment]
Fixed in [v0.79.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.79.0)
