### ISSUE TITLE
Forward onclick event for HeaderActionLink

### ISSUE THREAD

**Issue by mgreminger** [carbon-design-system/carbon-components-svelte#1796]
All of the UIShell components that wrap the anchor element forward the anchor element's `on:click` event (`SideNavMenuItem`, `HeaderNavItem`, `SideNavLink`, etc.). However, the `HeaderActionLink` component does not forward the `on:click` event for the anchor element that it wraps. Is it possible to update the library so that the `HeaderActionLink` forwards the `on:click` event? If desired, I'm happy to attempt a pull request for this feature.

**Comment by metonym** [comment]
That makes sense – a Pull Request would be appreciated.

**Comment by metonym** [comment]
Released in [v0.80.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.80.0)

**Comment by mgreminger** [comment]
Thanks for the release, much appreciated!
