### ISSUE TITLE
Missing types information

### ISSUE THREAD

**Issue by FalseDev** [carbon-design-system/carbon-components-svelte#1813]
I tried using the form example from [here](https://carbon-components-svelte.onrender.com/components/Form) but got the following errors from svelte LSP in Visual Studio Code:

```ts
Type '{ name: string; selected: string; }' is not assignable to type 'RadioButtonGroupProps'.
  Object literal may only specify known properties, and '"name"' does not exist in type 'RadioButtonGroupProps'.

Type '{ id: string; labelText: string; value: string; }' is not assignable to type 'SelectProps'.
  Object literal may only specify known properties, and '"value"' does not exist in type 'SelectProps'.
```

After digging things up, I finally figured out that the shown properties are missing from the type definitions.

Is there any way to temporarily fix this while a patch is being made?

**Comment by metonym** [comment]
The `name` prop has been added to `RadioButtonGroup` (#1037).

For the `Select`, the reason for the type error is that it's a typo. I've corrected this in the docs via #1841.

The correct prop to use on `Select` should be `selected` instead of `value`.

```diff
- <Select bind:value={selected} />
+ <Select bind:selected />
```
