### ISSUE TITLE
`RadioButtonGroup` should forward `name` to underlying input elements

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon-components-svelte#1814]
Identified two issues when triaging #1813:

- `RadioButtonGroup` should expose a `name` prop
- The `name` prop should be passed to the underlying `input` elements

**Comment by brunnerh** [comment]
- https://github.com/carbon-design-system/carbon-components-svelte/issues/1036

**Comment by metonym** [comment]
Dupe of #1036
