### ISSUE TITLE
Improve security practices for `carbon-components-svelte`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-components-svelte#1837]
Hey there, Carbon team member here! 👋 We'd like to ensure the security practices for packages published from the `carbon-design-system` GitHub org are in place and up to date. We'd like to work with you to get the following security practices implemented:

```[tasklist]
- [x] Add a security policy to the repository
- [x] Enable Security advisories
- [x] Enable Private vulnerability reporting
- [x] Enable Dependabot alerts
- [x] Enable Code scanning alerts
- [x] Enable Secret scanning alerts
- [x] Publish your package(s) to npm with [provenance statements](https://docs.npmjs.com/generating-provenance-statements)
```

Most of these can be found under the Security tab for this repository. You may already have most of these implemented and turned on - if so, awesome! 

For establishing a security policy, the existing [security policy for the Carbon monorepo](https://github.com/carbon-design-system/carbon/security/policy) can be used as a template if you'd like. It can be modified to include proper version(s) for your package and any other attributes unique to your project that you may want to highlight.

I'm happy to meet up and chat about this if you'd like, just let me know. Thanks in advance for your help in ensuring security and stability across the Carbon ecosystem! 🙏 💙

**Comment by metonym** [comment]
Thanks Taylor.

I completed the checklist, including adding a [new workflow](https://github.com/carbon-design-system/carbon-components-svelte/blob/master/.github/workflows/release.yml) that publishes this package to NPM with provenance.

**Comment by tay1orjones** [comment]
@metonym Awesome, thanks!
