### ISSUE TITLE
`SelectItem` properties `style`/`class` missing from types.

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#1839]
The values for `style`/`class` are pulled from `$$restProps` but the types only contain the defined props, leading to errors when using TypeScript.

https://github.com/carbon-design-system/carbon-components-svelte/blob/fee236194bbfc7aa9225fe694aa0c7fc098dd6dc/src/Select/SelectItem.svelte#L35-L43

Properties should probably either be explicit or all `$$restProps` should be spread along with a `/** @restProps {option} */` annotation.

**Comment by metonym** [comment]
Spreading `$$restProps` previously caused a bug that broke `select` bindings (https://github.com/carbon-design-system/carbon-components-svelte/pull/452). However, that was three years ago, and I haven't look into if it works.

**Comment by metonym** [comment]
Fixed in [v0.81.3](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.81.3)
