### ISSUE TITLE
no exports condition for svelte

### ISSUE THREAD

**Issue by hslee2008** [carbon-design-system/carbon-components-svelte#1863]
[vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

carbon-components-svelte@0.82.4

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.

**Comment by metonym** [comment]
Re-opening. Noticing a bug where types cannot be resolved. Working on a fix.

<img width="903" alt="Screenshot 2023-12-16 at 5 30 15 PM" src="https://github.com/carbon-design-system/carbon-components-svelte/assets/10718366/c5f1eb95-189e-470c-84a3-cd6b39f49550">

**Comment by metonym** [comment]
Type-related errors should be fixed in [v0.82.6](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.82.6)
