### ISSUE TITLE
TextInput v11

### ISSUE THREAD

**Issue by theetrain** [carbon-design-system/carbon-components-svelte#1888]
Spun off from #1629

- [x] Follow v11 styles for TextInput
- [x] Follow v11 styles for TextInputSkeleton
- [x] #1667
- [x] #1633 
- [x] #941 
- [x] #752 
- [x] #534 (relates to #1621)
- [x] (optional) #545

**Comment by theetrain** [comment]
@SimpleProgrammingAU I captured as many outcomes as I could above. Thank you for contributing!

**Comment by SimpleProgrammingAU** [comment]
@theetrain do you wanna add `PasswordInput` to this issue?

**Comment by theetrain** [comment]
@SimpleProgrammingAU I think `PasswordInput` can be handled separately since it doesn't share co-dependencies with `TextInput`; this way PRs can be kept small.

**Comment by theetrain** [comment]
This was released in [v1.0.0-next.1](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v1.0.0-next.1).
