### ISSUE TITLE
Use `Button` component instead of native `button` in `HeaderGlobalAction`

### ISSUE THREAD

**Issue by spburtsev** [carbon-design-system/carbon-components-svelte#1893]
Currently, adding tooltips to the HeaderGlobalAction component is a bit cumbersome due to its reliance on the native button element. To improve this functionality, I propose using the Button component instead, as it natively supports tooltips and aligns with the approach taken in @carbon/react.

**Comment by metonym** [comment]
Released in [v0.84.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.84.0).

[Example](https://svelte.carbondesignsystem.com/components/UIShell#header-with-utilities) in docs.

As simple as adding an `iconDescription` to complement the icon.

```svelte
<HeaderGlobalAction
  iconDescription="Settings"
  icon={SettingsAdjust}
/>

```

Adjust the tooltip alignment using the `tooltipAlignment` prop. Default value is `"center"`. Other values can be `"start"` or `"end"`.

```svelte
<HeaderGlobalAction
  iconDescription="Settings"
  icon={SettingsAdjust}
  tooltipAlignment="start"
/>

```
