### ISSUE TITLE
ContextMenu prevents context menu invocations outside of the target

### ISSUE THREAD

**Issue by gtm-nayan** [carbon-design-system/carbon-components-svelte#1909]
The use of preventDefault on this line https://github.com/carbon-design-system/carbon-components-svelte/blob/65904575743ba06344fb75e14685e42494c13cde/src/ContextMenu/ContextMenu.svelte#L141

applies to contextmenu events anywhere on the page, so even if you right click somewhere on the page that's not inside the target, it'll prevent the browser's context menu from opening

**Comment by metonym** [comment]
This is a major bug, thanks for reporting.

**Comment by metonym** [comment]
Fixed in [v0.82.9](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.82.9)
