### ISSUE TITLE
Link: do not render `<p>`

### ISSUE THREAD

**Issue by theetrain** [carbon-design-system/carbon-components-svelte#1924]
Original report: https://github.com/carbon-design-system/carbon-components-svelte/discussions/1908#discussioncomment-8698373

## Issue

Svelte 5 yields a compiler error for `<Link>` because `<div>` is an invalid descendent of `<p>`, which is correct as per W3 spec.

I recommend we align behaviour with [Carbon React](https://react.carbondesignsystem.com/?path=/story/components-link--playground&args=disabled:!true):

- [ ] When disabled, render an `<a aria-disabled="true">` (⚠️ breaking change since `<p>` has different layout behaviour)

Reference:

https://github.com/carbon-design-system/carbon-components-svelte/blob/96aef1705cc2812d47a8015a1499a6c6021ced0f/src/Link/Link.svelte#L37-L60

## Reproduction

Demo: https://stackblitz.com/edit/sveltejs-kit-template-default-mxnwjf?file=src%2Froutes%2F%2Bpage.svelte

Screenshot:

<img width="828" alt="image" src="https://github.com/carbon-design-system/carbon-components-svelte/assets/12798751/419d866f-df10-4693-bd05-4d8a1101a9b8">

**Comment by metonym** [comment]
Yes, I think it makes sense to fix this for <v1 if it's blocking Svelte 5 usage.
