### ISSUE TITLE
DataTable sort function return type is restricted to -1, 0 or 1

### ISSUE THREAD

**Issue by berndfuhrmann** [carbon-design-system/carbon-components-svelte#1934]
The expected return type for sorting rows in a DataTable is currently:
https://github.com/carbon-design-system/carbon-components-svelte/blob/21b1d78d8ebda608d78c1ab22833c36138f9ef3c/types/DataTable/DataTable.svelte.d.ts#L12

This restriction isn't used in DataTable.svelte and it wouldn't be a problem to use `number` as return type instead.

Doing so would give consumers of this library an easier way to write comparison functions, for example when sorting by Date: You could then write something like: `(a:Date, b:Date) => a.getTime() - b.getTime()` instead of having to write `Math.max(Math.min(a.getTime()-b.getTime(), 1), -1)`. This would also improve performance slightly.

**Comment by metonym** [comment]
Agreed – the return type should be a primitive, not an enum.

**Comment by metonym** [comment]
Fixed in [v0.84.1](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.84.1)
