### ISSUE TITLE
[Svelte 5] `MultiSelect` triggers `effect_update_depth_exceeded` error

### ISSUE THREAD

**Issue by malinowskip** [carbon-design-system/carbon-components-svelte#1986]
An `effect_update_depth_exceeded` error is printed to the console when a MultiSelect component is present on the page. I have tested it in `svelte@5.0.0-next.197`, but also checked some earlier versions.

## Console output
```
Uncaught (in promise) Svelte error: effect_update_depth_exceeded
Maximum update depth exceeded. This can happen when a reactive block or effect repeatedly sets a new value. Svelte limits the number of nested updates to prevent infinite loops
    effect_update_depth_exceeded errors.js:171
    infinite_loop_guard runtime.js:477
    flush_sync runtime.js:681
    flush_sync runtime.js:698
    flush_sync runtime.js:698
    flush_sync runtime.js:698
    flush_sync runtime.js:698
    flush_sync runtime.js:698
    flush_sync runtime.js:698
    flush_sync runtime.js:698
errors.js:171:16
```

## Reproduction
https://github.com/malinowskip/carbon-multiselect-svelte-5-error

**Comment by malinowskip** [comment]
Apparently, the problem lies with the `afterUpdate` hook.

After the initial page load, the following block runs 500 times before erroring out:
https://github.com/carbon-design-system/carbon-components-svelte/blob/ba27830b2f6ad1fb2c8cc7dc1a8c833cf9e236d0/src/MultiSelect/MultiSelect.svelte#L252-L255

The same goes for this assignment:
https://github.com/carbon-design-system/carbon-components-svelte/blob/ba27830b2f6ad1fb2c8cc7dc1a8c833cf9e236d0/src/MultiSelect/MultiSelect.svelte#L261

**Comment by wbhob** [comment]
Seeing the same problem with ToolbarMenu example from DataTable on svelte 5-next.216.

https://svelte.carbondesignsystem.com/components/DataTable#with-toolbar

**Comment by Sheepux** [comment]
> Seeing the same problem with ToolbarMenu example from DataTable on svelte 5-next.216.

Yep i can confirm, i get the same thing with Datatable pagination (if I remove this part of the component it works fine)
