### ISSUE TITLE
[Svelte 5] `children` prop is reserved

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon-components-svelte#2013]
One of the Svelte 5 breaking changes is that the [`children` prop is reserved](https://svelte-5-preview.vercel.app/docs/breaking-changes#the-children-prop-is-reserved).

As such, components like `TreeView` and `RecursiveList` (which have `children` props) are affected.

From what I've observed:

- `TreeView` with Svelte 5 can render the tree, but toggling nodes does nothing (silently breaking).
- `RecursiveList` with Svelte 5 seems to render fine. Regardless, the prop should be renamed if Svelte 5 considers it reserved.

The fix would be to rename the `children` prop. This is a breaking change that is relatively easy to adapt to, and unblocks Svelte 5 usage.

**Comment by Sheepux** [comment]
Combobox also has the issue 
`{#snippet children({ item })}`
It will not allow item as parameter

**Comment by brunnerh** [comment]
That [should not be an issue](https://svelte.dev/playground/untitled?version=5.1.9#H4sIAAAAAAAACnWQwU7DMBBEf2W1RWoqWY2AWxoicePAH9Q9hGSrWnJsy15KUeR_R7ZcIILe7PXMrN_MaPqJsMEX0trCh_V6hIpGxTRuUOBRaQrY7GfkT5d0aYDi6np2bhvOpDnN3vpA_80Ha5gMB2ywDYNXjjtpJKvJWc_wqgLD0dsJ1ts6XYpxvZMmyQZrAoNimgI8wV3gnqna3wt4EPB42OykaeufVNPmvDnrY94zr4JRzhHDcFJ69GSqOedB3MQkkNyO6txlT2zrdM6-uvhiWpFiO2lQINOFsWH_TlHcqOUXxrKX5cONYuiSi9FUsP8gfv9wRf1wKt30IR-uREHbUkOEuvAkdYZJAUuSQ_wCIj8DTQoCAAA=).
Did you get type errors?

**Comment by Sheepux** [comment]
Yeah, as it was complaining about Snippet and item I thought it was the same issue.

> Type '{ id: string; placeholder: string; selectedId: string; size: "sm"; items: ComboBoxItem[]; shouldFilterItem: (item: any, value: string) => any; children: ({ item }: { item: any; }) => any; }' is not assignable to type 'Properties<ComboBoxProps, { default: { item: ComboBoxItem; index: number; }; titleText: {}; }>'.
>   Type '{ id: string; placeholder: string; selectedId: string; size: "sm"; items: ComboBoxItem[]; shouldFilterItem: (item: any, value: string) => any; children: ({ item }: { item: any; }) => any; }' is not assignable to type 'ComboBoxProps'.
>     Types of property 'children' are incompatible.
>       Type '({ item }: { item: any; }) => any' is not assignable to type 'Snippet<[]>'.
>         Target signature provides too few arguments. Expected 1 or more, but got 0.ts(2322)

Or did i take the wrong type in my previous code ??

```typescript
<script lang="ts">
    import {
        ComboBox,,
    } from 'carbon-components-svelte';

    import type {
        ComboBoxItem,
        ComboBoxItemId,
    } from 'carbon-components-svelte/src/ComboBox/ComboBox.svelte';

    let test: ComboBoxItem[] = [];
</script>
        <ComboBox
            items={test}
        >
            {#snippet children({ item })}
           {/snippet}
        </ComboBox> 
```
I'll look into it further and check with a new project

**Comment by metonym** [comment]
The change you'll need to make is to rename `children` to `nodes` in the `TreeView` and `RecursiveList` components:

```diff
<TreeView
- children={[
+ nodes={[
    {
      nodes: [
        {
          id: 2,
          text: "IBM Analytics Engine",
-         children: [
+         nodes: [
            { id: 3, text: "Apache Spark" },
            { id: 4, text: "Hadoop" },
          ],
        },
      ],
    },
  ]}
/>


<RecursiveList
- children={[
+ nodes={[
    {
      nodes: [
        {
          text: "IBM Analytics Engine",
-         children: [
+         nodes: [
            { text: "Apache Spark" },
            { text: "Hadoop" },
          ],
        },
      ],
    },
  ]}
/>
```
