### ISSUE TITLE
[Svelte 5] `Checkbox` indeterminate state not updating

### ISSUE THREAD

**Issue by malinowskip** [carbon-design-system/carbon-components-svelte#2039]
In Svelte 5, the following example from the docs doesn’t work: https://svelte.carbondesignsystem.com/components/Checkbox#indeterminate.

```svelte
<Checkbox labelText="Label text" indeterminate />
```

The initial indeterminate icon is frozen regardless of the current `checked` value.

While looking into this, I also discovered that `indeterminate` can’t be set as a HTML attribute, but should be set dynamically in JavaScript (source: [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate_state_checkboxes)).

The problem could be fixed by removing the `indeterminate` HTML attribute and setting the value dynamically:

```js
onMount(() => {
  if (ref && indeterminate) {
    ref.indeterminate = true;
  }
});
```

**Comment by metonym** [comment]
Fixed in [v0.86.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.86.0)
