### ISSUE TITLE
MultiSelect: `top-after-reopen` setting for `selectionFeedback` not being respected

### ISSUE THREAD

**Issue by malinowskip** [carbon-design-system/carbon-components-svelte#2066]
The `top-after-reopen` setting for `selectionFeedback` (default) is currently not being respected. With this setting enabled, selected items should jump to the top after the dropdown is re-opened.

## Reproduction
https://github.com/malinowskip/carbon-multiselect-selection-feedback-error

## Possible solution

Perhaps this could be fixed by including another condition on the following line:
https://github.com/carbon-design-system/carbon-components-svelte/blob/e2342aa249398e4d1e196a48f3fdcfc931370a92/src/MultiSelect/MultiSelect.svelte#L250

For example (assuming that items can be sorted as soon as the dropdown is closed):

```js
if (
  selectedIds.length > 0 &&
  (selectionFeedback === "top" || (selectionFeedback === "top-after-reopen" && !open))
) {
  // sorting logic
}
```

**Comment by metonym** [comment]
Fixed in [v0.86.2](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.86.2)
