### ISSUE TITLE
NumberInput and floating point values

### ISSUE THREAD

**Issue by cdellacqua** [carbon-design-system/carbon-components-svelte#233]
I was trying to use the NumberInput component and I found out that using the up&down buttons instead of the arrow keys on my keyboard (thus triggering the custom function that changes the value) causes the classic approximation problem of the floating point binary representation.

For example, setting the step at 0.01 (which cannot be expressed correctly in base 2) and starting from 0 gives the following sequence of values displayed in the input field:
0.01, 0.02, 0.03, 0.04, 0.05, 0.060000000000000005, 0.07, 0.08, 0.09, 0.09999999999999999, ..., and so on.

Possible solutions:
- use a library that handles these problems
or
- replace the following code (in NumberInput.svelte, line 149, function updateValue):
```
const nextValue = (value += direction * step);
```
with
```
const stepDecimalPlaces = step % 1 === 0 ? 0 : step.toString().split('.')[1].length;
const nextValue = stepDecimalPlaces === 0
    ? value + step * direction
    : Math.round(value * Math.pow(10, stepDecimalPlaces) + step * Math.pow(10, stepDecimalPlaces) * direction) / Math.pow(10, stepDecimalPlaces);
```

**Comment by metonym** [comment]
Thanks for opening an issue.

However, as you state, this floating point behavior is inherent to JS and not a component-specific bug.

This issue has been raised multiple times in the flagship Carbon monorepo (https://github.com/carbon-design-system/carbon/issues/1313, https://github.com/carbon-design-system/carbon/issues/5249). If you [open this issue in the monorepo](https://github.com/carbon-design-system/carbon), we can probably get a bigger discussion going by involving the Carbon team.

**Comment by cdellacqua** [comment]
Hi, thanks for your time.

While it's true that "this floating point behavior is inherent to JS", it's also true that the native `<input type="number">` is not affected, because browsers implement the arithmetic to take into account the inaccuracy of the binary representation. This is why I consider this implementation of the NumberInput buggy. Moreover using the arrow keys (thus triggering the default browser-implemented behavior) yields the correct results as stated in the previous comment, so its behavior is not even consistent on different input methods.

I've also tried to use the VanillaJS implementation, but it also yields the wrong values. The source code of the update function is almost identical.

As suggested I opened an issue in the monorepo: https://github.com/carbon-design-system/carbon/issues/6684

**Comment by NoelJacob** [comment]
Any temporary solution as of now?

**Comment by metonym** [comment]
Floating point step values are supported in [v0.70.13](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.70.13).

[Example](https://carbon-components-svelte.onrender.com/components/NumberInput#with-step-value)
