### ISSUE TITLE
CSS does not work with rollup-typescript example

### ISSUE THREAD

**Issue by DanielPower** [carbon-design-system/carbon-components-svelte#283]
Steps to reproduce:
1. Download the `rollup-typescript` example
2. `yarn`
3. `yarn run dev`

Open in a browser. 
![image](https://user-images.githubusercontent.com/12166320/94204596-1b06b880-fe9c-11ea-8bd5-bd1234bceff1.png)

I was initially struggling to get the styling to work in my own project, and eventually decided to check out the example, to get a better understanding. But unfortunately, the styles don't work in the example.

And advice would be greatly appreciated. This is a great ui library, and I appreciate your time working on it.

Edit: Just tested, and the webpack example is working.

**Comment by metonym** [comment]
@DanielPower Thank you for raising this issue. I'm sorry about the experience.

For both the rollup/rollup-typescript examples, the `all.css` stylesheet is somehow corrupted when being bundled.

Could you try this workaround?

Add `postcss` as a development dependency: `yarn add -D postcss`

Then, modify the following in rollup.config.js:

```diff
svelte({
      dev: !production,
-      preprocess: sveltePreprocess(),
+      preprocess: sveltePreprocess({
+       sourceMap: !production,
+        postcss: {},
+      }),
      css: (css) => {
        css.write("bundle.css");
      },
    }),
```

**Comment by weaseldotro** [comment]
Same problem here, I tried your fix and it doesn't work.

**Comment by benjibuiltit** [comment]
I was running into this same issue and quite frustrated. I was able to get things working by running
`npm i -D postcss autoprefixer` and using this config:
```
preprocess: sveltePreprocess({
    defaults: {
        script: 'typescript',
        style: 'scss'
    },
    postcss: true,
    scss: {
        includePaths: ["src"],
        postcss: {
            plugins: [require("autoprefixer")],
        },
    },
})
```
