### ISSUE TITLE
Tile component.

### ISSUE THREAD

**Issue by ispyinternet** [carbon-design-system/carbon-components-svelte#403]
Probably a question for upstream, but what's happening with the Tile component?

For example scroll down the page a bit at the demo usage: https://www.carbondesignsystem.com/components/tile/usage and we see examples with media, title, description, icons, selectable, call to action, but the actual component has zero support for any of these items via props or slots.

Also it could be argued that radioTile and selectableTile should be configurable options of a greater Tile component?

Personally I think material have a good model for this type of component: https://material.io/components/cards#anatomy

**Comment by metonym** [comment]
> Also it could be argued that radioTile and selectableTile should be configurable options of a greater Tile component?

There's little overlap in business logic between RadioTile and SelectableTile. It's better to keep them separate than as variants of the read only Tile.

As a consumer, if I just want to use Tile, I don't want to have to include logic from RadioTile, SelectableTile, and TileGroup (which RadioTile depends on) in my app.

**Comment by metonym** [comment]
> For example scroll down the page a bit at the demo usage: https://www.carbondesignsystem.com/components/tile/usage and we see examples with media, title, description, icons, selectable, call to action, but the actual component has zero support for any of these items via props or slots.

It would be nice to support a Card component. I wonder how much could be achieved by composing existing components?

```svelte
<Tile>
  <AspectRatio ratio="16x9" style="margin: -1rem">
     <img src="" alt="" />
  </AspectRatio>
  <div>description</div>
  <Link href="#">Call to action</Link>
</Tile>
```

**Comment by ispyinternet** [comment]
> > Also it could be argued that radioTile and selectableTile should be configurable options of a greater Tile component?
> 
> There's little overlap in business logic between RadioTile and SelectableTile. It's better to keep them separate than as variants of the read only Tile.
> 
> As a consumer, if I just want to use Tile, I don't want to have to include logic from RadioTile, SelectableTile, and TileGroup (which RadioTile depends on) in my app.

Yh, I suppose the radio has to be wrapped, also perhaps I'm conflating the docs with the internal designs. For example, RadioTile, SelectableTile are scattered in the docs hierarchy. Whereas for example DataTable, or ComposedModal, once you land on theses items, you discover the component parts - and Tiles being Tiles and all that, just with different modus operandi.

Anyway - the Card component - are you suggesting that this is left to userland, or you would create such a component in the library?

I would really like to be able to contribute - but not sure if that would be possible or indeed desirable.

Adding a new component seems like a big deal in such a tightly managed domain. Would the design / spec need to start upstream?

**Comment by metonym** [comment]
Yes, start upstream. See if there's anything in the works – but it shouldn't stop a user from building their own.
