### ISSUE TITLE
DataTable overflow menu with toolbar z-index issue

### ISSUE THREAD

**Issue by ispyinternet** [carbon-design-system/carbon-components-svelte#426]
The overflow menu of the toolbar and the datatable cell are competing:

![Capture](https://user-images.githubusercontent.com/1741823/100462614-6b7bdb80-30c2-11eb-8c8f-aefd33594bca.PNG)

**Comment by ispyinternet** [comment]
This one is resolvd by adding `z-index:1` to `bx--table-toolbar` should I action?

**Comment by metonym** [comment]
Yes, feel free to submit a PR

**Comment by metonym** [comment]
Fixed in [v0.63.8](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.63.8) by #1289.
