### ISSUE TITLE
ButtonSet not spanning whole buttons' width

### ISSUE THREAD

**Issue by tomadimitrie** [carbon-design-system/carbon-components-svelte#445]
![Screen Shot 2020-12-05 at 03 02 31](https://user-images.githubusercontent.com/34240434/101228906-5eed1980-36a6-11eb-9f6b-0971b1cfe3c6.png)

As you can see, ButtonSet only has the width equal to the first button.

(Using Sapper, if that matters)

Code:

```svelte
<script lang="ts">
  import { Button, ButtonSet } from "carbon-components-svelte";

  const items = [
    {
      name: "A",
      href: "A",
    },
    {
      name: "b",
      href: "b",
    },
  ];
</script>

<nav>
  <ButtonSet id="buttons">
    {#each items as item (item.name)}
      <Button href={item.href}>{item.name}</Button>
    {/each}
  </ButtonSet>
</nav>

<style lang="scss">
  nav {
    display: flex;
  }
  #buttons {
    margin-left: auto;
  }
</style>
```

**Comment by metonym** [comment]
For design questions, I'd recommend opening an issue in the [flagship Carbon repository](https://github.com/carbon-design-system/carbon/issues).

**Comment by theetrain** [comment]
To my understanding, the widths of buttons should be equal when they're part of a group. Buttons containing text labels have a minimum width as well:

![image](https://user-images.githubusercontent.com/12798751/211919754-5d12cc34-7bc3-48cd-bc76-c1e68066e870.png)

Reference: https://carbondesignsystem.com/components/button/usage/#button-groups

If core designs have changed, or if carbon-components-svelte has not implemented the designs correctly, we can reopen this issue.
