### ISSUE TITLE
Modal and Toast Notification position

### ISSUE THREAD

**Issue by auliabismar** [carbon-design-system/carbon-components-svelte#469]
In a long page, a Modal or Toast Notification created in the top page, not the y pixel scrolled window.

I use combination of `<svelte:window bind:scrollY={topY} />` and `<div style="top:{topY}px; position:absolute">` for workaround. Is there a more elegant way for this?

**Comment by metonym** [comment]
Essentially, the modal/notification should not be the child of a relative positioned element.

I'd recommend rendering the modal/toast notification in a node that is as close to the top of the DOM as possible.

For example, say you have `App.svelte` that is the "root" of your app:

```svelte

<main>
  <Routes>
    ...
  </Routes>
</main>

{#if $showModal}
  <Modal />
{/if}

{#if $showNotifications}
  <div style="fixed">
    {#each $notifications as notification}<ToastNotification {...notification} />{/each}
  </div>
{/if}
```

**Comment by benjamin-kirkbride** [comment]
For posterity, I found the following to be very useful:

https://dev.to/danawoodman/svelte-quick-tip-creating-a-toast-notification-system-ge3

https://svelte.dev/repl/0091c8b604b74ed88bb7b6d174504f50?version=3.35.0
