### ISSUE TITLE
Href link doesn't work when clicking on tabs.

### ISSUE THREAD

**Issue by mateuszlewko** [carbon-design-system/carbon-components-svelte#473]
Consider a simple set of tabs with `href` property specified:
```
<Tabs>
  <Tab label="Tab label 1" href="/a" />
  <Tab label="Tab label 2" href="/b" />
</Tabs>
```

`href` property is propagated to `<a>` element in the `Tab` component. However, clicking on any tab doesn't navigate to a given url. 
This is caused by using `preventDefault` option for `on:click` handler in `<li>` element in `Tab.svelte` (around line 42). 

Removing  `preventDefault` from `on:click` handler fixes this issue. Was there any reason in the first place why that option was used?

Thanks.

**Comment by miedzikd** [comment]
Any update?

**Comment by metonym** [comment]
As a workaround, are you able to manually trigger a route change when clicking a tab?

FWIW, the Tab [`href` prop is deprecated upstream](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Tab/Tab.js#L44).

**Comment by miedzikd** [comment]
ah... I didn't know that option was deprecated... yes I just add on:click to route change... 
thanks for explanaition

**Comment by cupcakearmy** [comment]
@metonym Is there a way to stop the href from pushing to the history? I tried on:click and stoping propagation does not let the tab change at all and preventDefault does not stop the tab component from changing the history. I use the tab for within a page that does not change the url and currently there is no way to prevent that

**Comment by metonym** [comment]
@cupcakearmy The bug where mobile tab links push to history has been fixed in https://github.com/carbon-design-system/carbon-components-svelte/pull/946 (v0.50.3)
