### ISSUE TITLE
How to ensure Modal z-index is correct

### ISSUE THREAD

**Issue by ispyinternet** [carbon-design-system/carbon-components-svelte#526]
Perhaps not even a z-index issue, more component layout question, but how do you advise, for example, if you structure your component hierarchy, and a child has some logic to open a modal - and lets assume the modal is strongly tied to the component so you naturally include the modal code within - then I am having an issue that the modal is partially obscured by the SideNav.

I can't imagine that the modal _must_ be placed at top level and some form of event / prop or store communication to open it!?

<img width="401" alt="Screenshot 2021-02-18 at 14 28 31" src="https://user-images.githubusercontent.com/1741823/108370737-e271cd80-71f4-11eb-862f-adfc0a214c93.png">

**Comment by metonym** [comment]
Yes, the modal should be placed as high as possible in the DOM to ensure that it's not wrapped by an element with a low z-index.

**Comment by ispyinternet** [comment]
so if you want a deeply nested child component to show a modal the options are to chain `on:message` throughout your component tree or share a store? Or can you recommend a better pattern?

**Comment by metonym** [comment]
Yes
