### ISSUE TITLE
OverflowMenu iconDescription not optimal

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#536]
1. It only triggers in the middle section where the icon is, not on the padding
2. It uses the browser's basic "title" attribute, which is slow to show and different from the way other icon-only buttons look.

```svelte
<OverflowMenu icon={Menu20} iconDescription="Menu"/>
<Button icon={Menu20} iconDescription="Menu" kind="ghost"/>
```

![image](https://user-images.githubusercontent.com/834235/109064919-457acd00-76eb-11eb-926b-e219fe6bb694.png)
![image](https://user-images.githubusercontent.com/834235/109064891-3c89fb80-76eb-11eb-9e50-7eb2601fc353.png)

**Comment by metonym** [comment]
This is a question for the [flagship repo](https://github.com/carbon-design-system/carbon)
