### ISSUE TITLE
Make DataTable selectAll reactive

### ISSUE THREAD

**Issue by Yahatix** [carbon-design-system/carbon-components-svelte#592]
Currently the header checkbox doesn't turn checked after manually selecting all rows

https://github.com/IBM/carbon-components-svelte/blob/bd846dc453a5d03db104a0bb74f7914d7de00ffd/src/DataTable/DataTable.svelte#L150

This could easily be made reactive like so
```js
$: selectAll = rows.length === selectedRowIds.length
```

**Comment by metonym** [comment]
Related #1083

Fixed in [v0.58.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.58.0)
