### ISSUE TITLE
Checkbox click event gets triggered twice

### ISSUE THREAD

**Issue by Yahatix** [carbon-design-system/carbon-components-svelte#593]
# Example
```svelte
<Checkbox on:click={()=> console.count()}/>
```

# Issue
The click event gets triggered twice

# Solution
The on:click should be on the input element and not on the div

https://github.com/IBM/carbon-components-svelte/blob/bd846dc453a5d03db104a0bb74f7914d7de00ffd/src/Checkbox/Checkbox.svelte#L59-L63
https://github.com/IBM/carbon-components-svelte/blob/bd846dc453a5d03db104a0bb74f7914d7de00ffd/src/Checkbox/Checkbox.svelte#L51-L53

**Comment by metonym** [comment]
After looking into this further, I don't think the current behavior should be changed.

- the canonical React implementation uses `onChange`
- moving the forwarded `on:click` event would make it inconsistent with other forwarded events

Use the `on:change` event instead:

```svelte
<Checkbox on:change={() => console.count()} />
```
