### ISSUE TITLE
Checkbox Bind Group

### ISSUE THREAD

**Issue by alexstaroselsky** [carbon-design-system/carbon-components-svelte#612]
Thank you for creating this awesome library for Svelte.

I had a question regarding the `Checkbox` component. Is there any variation of the checkbox or similar checkbox like component that supports [bind:group](https://svelte.dev/docs#bind_group)? It looks like `value` is not exposed by `Checkbox`. Or is it intended to use [SelectableTile](https://carbon-svelte.vercel.app/components/SelectableTile) for that type of functionality?

Thanks!

**Comment by metonym** [comment]
Great suggestion – we should leverage Svelte APIs wherever possible.

**Comment by metonym** [comment]
Checkbox now supports `bind:group` in [v0.51.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.51.0) using a custom implementation by @gregorw 

[Example](https://carbon-components-svelte.onrender.com/components/Checkbox#multiple)
