### ISSUE TITLE
ContextMenu can only be used on the whole page

### ISSUE THREAD

**Issue by NyxCode** [carbon-design-system/carbon-components-svelte#620]
Currently, `ContextMenu` can only be used on the whole page.
Sadly, this is pretty limiting - I'd like to use it only on an element on my page.

Could `ContextMenu` be split into a dumb sub-component which doesn't listen for events itself?
I would like to just give it `x`, `y` as props and handle everything else myself.

**Comment by metonym** [comment]
I agree that there should be an option to use it on an arbitrary element.

I think that adding a `target` prop (`HTMLElement`) to `ContextMenu` would be a good approach. The default would still be the `window`.

**Comment by NyxCode** [comment]
I guess that would work for most cases, but I'm not sure that would be flexible enough.
At least for my usecase, I need to have a context menu for a *lot* of elements, and I wouldn't want a seperate `ContextMenu` for every one of them.

I think this would be a sane change for `ContextMenu`, but I still believe that something like `ContextMenuInner` (#622) would be great for more compilcated usecases.

**Comment by geoidesic** [comment]
Should just be called `Menu` if it can only be used on the whole page. The whole point of adding the world "Context" before menu is, well.. for a menu that differs by context. Boggles the mind :)

**Comment by Trystan-SA** [comment]
I also don't understand why ContextMenu is indeed not contextualized based on what item you right-click. Please at least populate the passed on:open forwarded event with a reference to the DOM element we have the cursor over.

 ```js
<ContextMenu on:open={(...e)=>{console.log(e); }}>
	<ContextMenuOption indented labelText="Copy"/>
	<ContextMenuOption indented kind="danger" labelText="Delete" />
</ContextMenu>
```

is currently returning this : 
![Capture d’écran 2021-11-17 194339](https://user-images.githubusercontent.com/43876044/142262693-f4be0310-64a9-4522-affb-78e7711af76a.png)

**Comment by metonym** [comment]
In [version 0.50](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.50.0), you can now pass custom elements as trigger targets to `ContextMenu`

Example: https://carbon-components-svelte.onrender.com/components/ContextMenu#custom-target

@Trystan-SA The `event.target` is passed to the `on:open` event detail as well.

```svelte
<ContextMenu on:open={(e) => {
  console.log(e.detail); // HTMLElement
}}>
  ...
</ContextMenu>
```

**Comment by geoidesic** [comment]
Does this mean that this PR is no longer needed? https://github.com/carbon-design-system/carbon-components-svelte/pull/622
