### ISSUE TITLE
css docs website vs local import discreps

### ISSUE THREAD

**Issue by xSCIven** [carbon-design-system/carbon-components-svelte#628]
On importing the UI shell the class .bx--content has the wrong colour when comparing to the docs website.

The css with this class was generated from the latest version of carbon components css.

**Comment by metonym** [comment]
Could you provide some more detail?

**Comment by xSCIven** [comment]
The steps required are:

Generate g100.css from g100.scss, Import the UI shell to a svelte project, compare with your carbon-components-svelte/docs website ui shell example.

**Comment by metonym** [comment]
The `Content` dark themes have a background color applied; the documentation site resets this color:

```css
main.bx--content {
  background: none;
}
```

**Comment by xSCIven** [comment]
This could be a bit misguiding for someone using carbon svelte for a first time as the docs website is the main reference for importing and using components.
