### ISSUE TITLE
DataTable > ToolbarMenuItem > Index issue

### ISSUE THREAD

**Issue by Smilefounder** [carbon-design-system/carbon-components-svelte#652]
Kindly see attached video for he more detail
https://user-images.githubusercontent.com/3785721/119255469-35896100-bbe6-11eb-8282-33a243c93674.mp4

**Comment by metonym** [comment]
Fixed in [v0.63.8](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.63.8)
