### ISSUE TITLE
Snowpack Typescript Example

### ISSUE THREAD

**Issue by davidpodhola** [carbon-design-system/carbon-components-svelte#661]
First of all, thank you very much for making it possible to use Carbon Components in Svelte! With the micro-frontends, I feel like having a framework that can be used from Svelte, React, Vue and Angular is simply awesome!

I have seen there are several samples available (which is great!), but it seems [Snowpack](https://www.snowpack.dev/) is missing. I know it is relatively new and [SvelteKit is actually using Vite](https://vitejs.dev/), but there are still single-page applications being developed and Carbon Components with Snowpack would make the developer experience simply great.

Does it make sense? Is this something I can create a PR for? Thanks!

![carbon snowpack](https://user-images.githubusercontent.com/436605/119884788-524cce00-bf31-11eb-8858-7820e5d1d0e3.gif)

**Comment by davidpodhola** [comment]
If anyone is interested or search for the keywords, the example is here https://github.com/iDempiere-micro/carbon-components-svelte/tree/master/examples/snowpack-typescript

**Comment by metonym** [comment]
Closing as [Snowpack](https://github.com/FredKSchott/snowpack) is no longer maintained.
