### ISSUE TITLE
DataTable ToolbarMenu layout bug in Firefox with ToolbarBatchActions

### ISSUE THREAD

**Issue by n-peugnet** [carbon-design-system/carbon-components-svelte#668]
### Description

Using Firefox (tested with 88.0.1 Desktop and 89.0.0-beta.10 Android), in "add-on disabled" mode, the toolbar moves to a strange position once the `ToolbarMenu` has been opened and after a page refresh. It goes back to it's original position when the menu is opened again, but it moves on each refresh.
The only way to make it come back to its original position is to make a force refresh (<kbd>Ctrl</kbd> + <kbd>F5</kbd>).

This happens only when the `ToolbarMenu` is used in conjunction with the `ToolbarBatchActions`. 

This bug does not happen with Chromium

### Step to reproduce

1.  clone & build demo repo then open firefox:
    ```bash
    git clone https://github.com/n-peugnet/data-table-bug
    cd data-table-bug
    yarn
    yarn dev &
    firefox localhost:3000
    ```
2. open the toolbar menu
3. refresh the page

### Demo

![Peek 2021-06-04 16-05](https://user-images.githubusercontent.com/23519418/120814965-aec27580-c54f-11eb-901d-d469d8b823ed.gif)

### Example

Here is the minimal template that triggers this issue:

```svelte
<script>
  import {
    DataTable,
    Toolbar,
    ToolbarBatchActions,
    ToolbarContent,
    ToolbarSearch,
    ToolbarMenu,
    ToolbarMenuItem,
    Button,
  } from "carbon-components-svelte";
</script>

<DataTable
  batchSelection
  title="Load balancers"
  description="Your organization's active load balancers."
  headers={[{ key: 'name', value: 'Name' }, { key: 'protocol', value: 'Protocol' }, { key: 'port', value: 'Port' }, { key: 'rule', value: 'Rule' }]}
  rows={[{ id: 'a', name: 'Load Balancer 3', protocol: 'HTTP', port: 3000, rule: 'Round robin' }, { id: 'b', name: 'Load Balancer 1', protocol: 'HTTP', port: 443, rule: 'Round robin' }, { id: 'c', name: 'Load Balancer 2', protocol: 'HTTP', port: 80, rule: 'DNS delegation' }, { id: 'd', name: 'Load Balancer 6', protocol: 'HTTP', port: 3000, rule: 'Round robin' }, { id: 'e', name: 'Load Balancer 4', protocol: 'HTTP', port: 443, rule: 'Round robin' }, { id: 'f', name: 'Load Balancer 5', protocol: 'HTTP', port: 80, rule: 'DNS delegation' }]}
>
  <Toolbar>
    <ToolbarBatchActions>
    </ToolbarBatchActions>
    <ToolbarContent>
      <ToolbarMenu>
        <ToolbarMenuItem>Restart all</ToolbarMenuItem>
      </ToolbarMenu>
    </ToolbarContent>
  </Toolbar>
</DataTable>
```

I could not reproduce this bug using vanilla js examples from [carbon demo website](https://the-carbon-components.netlify.app/?nav=data-table). Here is a minimal html file that I made to try reproducing it:

https://gist.github.com/n-peugnet/cf6b3ac91b640c1a91081e23a3b0712d ([resulted page](https://gist.githack.com/n-peugnet/cf6b3ac91b640c1a91081e23a3b0712d/raw/de6a2ac4048af41d1b88b4484ee14c9147331500/datable.html))

**Comment by n-peugnet** [comment]
For now I fixed this by adding the following rule in my `global.css`:

```css
section.bx--table-toolbar {
	overflow: clip;
}
```

**Comment by metonym** [comment]
Apologies for the belated reply – thank you for the detailed repro instructions. I've tried your code in Firefox 100 but am unable to create the bug. Since this isn't reproducible in Chrome, I wonder if it was a Firefox-specific bug that has since been fixed?

**Comment by n-peugnet** [comment]
I just tested it on Firefox 100 too and it does not occur any more. I guess it was indeed a Firefox bug. Thank you for taking the time to reproduce it.
