### ISSUE TITLE
ToolbarSearch does not expand automatically when value is set programmatically

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#673]
When binding the value and updating the bound variable the search box does not expand, instead the search and clear icons will overlap.

```svelte
<!-- Change searchText somewhere in code -->
<ToolbarSearch bind:value={searchText}/>
```

![image](https://user-images.githubusercontent.com/834235/121039138-204d2e80-c7b1-11eb-9fbf-9d92c4ae0dca.png)

---

Workaround: Bind `expanded` and set bound value to `true` when changing the search text.

```svelte
<ToolbarSearch bind:value={searchText} bind:expanded={searchExpanded}/>
```

**Comment by metonym** [comment]
Fixed in [v0.50.5](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.50.5)
