### ISSUE TITLE
How to control slider visual width?

### ISSUE THREAD

**Issue by geoidesic** [carbon-design-system/carbon-components-svelte#700]
Currently they are misaligned. How do I control this?
<img width="413" alt="Screenshot 2021-06-27 at 11 33 15" src="https://user-images.githubusercontent.com/4637995/123541256-77ed1300-d73b-11eb-9a73-62e55033011a.png">

I want them both to take the same amount of horizontal space.. the one below is dangling through the padding of the parent element.

**Comment by metonym** [comment]
A `fullWidth` prop was added to `Slider` in #1354 in v0.66.0.

Docs: https://carbon-components-svelte.onrender.com/components/Slider#full-width

Svelte REPL: https://svelte.dev/repl/d7d90415cff54004b2cb7154a17f43f8?version=3.49.0
