### ISSUE TITLE
Naming and structure suggestions

### ISSUE THREAD

**Issue by ricardo-valero** [carbon-design-system/carbon-components-svelte#709]
I was reading this https://github.com/IBM/carbon-components-svelte/issues/344, and thought I could help in a different way, I leave in italics some suggestions.

### Inconsistent docs and src folder

I think that every top level folder (component) in the src folder should be in the docs. 

**Not in docs but in src folder**
* Copy *(move inside CopyButton?)*
* FormGroup *(rename to InputGroup? it can be misinterpreted as a group of forms, which is obviouly not... see Bootstrap's naming)*
* FormItem *(rename to InputItem?)*
* FormLabel *(rename to Label?)*
* ListBox
* ListItem
* RadioButtonGroup *(move inside RadioButton? just like TileGroup is inside Tile)*
* UnorderedList *(I'm sure it was in the docs before...)*

**In docs but not in src folder**
* ButtonSet is inside Button (*move docs inside Button?*)
* ClickableTile, ExpandableTile, RadioTile, SelectableTile,  TileGroup are inside Tile 
* InlineNotification, ToastNotification are inside Notification *(move docs inside Notification?)*

### Inconsistent naming conventions

* RadioTile and SelectableTile are RadioButton and Checkbox equivalents
  * Proposal: RadioButtonTile, CheckboxTile
* Use only one word to represent groups (Set, Group or plural form)
  * Current: ButtonSet, RadioButtonGroup, Tabs
  * Proposal: ButtonGroup, RadioButtonGroup, TabGroup

### Restructuring both src and docs

* InlineLoading, Loading *(move to Loading?)*
 
### Other stuff

* Why RadioButtonGroup but no CheckboxGroup? It is mentioned as optional [here](https://www.carbondesignsystem.com/components/checkbox/usage/#main-elements) but I don't get why not have one
* Treeview component?
* NumberInput has no `inline` prop

**Comment by metonym** [comment]
These are great points – thank you for taking the time and providing feedback.

**Comment by metonym** [comment]
> Treeview component?

[TreeView](https://carbon-svelte.vercel.app/) added in [v0.39](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.39.0)
