### ISSUE TITLE
Dropdown catches Enter keydown event even when focused on other components

### ISSUE THREAD

**Issue by weaseldotro** [carbon-design-system/carbon-components-svelte#739]
https://codesandbox.io/s/goofy-violet-ntt5k?file=/App.svelte

Click on the username text input, type something, then type Enter. The form should submit, but instead the dropdown catches the Enter keydown event and opens the dropdown. The focus stays on the text input, using the arrow keys has an effect on the input, not on the dropdown. Pressing Enter again while still focused on the text input will again be caught by the dropdown and it will close.

**Comment by inakidelamadrid** [comment]
is this bug fixed? I have the same problem.

**Comment by metonym** [comment]
Fixed in [v0.63.2](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.63.2)
