### ISSUE TITLE
[Question] Carbon all theme not working in Sveltekit production

### ISSUE THREAD

**Issue by ihsanmohamad** [carbon-design-system/carbon-components-svelte#743]
Hi, i have done theme switcher prior the 0.40 update. It is working in dev, however in production the theme are not working. After 0.40 update, i make use of the Theme component and the result are the same which works in dev but not in production. What should i do to make it working?

Here is my svelte.config.js

```js
/** @type {import('@sveltejs/kit').Config} */
import { optimizeImports, optimizeCss } from "carbon-preprocess-svelte";
import adapter from '@sveltejs/adapter-static';

const config = {
	kit: {
		// hydrate the <div id="svelte"> element in src/app.html
		adapter: adapter({
			// default options are shown
			pages: 'build',
			assets: 'build',
			fallback: null
		}),
		target: '#svelte',
		vite: {
			plugins: [
				process.env.NODE_ENV === "production" && optimizeCss(),
			],
		  },
	},
	preprocess: [optimizeImports()],
	
};

export default config;

```

**Comment by metonym** [comment]
Which StyleSheet are you using?

The `Theme` component uses CSS variables, so it will only work with `carbon-components-svelte/css/all.css`.

**Comment by ihsanmohamad** [comment]
> Which StyleSheet are you using?
> 
> The `Theme` component uses CSS variables, so it will only work with `carbon-components-svelte/css/all.css`.

i'm using
```css
  @import "carbon-components-svelte/css/all";
```
with style lang="scss";

i have tried using normal style without the lang option and the result are the same

**Comment by metonym** [comment]
My next guess would be that the `optimizeCss` strips away CSS needed for dynamic theming. What happens if you remove that plugin when building for production?

**Comment by ihsanmohamad** [comment]
i have tried that too with no luck as well. It's ok, i will try again with new sveltekit project later. I think it is because of the production css too as the html theme props are changing as i change the theme in the inspect tool. 

Thanks for your help

**Comment by denizkenan** [comment]
Having same issue.

**Comment by DavidM42** [comment]
I am struggling with this issue too.
Did anyone figure out how to allow dynamic theming with svelteKit production builds?

**Comment by metonym** [comment]
@DavidM42 Could you provide a minimal repo? Happy to take a further look

**Comment by DavidM42** [comment]
Thanks for your super quick answer :heart:. Went immediately to work creating a minimal repo but there it worked just fine :eyes: .
So **false alarm**. In the end, I found the error in my repo. I forgot another [import of the theme file white.css in my error page](https://github.com/DavidM42/ects/commit/46a9fdef0bc39698bad3d609d91be0cb76f8c030#diff-3c1e547854be97d353f19baadd10ed5619928b9384ab12de4b0a7c88311fbb6dL14) which collided with my `all.css` import but only on production builds not on dev previews.

Lesson learned, minimum viable project makes sense to debug sometimes.

For others stumbling upon this issue:
Check in your editor if you find multiple matches for the search
```
import 'carbon-components-svelte/css/
```
and then make sure to only import **either the theme you want or `all.css`**
