### ISSUE TITLE
DatePicker Popup is positioned wrong when inside dialog. 

### ISSUE THREAD

**Issue by mikerussellnz** [carbon-design-system/carbon-components-svelte#753]
When a datepicker is placed inside a modal / composed dialog the picker part is positioned incorrectly. 

Screenshot below, it seems that the calculation of the position of the picker is being calculated relative to the top left of the screen, but it is being positioned relative to the top left of the dialog. :-(

![datepicker](https://user-images.githubusercontent.com/627852/125935327-507e3687-b881-4636-b661-aa31531e5078.png)

**Comment by mikerussellnz** [comment]
I found that the fix is to set static: true on the calendar config options passed to flatpickr. 
` calendar = await createCalendar({
      options: {
        appendTo: datePickerRef,
        dateFormat,
        defaultDate: $inputValue,
        locale,
        maxDate,
        minDate,
        mode: $mode,
	static: true  // <<< This line
      },`

Result:
![datepicker2](https://user-images.githubusercontent.com/627852/125937074-4450ba8b-3f01-46a1-889e-3a02096245cc.png)

**Comment by insasho** [comment]
> I found that the fix is to set static: true on the calendar config options passed to flatpickr.

@mikerussellnz I am also experiencing this problem. Can you share your workaround showing how to pass static: true through to the flatpickr instance used by carbon-components-svelte?

**Comment by metonym** [comment]
Supported in [v0.44.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.44.0).

Override/customize the `flatpickr` calendar options using `flatpickrProps`.

```svelte
<script>
  import { DatePicker, DatePickerInput } from "carbon-components-svelte";
</script>

<DatePicker
  datePickerType="single"
  flatpickrProps="{{ static: true }}"
  on:change
>
  <DatePickerInput labelText="Meeting date" placeholder="mm/dd/yyyy" />
</DatePicker>
```

See https://flatpickr.js.org/options for a full list of options.
