### ISSUE TITLE
Input values are not "binding" to variables

### ISSUE THREAD

**Issue by andregoldstein** [carbon-design-system/carbon-components-svelte#764]
Hi there, I'm struggling to get TextInput and PasswordInput values to bind to simple variables. I must be doing something wrong here...

```
<script>
  import { Form, FormGroup, TextInput, PasswordInput, Button } from "carbon-components-svelte"
  let email = ""
  let password = ""
  
  $: disabled = !email || !password  

  function handleLogin() {...}
</script>

<Form on:submit={handleLogin}>

  <FormGroup>
    <TextInput labelText="Email address" placeholder="Enter your email address..." bind:value={email} />
  </FormGroup>
  
  <FormGroup>
    <PasswordInput labelText="Password" placeholder="Enter your password..." bind:value={password} />
  </FormGroup>
  
  <Button type="submit" {disabled}>Login</Button>
  
</Form>
```

**Comment by metonym** [comment]
I've created a [Svelte REPL](https://svelte.dev/repl/d0e3683b0d3a48be811a5f44e4e2e429?version=3.38.3) using the code you provided, and binding works for me.

**Comment by andregoldstein** [comment]
Thank you for taking the time to do this @metonym and apologies for the slow reply. The REPL does indeed work.

Hmm maybe it's something external messing with this. I'm using it inside Meteor but not sure that would be the issue.

I'll try and strip everything else back and rule them out, thanks again
