### ISSUE TITLE
Feature Request: Specify the size of tabs

### ISSUE THREAD

**Issue by ibilux** [carbon-design-system/carbon-components-svelte#774]
It would be great if the tabs size can be changed to various sizes (`size="sm"`) like (`type="container"`)

**Comment by metonym** [comment]
Do you mean the height of the tabs, or just the width?

**Comment by metonym** [comment]
Auto-width Tabs is supported in [v0.48.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.48.0).

[Example](https://carbon-components-svelte.onrender.com/components/Tabs#auto-width)

**Comment by ibilux** [comment]
> Auto-width Tabs is supported in [v0.48.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.48.0).
> 
> [Example](https://carbon-components-svelte.onrender.com/components/Tabs#auto-width)

Thank you @metonym. This is much better then using a custom overridden CSS styles.
