### ISSUE TITLE
Feature Request: Add a pretty Scroll Bar component.

### ISSUE THREAD

**Issue by ibilux** [carbon-design-system/carbon-components-svelte#775]
It would be great if carbon-components-svelte can use a modern pretty Scroll Bar component.

**Comment by brunnerh** [comment]
That should probably be part of the themes instead of being a component, so it would have to be in the styles of the flagship Carbon package (https://github.com/carbon-design-system/carbon).

**Comment by ibilux** [comment]
> That should probably be part of the themes instead of being a component, so it would have to be in the styles of the flagship Carbon package (https://github.com/carbon-design-system/carbon).
> 
> Edit: Just looked at the current state of the [standards for styling scrollbars](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars) and unfortunately widespread support is not there yet. For most browsers prefixed properties exist, but those usually should not be used.

Yeah, you are right. I used [this](https://www.digitalocean.com/community/tutorials/css-scrollbars) but it's not fully supported by all browsers.
