### ISSUE TITLE
ComboBox disabled props don't disable list to open

### ISSUE THREAD

**Issue by rafadess** [carbon-design-system/carbon-components-svelte#776]
Even if `disabled` is set to `true`, it is still possible to open ComboBox list by clicking on the right arrow.

It is possible to see this issue on [official documentation](https://carbon-svelte.vercel.app/components/ComboBox), under Disabled subheading.

PR is comming if it is welcome 😃

**Comment by metonym** [comment]
PRs welcome

**Comment by rafadess** [comment]
Wow! I was working on this right now! Perfect timing 😅

**Comment by metonym** [comment]
Fixed in [v0.44.1](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.44.1)
