### ISSUE TITLE
Error: UMD and IIFE output formats are not supported for code-splitting builds caused by DatePicker

### ISSUE THREAD

**Issue by gforcedev** [carbon-design-system/carbon-components-svelte#778]
Really enjoying the framework so far, but one of the key reasons I chose it, the `DatePicker`, is causing me some problems. When I import it into a file, my project starts failing to compile with `Error: UMD and IIFE output formats are not supported for code-splitting builds`.

I set up the svelte project with degit - packages installed:
```json
  "devDependencies": {
    "@rollup/plugin-commonjs": "^17.0.0",
    "@rollup/plugin-json": "^4.1.0",
    "@rollup/plugin-node-resolve": "^11.0.0",
    "carbon-components-svelte": "^0.42.2",
    "rollup": "^2.3.4",
    "rollup-plugin-css-only": "^3.1.0",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.0.0",
    "rollup-plugin-terser": "^7.0.0",
    "svelte": "^3.38.3"
  },
  "dependencies": {
    "carbon-icons-svelte": "^10.36.0",
    "firebase": "^8.7.1",
    "rxfire": "^4.0.0",
    "rxjs": "^7.2.0",
    "sirv-cli": "^1.0.0"
  }
```

Would appreciate any help with getting this working.

**Comment by gforcedev** [comment]
Node v12, npm v6

**Comment by metonym** [comment]
Try adding `inlineDynamicImports: true` in your exported rollup.config.js.

**Comment by gforcedev** [comment]
This fixed it thank you so much!
