### ISSUE TITLE
position label

### ISSUE THREAD

**Issue by zfranco55** [carbon-design-system/carbon-components-svelte#781]
is it possible to place the component label (eg InputText) on the left, instead of top?

**Comment by weaseldotro** [comment]
I don't think you can. The workaround is to not use a label for the component and add a separate element for the label.

**Comment by metonym** [comment]
Not sure if this is what you're looking for, but some labelled components have an inline variant:  https://carbon-components-svelte.onrender.com/components/TextInput#inline-variant
