### ISSUE TITLE
Export ToolbarBatchActions Cancel button text

### ISSUE THREAD

**Issue by elvuel** [carbon-design-system/carbon-components-svelte#782]
https://github.com/carbon-design-system/carbon-components-svelte/blob/abfc472c82d7331d96dfdff504aeb8d9864cc9d2/src/DataTable/ToolbarBatchActions.svelte#L54

Make the cancel button text reactive or slot cancel?

**Comment by metonym** [comment]
Fixed in [v0.44.1](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.44.1)

Override the "Cancel" text by using a the "cancel" slot.

```svelte
<ToolbarBatchActions>
  <svelte:fragment slot="cancel">Terminate</svelte:fragment>
</ToolbarBatchActions>
```
