### ISSUE TITLE
What's the difference between Modal and ComposedModal?

### ISSUE THREAD

**Issue by Florian-Schoenherr** [carbon-design-system/carbon-components-svelte#784]
ComposedModal also doesn't work in svelte-kit, possibly because of `onDestroy` using `document`?

**Comment by metonym** [comment]
> ComposedModal also doesn't work in svelte-kit, possibly because of `onDestroy` using `document`?

Fixed by https://github.com/carbon-design-system/carbon-components-svelte/pull/914

**Comment by michahell** [comment]
still does not answer the question :)
