### ISSUE TITLE
I don't get why changing the theme doesn't change the SideNav background-color

### ISSUE THREAD

**Issue by Pierre-Monier** [carbon-design-system/carbon-components-svelte#787]
After testing CarbonTheme, I run through something weird. Changing theme as no effect on the SideNav background color :thinking: . It doesn't seem to be a bug, so I'm asking why it's working like that ? If the user choose to set a dark theme, I think it's annoying for him to have a full white SideNav component when he clicks on the hamburger menu. What was the idea behind that ?

I [made a sandbox](https://codesandbox.io/embed/suspicious-euclid-3bb43?fontsize=14&hidenavigation=1&theme=dark) to demonstrate

**Comment by dqzx** [comment]
The core carbon project haven't supported themes on the sidebar yet. See my response https://github.com/carbon-design-system/carbon-components-svelte/issues/762#issuecomment-885484991 to a similar question for a workaround.

**Comment by codeinforest** [comment]
> After testing CarbonTheme, I run through something weird. Changing theme as no effect on the SideNav background color 🤔 . It doesn't seem to be a bug, so I'm asking why it's working like that ? If the user choose to set a dark theme, I think it's annoying for him to have a full white SideNav component when he clicks on the hamburger menu. What was the idea behind that ?
> 
> I [made a sandbox](https://codesandbox.io/embed/suspicious-euclid-3bb43?fontsize=14&hidenavigation=1&theme=dark) to demonstrate

Seem current version not has any props to do that, but you can change background by this way:
```
  :global(.bx--side-nav__navigation) {
    background-color: #111; /* Any HEX you want */
  }

  :global(.bx--side-nav__link .bx--side-nav__icon svg) {
    fill: #fff; /* Any HEX you want */
  }
```

**Comment by metonym** [comment]
I believe the next major version of Carbon will [support a theme-able UI Shell](https://github.com/carbon-design-system/carbon/pull/8579).
