### ISSUE TITLE
Feature Request: Set the width of a column in DataTable

### ISSUE THREAD

**Issue by ibilux** [carbon-design-system/carbon-components-svelte#790]
Hello,
It would be nice if we can set the width of a column when setting the headers in `DataTable`. For example:
```
  headers={[
    { key: 'name', value: 'Name' },
    { key: 'protocol', value: 'Protocol', width='15%' },
    { key: 'port', value: 'Port', width='10rem' },
    { key: 'rule', value: 'Rule', minWidth='10rem' }
  ]}
```

**Comment by metonym** [comment]
Released in [v0.64.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.64.0).

https://carbon-components-svelte.onrender.com/components/DataTable#custom-column-widths
