### ISSUE TITLE
Clear ComboBox programmatically

### ISSUE THREAD

**Issue by rafadess** [carbon-design-system/carbon-components-svelte#791]
I'm trying to clear the selection of the ComboBox programmatically but I'm not being able to. I tried to set `selectedIndex = -1` and `value = ''` still it didn't work. 

Looking at the code, I saw that there are a couple actions that must happen to clear the combobox. So I would like to suggest creating a clear function that would be triggered if `selectedIndex = -1`. Something like:
```
function clear() {
    selectedIndex = -1;
    highlightedIndex = -1;
    open = false;
    inputValue = '';
    ref?.focus();
  }
```

and add it to this reactive statement:
```
$: if (selectedIndex > -1) {
    selectedId = items[selectedIndex].id;
    dispatch("select", { selectedId, selectedIndex, selectedItem });
  } else {
    clear()
  }
```

I will be more than happy to create a PR with this idea. What you folks think?

**Comment by gforcedev** [comment]
I am also currently struggling to reset the value of a combobox on a form submit. This would definitely help!

**Comment by renefournier** [comment]
Here, too! Please & thank you!

**Comment by DaleCam** [comment]
I need this too!

**Comment by jackiewongjw** [comment]
Same here. Please consider this change. Thanks!

**Comment by rafadess** [comment]
I've created the PR. We really need a way to clear the ComboBox. So we will be very happy if you guys review it. 
Here is the PR: #804 

Thank you very much for considering.

**Comment by rafadess** [comment]
The mentioned PR was merged. Check the docs to see how to clear the combobox programmatically. Closing the issue.
