### ISSUE TITLE
is there any way to add dark mode?

### ISSUE THREAD

**Issue by jatinhemnani01** [carbon-design-system/carbon-components-svelte#792]

**Comment by rafadess** [comment]
@jatinhemnani01 I think carbon has already. Is it the gray100 theme that you are looking for?

[Under Styling.](https://carbon-svelte.vercel.app/)

**Comment by jatinhemnani01** [comment]
Yeah. It's supported for all the components?

**Comment by rafadess** [comment]
Yes. On the docs, if you switch the them it will be preserved while you are navigating on the other components. so you can see how they would like. Also, under each component you can switch the theme.
