### ISSUE TITLE
Can I import dark theme CSS in __layout.svelte file and will it work on that route?

### ISSUE THREAD

**Issue by jatinhemnani01** [carbon-design-system/carbon-components-svelte#793]

**Comment by metonym** [comment]
I believe styles in `__layout.svelte` files are applied globally.

You'll probably need to [reset the layout](https://kit.svelte.dev/docs#layouts-resets) if you want to use different themes for different routes.

**Comment by metonym** [comment]
I think a better option would be to use dynamic theming through `all.css` and programmatically update the theme in specific routes.

```js
$: if (typeof document !== 'undefined'). document.documentElement.setAttribute('theme', 'g90');
```
