### ISSUE TITLE
DataTable useStaticWidth title/description style bug

### ISSUE THREAD

**Issue by Florian-Schoenherr** [carbon-design-system/carbon-components-svelte#795]
![image](https://user-images.githubusercontent.com/65456722/130399529-7b42470a-6b9c-4d1b-9124-d18a4dd733f7.png)
will try to do a PR
edit: seems like this is an upstream issue and it will probably not get merged here if I "simply" fix it

**Comment by Florian-Schoenherr** [comment]
they fixed it upstream 😄

**Comment by Florian-Schoenherr** [comment]
not released yet, seems like they also have a pre-release version so it might take a while

**Comment by metonym** [comment]
Fixed in [v0.44.3](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.44.3)
