### ISSUE TITLE
Combobox input does not get the name passed in properties

### ISSUE THREAD

**Issue by LSchipperGroningen** [carbon-design-system/carbon-components-svelte#797]
The input name passed in the properties to the component doesn't get set in the input.

![image](https://user-images.githubusercontent.com/89142931/130583532-6c039a9a-c406-40c7-83e3-3175047e9020.png)

![image](https://user-images.githubusercontent.com/89142931/130583287-a484355b-0dae-45e3-aaf4-0d3bfdcfc670.png)

I need this name to be filled as I serialize the form it is in.

**Comment by metonym** [comment]
Fixed in [v0.52.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.52.0)
