### ISSUE TITLE
slot not working for labelText in RadioButton

### ISSUE THREAD

**Issue by airedwin** [carbon-design-system/carbon-components-svelte#799]
https://github.com/carbon-design-system/carbon-components-svelte/blob/abfc472c82d7331d96dfdff504aeb8d9864cc9d2/src/RadioButton/RadioButton.svelte#L70

I believe this line should be similar to the RadioButtonGroup in order for slot to work
`{#if labelText || $$slots.labelText}`

**Comment by metonym** [comment]
Released in [v042.3](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.42.3)
