### ISSUE TITLE
Not possible to define appendTo for DatePicker

### ISSUE THREAD

**Issue by BZembrodt-BP** [carbon-design-system/carbon-components-svelte#803]
This option was removed in PR #737.
Alternatively the flatpickr option "static" should be exposed.
Without either of these 2 options, it is not possible to correctly position the calendar if the DatePicker is placed in a position: relative element. (see: https://codesandbox.io/s/epic-lewin-vjky5)

It would be even better, if the DatePicker allowed to set a flatpickr options property that then gets merged with the default options. That way all options could be accessed if needed.

**Comment by metonym** [comment]
Supported in [v0.44.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.44.0).

Override/customize the `flatpickr` calendar options using `flatpickrProps`.

```svelte
<script>
  import { DatePicker, DatePickerInput } from "carbon-components-svelte";
</script>

<DatePicker
  datePickerType="single"
  flatpickrProps="{{ static: true }}"
  on:change
>
  <DatePickerInput labelText="Meeting date" placeholder="mm/dd/yyyy" />
</DatePicker>
```

See https://flatpickr.js.org/options for a full list of options.
