### ISSUE TITLE
Make icon prop types more compatible?

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#806]
Components with `icon` properties usually expect `typeof CarbonIcon | undefined` but could support other icon components as well.

E.g. I integrated icons from [svelte-codicons](https://github.com/metonym/svelte-codicons) as part of a custom title bar, but TS is not happy.

```svelte
<script lang="ts">
	import ChromeClose from 'svelte-codicons/lib/ChromeClose.svelte';
	import ChromeMaximize from 'svelte-codicons/lib/ChromeMaximize.svelte';
	import ChromeMinimize from 'svelte-codicons/lib/ChromeMinimize.svelte';
	import ChromeRestore from 'svelte-codicons/lib/ChromeRestore.svelte';
</script>

<!-- ... other buttons ... -->
<HeaderGlobalAction icon={ChromeClose} class="window-close-button"
	on:click={onWindowClose}/>
```

> Type 'typeof ChromeClose' is not assignable to type 'typeof CarbonIcon'. ts(2322)

It builds and displays fine:
![image](https://user-images.githubusercontent.com/834235/131737105-38eb0028-0974-465f-8dd9-edbdf83f7296.png)

**Comment by metonym** [comment]
Agreed. It should be more loosely typed
