### ISSUE TITLE
ContextMenu, limit to div

### ISSUE THREAD

**Issue by Sheepux** [carbon-design-system/carbon-components-svelte#811]
I've done a contextualised contextmenu, meaning that i can handle on wich div it appears instead of appearing on all my page (outside of my rendered component).
I was wondering if it's the correct way to handle it or if i should have used the contextMenu differently.

That's probably something that could be introduced as a new prop "limitTo" (HtmlElement).
```javascript
<script>
// Context Menu
    let itemsdiv: HTMLElement;
    let pos = { x: 0, y: 0 };
    let showMenu = false;

    async function onRightClick(event: any) {
        if (showMenu) {
            showMenu = false;
            await new Promise((res) => setTimeout(res, 100));
        }
        pos = { x: event.clientX, y: event.clientY };
        showMenu = true;
    }

    document.addEventListener(
        "contextmenu",
        function (event: any) {
            if (event.target === itemsdiv || itemsdiv.contains(event.target)) {
                event.preventDefault();
                return;
            }
            showMenu = false;
        },
        true
    );
</script>
```
manually handing menu opening because of manual event handling
```html
{#if showMenu}
    <ContextMenu open={showMenu} x={pos.x} y={pos.y}>
 ```
 Specifying the desired div
 ```html
 <div  bind:this={itemsdiv} on:contextmenu={onRightClick} >
 ```
 I havent tried to PR
 I guess i would have to change[ something here ](https://github.com/carbon-design-system/carbon-components-svelte/blob/master/src/ContextMenu/ContextMenu.svelte#L83) to check if we're inside the limitTo prop

**Comment by metonym** [comment]
In [version 0.50](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.50.0), you can now pass custom elements as trigger targets to `ContextMenu`

Example: https://carbon-components-svelte.onrender.com/components/ContextMenu#custom-target

**Comment by Sheepux** [comment]
I believe the example should have 3 div to show that you can have different menus (and share 1):
DIV1 (menuA) DIV2 (menuA) DIV3 (menuB)
I'll test it later. Thanks a lot for this one 👍
