### ISSUE TITLE
[Request] 3D Icon Module

### ISSUE THREAD

**Issue by codeinforest** [carbon-design-system/carbon-components-svelte#813]
I find a 3d icon on `https://www.carbondesignsystem.com/guidelines/icons/library/` but cannot use with Svelte cause current package not include 3D icons. Please add it soon, thank you!

**Comment by metonym** [comment]
@codeinforest  Which icons are you referring to? `carbon-icons-svelte` is already built using the next available `@carbon/icons` version.

**Comment by metonym** [comment]
@codeinforest I believe the module name is `WatsonHealth3DSoftware20`.

From the [visual preview](https://carbon-design-system.github.io/carbon-icons-svelte/):

![3d-software](https://user-images.githubusercontent.com/10718366/132366797-bd64485e-b1f5-409e-a7e1-7bf850a1d718.png)

Code:

```svelte
<script>
  import WatsonHealth3DSoftware20 from "carbon-icons-svelte/lib/WatsonHealth3DSoftware20";
</script>

<WatsonHealth3DSoftware20 />
```

**Comment by codeinforest** [comment]
> @codeinforest I believe the module name is `WatsonHealth3DSoftware20`.
> 
> From the [visual preview](https://carbon-design-system.github.io/carbon-icons-svelte/):
> 
> ![3d-software](https://user-images.githubusercontent.com/10718366/132366797-bd64485e-b1f5-409e-a7e1-7bf850a1d718.png)
> 
> Code:
> 
> ```svelte
> <script>
>   import WatsonHealth3DSoftware20 from "carbon-icons-svelte/lib/WatsonHealth3DSoftware20";
> </script>
> 
> <WatsonHealth3DSoftware20 />
> ```

That's great! I don't know that link. Thank you!
