### ISSUE TITLE
ComboBox "clear" event unexpectedly fires too many times

### ISSUE THREAD

**Issue by phil-mayer** [carbon-design-system/carbon-components-svelte#817]
First off, I wanted to say thank you to all contributors for this great component library. It has some great momentum!

I'm seeing an issue where the `ComboBox` component is firing `clear` events unexpectedly. The culprit is [this block](https://github.com/carbon-design-system/carbon-components-svelte/commit/dfc00f6668435f43b906e25ec936286286625c64#diff-3450feee793c0d5e0d3379e9987f16a04303de98f39f94416a5ea37f4daf9c31R151-R154). Steps to Reproduce:

1. Create a `ComboBox`, but do not set the `selectedIndex`.
2. Trigger some change (besides selecting a list item) that causes a re-render. For example, add a handler for the `on:keyup` event that changes the underlying list of `items` (essentially typeahead behavior).

The reactive statement linked above will fire, causing the `ComboBox`'s internal `inputValue` to be cleared. Overall, I don't understand the intent behind the `else` block -- it seems to clear the input whenever an option isn't selected.

**Comment by metonym** [comment]
Indeed, it seems that the `clear` function should only be invoked inside `on:clear` and there should be no need to both dispatch and forward the "clear" event.

**Comment by metonym** [comment]
Released in [v0.44.2](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.44.2)

**Comment by phil-mayer** [comment]
Thanks for the speedy resolution @metonym!
