### ISSUE TITLE
Performance issue when page contains many TooltipDefinition components.

### ISSUE THREAD

**Issue by GiacomoRandazzo** [carbon-design-system/carbon-components-svelte#820]
Hey, 

First of all thank you for your great work!

Sometimes in our app we have 1000+ `TooltipDefinition` components around the page.
Each component register a `keydown` event on `window`, see [lines 34-38 in TooltipDefinition.svelte](https://github.com/carbon-design-system/carbon-components-svelte/blob/abfc472c82d7331d96dfdff504aeb8d9864cc9d2/src/TooltipDefinition/TooltipDefinition.svelte#L34-L38).

This causes performance issues, each time I press a key it hangs for 100ms or more, which is not ideal. That's because all the event listeners fire.

I'd love to have the option to disable the feature altogether. 

Happy to open a PR.

**Comment by metonym** [comment]
Feel free to open a PR – I'd be interested to see the approach, and I don't see any harm in having a prop to opt out of adding the listener.

**Comment by metonym** [comment]
After investigating further, I wasn't able to repro the behavior that you described.

In this experiment, this REPL renders 1000 tooltip definition components with a button to toggle all tooltips. Pressing the Escape key doesn't appear to cause any significant delay.

https://svelte.dev/repl/cb6dd8417b234352bb3679adb7c17d48?version=3.48.0

```svelte
<script>
  import { TooltipDefinition } from "carbon-components-svelte";
	
  let open = false;
</script>

<button on:click={() => { open = !open }}>
  Toggle all
</button>

{#each Array.from({ length: 1000 }) as item}
  <TooltipDefinition
    bind:open
    tooltipText="IBM Corporate Headquarters is based in Armonk, New York."
  >
    Armonk
  </TooltipDefinition>
{/each}
```

Feel free to re-open this with a repro.
