### ISSUE TITLE
Datepicker iframe placement incorrect in a modal

### ISSUE THREAD

**Issue by LSchipperGroningen** [carbon-design-system/carbon-components-svelte#833]
![image](https://user-images.githubusercontent.com/89142931/135582177-06653dad-bae9-4a9c-b042-ae62f6ab32a9.png)

The iframe of the datepickers does not get placed correctly when used in a Modal using 0.44.4.

My code:

```
<script>
  import { Button, DatePicker, DatePickerInput, Form, Modal } from "carbon-components-svelte";
  let isOpen = false;
</script>

<Button on:click={() => {isOpen = true}}></Button>
<Modal open={isOpen}>
  <Form>
    <DatePicker datePickerType="single" on:change>
      <DatePickerInput labelText="End date" placeholder="mm/dd/yyyy" />
    </DatePicker>
  </Form>
</Modal>
```

Outside a modal it works as expected:
![image](https://user-images.githubusercontent.com/89142931/135583931-16e3a029-c060-4bf1-9c46-901bb64546c0.png)

**Comment by metonym** [comment]
I believe this was addressed by https://github.com/carbon-design-system/carbon-components-svelte/pull/794

Try passing `flatpickrProps={{ static:true }}` to the `DatePicker` component.

**Comment by LSchipperGroningen** [comment]
That works splendidly! Thanks :)
