### ISSUE TITLE
Property 'offsetHeight' does not exist on type 'IntrinsicAttributes & RowProps'

### ISSUE THREAD

**Issue by yyywork** [carbon-design-system/carbon-components-svelte#837]
I was trying to bind my local variable to offsetHeight in a IBM component, but it shows "Property 'offsetHeight' does not exist on type 'IntrinsicAttributes & RowProps'"... and the variable returns undefined.

`<Grid noGutter={false}>
    <Row bind:offsetHeight={height} >
    ...
    </Row>
</Grid>`  like it

Type '{ class: string; offsetHeight: any; }' is not assignable to type 'IntrinsicAttributes & RowProps'.
  Property 'offsetHeight' does not exist on type 'IntrinsicAttributes & RowProps'.   error shows on bind:offsetHeight

thank for your patience!

**Comment by metonym** [comment]
The `Row` component does not expose an `offsetHeight` property to bind to.

Try using the `Row` slot by enabling `as` instead:

```svelte
<script>
  import { Row } from "carbon-components-svelte";

  let ref = null;

  $: if (ref) console.log(ref.offsetHeight);
</script>

<Row as let:props>
  <div {...props} bind:this={ref}>...</div>
</Row>
```

**Comment by yyywork** [comment]
it works, thank you so much!
