### ISSUE TITLE
Sorting a DataTable with null values throws an unrecoverable error

### ISSUE THREAD

**Issue by malinowskip** [carbon-design-system/carbon-components-svelte#843]
In the DataTable component, if a cell value is `null`, sorting rows by the cell’s column results in an error.
```js
// Browser console output
Uncaught (in promise) TypeError: itemA is null
    sortedRows DataTable.svelte:2979
    update DataTable.svelte:184
    update internal.js:737
    flush internal.js:709
```

The problem can be fixed by handling null values before they are passed to the compare functions.

```js
// DataTable.svelte

...
const itemA = ascending
  ? resolvePath(a, sortKey, "")
  : resolvePath(b, sortKey, "");
const itemB = ascending
  ? resolvePath(b, sortKey, "")
  : resolvePath(a, sortKey, "");

// Handle null values here
if (itemA === itemB) return 0;
if (!itemA) return -1;
if (!itemB) return 1;
...
```

**Comment by metonym** [comment]
Thanks for reporting this bug.

What do you think about using [optional chaining operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) on [this line](https://github.com/carbon-design-system/carbon-components-svelte/blob/master/src/DataTable/DataTable.svelte#L197)?

```diff
- return itemA.toString().localeCompare(itemB.toString(), "en", { numeric: true });
+ return itemA?.toString().localeCompare(itemB?.toString(), "en", { numeric: true });
```

**Comment by malinowskip** [comment]
Thanks, just tested it and it works fine. One thing to note about this approach is that it always leaves null/undefined values at the top. I’m not sure what the best practices are in terms of ordering empty values. Do you have any thoughts on this?

**Comment by metonym** [comment]
From a UX standpoint, I would expect "empty" values to be last, whether sorting ascending/descending.

**Comment by metonym** [comment]
@malinowskip Nice! Would you like to submit a PR?
