### ISSUE TITLE
Multiselect doesn’t lose focus on some "click outside" events (Chrome, Edge)

### ISSUE THREAD

**Issue by malinowskip** [carbon-design-system/carbon-components-svelte#848]
*Note: Only occurs in Chrome and Edge; works fine in Firefox and Safari*

After clicking on a button when a [MultiSelect](https://carbon-components-svelte.onrender.com/components/MultiSelect) element is in focus, the following things happen:

- the `MultiSelect` component does not lose focus;
- in some cases, the expected `click` event is not dispatched;
- the page jumps to the top.

This doesn’t happen for each button component, e.g. [Button](https://carbon-components-svelte.onrender.com/components/Button) fires a `click` event, in which case MultiSelect still doesn’t lose its focus state.

https://user-images.githubusercontent.com/47485431/137010805-604e1f2e-7376-4181-be75-ffe482020cc9.mov

**Comment by malinowskip** [comment]
I’ve found what’s causing this issue.

### Easiest way to reproduce
1. Open Chrome;
2. Open the [MultiSelect page](https://carbon-components-svelte.onrender.com/components/MultiSelect);
3. Open any MultiSelect component on the page;
4. Scroll down and click on any CopyButton on the page.

The button won’t work and the page will jump back up to the MultiSelect component.

### Cause
The issue is caused by the `on:blur` handler [on this line](https://github.com/carbon-design-system/carbon-components-svelte/blob/07655aed3ed983e5dd734913ac10417b121b386b/src/MultiSelect/MultiSelect.svelte#L419).

**Comment by metonym** [comment]
Related #938, #1024

**Comment by metonym** [comment]
Fixed in [v0.58.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.58.0)
