### ISSUE TITLE
DatePicker locale type compatibility

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#855]
The `locale` property is passed to flatpickr, which supports locale names and custom locale objects. The property is currently typed as `string`, though.

```svelte
<script>
    // ...
    import { Russian } from "flatpickr/dist/l10n/ru.js"
</script>

<DatePicker locale={Russian}><!-- ... --></DatePicker>
```

A workaround for the type error would be to use `flatpickrProps` and set `locale` there, which is currently not documented.

In general it would be nice to have better documentation around correctly localizing the `DatePicker`, which requires adjusting the locale, `DatePicker.dateFormat` and `DatePickerInput.pattern` to work properly.

**Comment by metonym** [comment]
Fixed in [v0.48.1](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.48.1).

DatePicker `locale` is now strongly typed to support the following:

```svelte
<script lang="ts">
  import { DatePicker } from "carbon-components-svelte";
  import { Russian } from "flatpickr/dist/l10n/ru.js";
</script>

<!-- imported locale -->
<DatePicker
  locale="{Russian}"
  datePickerType="single"
>
  ...
</DatePicker>

<!-- locale short code -->
<DatePicker
  locale="ru"
  datePickerType="single"
>
  ...
</DatePicker>
```
