### ISSUE TITLE
[Regression] Reactive tooltip example doesn't work

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon-components-svelte#872]
https://carbon-components-svelte.onrender.com/components/Tooltip#reactive-example

Clicking the button to toggle the tooltip cannot close it.

**Comment by malinowskip** [comment]
This turned out to be really tricky, but I came up with a possible solution: https://github.com/malinowskip/carbon-components-svelte/commit/257cf816dce8909690a98a108877645d141fb6f7. All the examples seem to work.

**Comment by metonym** [comment]
@malinowskip Could you submit a PR? Would love to give it a try

**Comment by metonym** [comment]
Released in [v0.47.5](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.47.5)
