### ISSUE TITLE
DatePicker/DatePickerInput just loses focus on pressing Enter

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#876]
The `DatePickerInput` should probably:
- Submit enclosing form **or** toggle the date picker dropdown on pressing Enter
- Not lose focus without reason

Example ([REPL](https://svelte.dev/repl) compatible):

```svelte
<script>
	import { DatePicker, DatePickerInput } from 'carbon-components-svelte';
</script>

<svelte:head><link rel="stylesheet" href="https://unpkg.com/carbon-components-svelte/css/g100.css" /></svelte:head>

<form on:submit|preventDefault={()=> alert('submitted')}>
	<DatePicker datePickerType="single">
		<DatePickerInput labelText="Date" placeholder="Press Enter here"/>
	</DatePicker>
	
	<label>
		Native Input
		<input type="date"/>
	</label>
	
	<button>Submit</button>
</form>
```

For reference, try pressing Enter in the native date input.
The exact behavior for the native input appears to be browser dependent or there is some deviation from the spec.

I tested:
- Edge/Chrome: Submits form
- Firefox: Opens date picker dropdown

**Comment by metonym** [comment]
Fixed in [v0.50.5](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.50.5)
