### ISSUE TITLE
Add slots for InlineNotification title/subtitle

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#883]
Personally, I would like to add a link in the `subtitle` text, which is not possible via the text-based props.

Current workaround is using the default slot and adding the relevant subtitle class, e.g.:

```svelte
<InlineNotification {title}>
	<div class="bx--inline-notification__subtitle">
		Please <a href="/login">log in</a> first.
	</div>
</InlineNotification>
```

This is not ideal because when using a component library, access to these classes could be considered a leak of implementation details. I recently read that the prefix `bx` is might be changed, so this would need to be updated to prevent breakage in case this also applies to the Svelte components.

**Comment by metonym** [comment]
Released in [v0.49.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.49.0).

`InlineNotification` has slottable title/subtitle props.

```svelte
<InlineNotification>
  <strong slot="title">Error: </strong>
  <strong slot="subtitle">An internal server error occurred.</strong>
</InlineNotification>
```
