### ISSUE TITLE
Combobox two-way data binding doesn't clear value

### ISSUE THREAD

**Issue by nevvv** [carbon-design-system/carbon-components-svelte#886]
Say I have this block of code here:
```
<script>
  import { ComboBox } from "carbon-components-svelte";

  let option = '';

  function clearOption() {
  option = '';
  }
</script>

<ComboBox
  bind:value={option}
  titleText="Contact"
  placeholder="Select contact method"
  items={[{ id: '0', text: 'Slack' }, { id: '1', text: 'Email' }, { id: '2', text: 'Fax' }]}
/>

<button on:click={clearOption}></button>
```
The combobox is binded to option.
If I input words into the combobox and then reset the state of option, the input will have been cleared in state but my input will still be shown inside the combobox even though it is binded to option.

**Comment by metonym** [comment]
Would programmatically clearing the selection work for your use case? You can bind to the component instance and invoke the `clear` accessor:

```svelte
<script>
  import { ComboBox } from 'carbon-components-svelte';
	
  let option = '';
  let ref;
</script>

<ComboBox
  bind:this={ref}
  bind:value={option}
  titleText="Contact"
  placeholder="Select contact method"
  items={[{ id: '0', text: 'Slack' }, { id: '1', text: 'Email' }, { id: '2', text: 'Fax' }]}
/>

<button on:click={ref.clear}>Clear</button>
```

**Comment by nevvv** [comment]
Hey @metonym this method does indeed work however it has the added effect of focussing the combobox when cleared.
![image](https://user-images.githubusercontent.com/64247023/140004773-1dd346c2-ea86-477b-8110-0d9b79566c9e.png)

**Comment by metonym** [comment]
@nevvv The `selectedIndex` prop supports two-way binding.

[Svelte REPL](https://svelte.dev/repl/4b53e1aace70495093386898661b35b4)

```svelte
<script>
  import { ComboBox } from 'carbon-components-svelte';
	
  const items = [{ id: '0', text: 'Slack' }, { id: '1', text: 'Email' }, { id: '2', text: 'Fax' }];
	
  let selectedIndex = 1;
	
  $: value = items[selectedIndex];
</script>

<ComboBox
  bind:selectedIndex
  titleText="Contact"
  placeholder="Select contact method"
  {items}
/>

<button on:click={() => (selectedIndex = -1)}>Clear</button>
```

**Comment by metonym** [comment]
@nevvv [v0.52.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.52.0) added an option to not re-focus the input when triggering `ComboBox.clear`. Closing this but feel free to re-open if this doesn't address your use case.

**Usage**

```js
combobox.clear({ focus: false })
```

**Example**

```svelte
<script>
  import { ComboBox, Button } from "carbon-components-svelte";

  let combobox;
</script>

<ComboBox
  titleText="Contact"
  placeholder="Select contact method"
  bind:this={combobox}
  items={[
    { id: "0", text: "Slack" },
    { id: "1", text: "Email" },
    { id: "2", text: "Fax" },
  ]}
/>

<Button on:click={() => combobox.clear({ focus: false })}>Clear</Button>
```

[Docs](https://carbon-components-svelte.onrender.com/components/ComboBox#clear-selection)
