### ISSUE TITLE
ContentSwitcher is slow to render

### ISSUE THREAD

**Issue by TheophileMot** [carbon-design-system/carbon-components-svelte#887]
I have a page with a basic ContentSwitcher. On loading the page (or navigating away then back), there is a delay of about 0.25s before the first item is styled as the selected element. This causes a noticeable flicker every time the page is loaded, and it happens both in dev mode and in preview.

Is there any way to make the rendering more immediate?

```
<ContentSwitcher>
    <Switch>abc</Switch>
    <Switch>def</Switch>
    <Switch>ghi</Switch>
</ContentSwitcher>
```

**Comment by metonym** [comment]
Could you try setting an initial `selectedIndex`?

```svelte
<script>
  let selectedIndex = 0;
</script>

<ContentSwitcher bind:selectedIndex>
    <Switch>abc</Switch>
    <Switch>def</Switch>
    <Switch>ghi</Switch>
</ContentSwitcher>
```

**Comment by TheophileMot** [comment]
Ah, that didn't change anything, but it did get me to testing other components on the page, and I figured it out. The problem was an `<OverflowMenu open>` elsewhere on the page. Removing the `open` fixed the issue with the ContentSwitcher. (I only had it `open` for testing purposes, so this resolves the matter for me, but it looks like this interaction could still be considered a bug?)

Thanks for your help!

**Comment by metonym** [comment]
Glad to hear - a repro would be appreciated to debug this further

**Comment by TheophileMot** [comment]
Here's a minimal example:

```
<script lang="ts">
  import {
    ContentSwitcher,
    OverflowMenu,
    OverflowMenuItem,
    Switch,
  } from 'carbon-components-svelte';
</script>

<ContentSwitcher>
  <Switch>option 1</Switch>
  <Switch>option 2</Switch>
  <Switch>option 3</Switch>
</ContentSwitcher>

<OverflowMenu open>
  <OverflowMenuItem>a</OverflowMenuItem>
  <OverflowMenuItem>b</OverflowMenuItem>
  <OverflowMenuItem>c</OverflowMenuItem>
</OverflowMenu>
```

Put this on a page, and repeatedly navigate away then back to the page. It may take a few tries, but on my computer, the render is usually visibly slow.

Then remove `open` and try again; it should render normally now.

**Comment by metonym** [comment]
Closing as this issue seems to be related to the other library.
