### ISSUE TITLE
Datatable event on:click:row should not fire when clicking on the expander column

### ISSUE THREAD

**Issue by drjonathanbradley** [carbon-design-system/carbon-components-svelte#889]
I have a DataTable component with a list of data, and I've set up a on:click:row event that opens a modal with a form in it used to edit the data in that particular row. The data set in the DataTable has dynamic related data, and I would like to use the expander function of the DataTable to display that related data in rows underneath the parent entry. However, when I click on the expander chevron in the expander column, it still triggers the on:click:row event, opening the modal/form. It seems like since the expander column has a specific function it handles when clicked on, it shouldn't be included in the on:click:row event. If that's not the design intention, it would be nice to be able to exempt that column in some way. I tried using the on:click:row--expand event to customize this, and while on:click:row doesn't prevent on:click:row--expand from triggering, it does result in both functions triggering still.

**Comment by metonym** [comment]
@drjonathanbradley Can you give version 0.47.4 a try?

`click:row` should no longer fire in conjunction with `click:row--expand`.
