### ISSUE TITLE
Tooltip: reactive toggling doesn’t work if the tooltip icon is in focus

### ISSUE THREAD

**Issue by malinowskip** [carbon-design-system/carbon-components-svelte#894]
Unfortunately, I didn’t cover one possibility in https://github.com/carbon-design-system/carbon-components-svelte/pull/885. In the [reactive tooltip example](https://carbon-components-svelte.onrender.com/components/Tooltip/#reactive-example), toggling doesn’t work as intended if the icon is in focus.

https://user-images.githubusercontent.com/47485431/140752758-3306bdf4-d50a-4122-ae28-2401d46ce4dc.mov

**Comment by metonym** [comment]
Patched in [v0.47.6](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.47.6)
