### ISSUE TITLE
Threshold-Lines in line charts are rendered outside the chart and raise javascript error

### ISSUE THREAD

**Issue by usefool** [carbon-design-system/carbon-components-svelte#897]
When using threshold lines in line-chart, they are rendered outside the chart. The corresponding tooltip is shown in the right place. 

<img width="856" alt="Screen Shot 2021-11-09 at 16 32 42" src="https://user-images.githubusercontent.com/11616064/140955157-ded5debd-9762-4fe9-90ef-480efcaf3243.png">
t)

Additionally, I get this javascript error message:

<img width="530" alt="Screen Shot 2021-11-09 at 16 43 05" src="https://user-images.githubusercontent.com/11616064/140956265-271e1f18-0646-4ec1-9515-024844fb2a03.png">

Here is the corresponding axis configuration:
axes: {
      left: { mapsTo: "value",
      thresholds: [
          {
            value: 20,
            label: "My theshold"
          },
        ], 
      },
      bottom: {
        mapsTo: "date",
        scaleType: "time",
        
      },
    },

**Comment by metonym** [comment]
@usefool Hi there. A better place for this issue would be the [carbon-charts](https://github.com/carbon-design-system/carbon-charts/issues).

**Comment by usefool** [comment]
Ok, opened it there: https://github.com/carbon-design-system/carbon-charts/issues/1214
