### ISSUE TITLE
`TextInput type="number"` still produces string values

### ISSUE THREAD

**Issue by pheuter** [carbon-design-system/carbon-components-svelte#898]
Repro: https://svelte.dev/repl/3474e79c41a84da58b88976eeee751f5?version=3.44.1

**Comment by pheuter** [comment]
Likely has to do with this line: https://github.com/carbon-design-system/carbon-components-svelte/blob/81daaab1ff06f27bc1ec4132cf658113f2300a31/src/TextInput/TextInput.svelte#L178

`target.value` is always a string. According to svelte [docs](https://svelte.dev/docs#bind_element_property), numerical values should be coerced.

**Comment by pheuter** [comment]
Just now noticing there's a separate NumberInput component: https://carbon-svelte.vercel.app/components/NumberInput. To be fair, TextInput [docs](https://carbon-svelte.vercel.app/components/TextInput#props) specify that value can be a number as well.

**Comment by metonym** [comment]
It's still a valid assumption that `type="number"` should produce a number.

**Comment by metonym** [comment]
Patched in [v0.47.6](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.47.6)
