### ISSUE TITLE
HeaderAction doesn't work

### ISSUE THREAD

**Issue by mzztin** [carbon-design-system/carbon-components-svelte#908]
I am using the HeaderAction with a svelte-kit, but if I click it the HeaderPanel is not opening. Most of the code is copied from the UIShell example. I am importing the header file in my `src/routes/__layout.svelte.` The source code of the header file is this:
```svelte
<script>
	import {
	  Header,
	  HeaderUtilities,
	  HeaderAction,
	  HeaderPanelLinks,
	  HeaderPanelDivider,
	  HeaderPanelLink,
	  SkipToContent,
	} from "carbon-components-svelte";

	import { expoIn } from "svelte/easing";
  
	let isOpen = false;
</script>
  
  <Header company="IBM" platformName="Carbon Svelte">
	<div slot="skip-to-content">
	  <SkipToContent />
	</div>

	<HeaderUtilities>
	  <HeaderAction bind:isOpen>
		<HeaderPanelLinks>
		  <HeaderPanelDivider>Switcher subject 1</HeaderPanelDivider>
		  <HeaderPanelLink>Switcher item 1</HeaderPanelLink>
		  <HeaderPanelDivider>Switcher subject 2</HeaderPanelDivider>
		  <HeaderPanelLink>Switcher item 1</HeaderPanelLink>
		  <HeaderPanelLink>Switcher item 2</HeaderPanelLink>
		  <HeaderPanelLink>Switcher item 3</HeaderPanelLink>
		  <HeaderPanelLink>Switcher item 4</HeaderPanelLink>
		  <HeaderPanelLink>Switcher item 5</HeaderPanelLink>
		</HeaderPanelLinks>
	  </HeaderAction>
	</HeaderUtilities>
  </Header>
```

Did I do something wrong?

**Comment by metonym** [comment]
That looks right to me. This is what I see when I copy/paste that code in a SvelteKit project:

https://user-images.githubusercontent.com/10718366/141648116-1d083c85-c555-4178-8e07-2d89243d0229.mov

Does that match your expected behavior?

**Comment by mzztin** [comment]
> That looks right to me. This is what I see when I copy/paste that code in a SvelteKit project:
> 
>  _ui-shell.mov 
> Does that match your expected behavior?

Nope, right now I even realized that the button for PasswordInput is also not showing any results. Do you have any clues how this can happen?

**Comment by metonym** [comment]
Could you create a repro in the Svelte REPL (https://svelte.dev/repl) for easier debugging?

**Comment by mzztin** [comment]
It was actually a problem with a dependency I imported. I am sorry.
