### ISSUE TITLE
Popover inside an Accordion

### ISSUE THREAD

**Issue by keehun** [carbon-design-system/carbon-components-svelte#910]
Is there a known issue where using a `Popover` component inside an `Accordion` component can cause placement issues?

**Comment by metonym** [comment]
Could you provide a repro?

**Comment by keehun** [comment]
[Here's a basic svelte-kit empty template](https://www.dropbox.com/s/4j4vakrwbpjk0f8/popover-repro-thin.zip?dl=0) with a component called `CommentableContent` which has an icon link which when hovered over should present a popover.

I've placed this `CommentableContent` both inside and outside an `Accordion` but it doesn't seem to work either way.

**Comment by metonym** [comment]
@keehun Could you try upgrading to `carbon-components-svelte` [version 0.49.1](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.49.1)?

**Comment by keehun** [comment]
Interestingly enough, now it shows up "above the fold" so-to-speak. I can see the bottom shadow of it at the very top of the webpage. I've attached a screen capture of what I mean.

https://user-images.githubusercontent.com/77378/142433579-2e9301b9-e6a1-4ff3-85b3-7bd427c8e8d4.mov

**Comment by metonym** [comment]
Can you try adding a "position: relative" style to the containing `data-outline` div?

**Comment by keehun** [comment]
Aha! That's working now. Thanks!
