### ISSUE TITLE
HeaderNav is missing role

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#920]
The `HeaderNav` component should have an element with `role="menubar"` somewhere in its HTML.

[Spec for contained `menuitem` elements](https://www.w3.org/TR/wai-aria-1.1/#menuitem):

> Authors ***MUST*** ensure that menu items are owned by an element with role `menu` or `menubar` in order to identify that they are related widgets.

**Comment by metonym** [comment]
I believe the `role` attribute was intentionally removed upstream as it caused other accessibility issues: https://github.com/carbon-design-system/carbon/issues/7377#issuecomment-740826351

**Comment by brunnerh** [comment]
Should I raise the issue upstream then?

**Comment by metonym** [comment]
You can, but I think it was intentionally removed because of a11y violations

https://github.com/carbon-design-system/carbon/pull/7462
