### ISSUE TITLE
MultiSelect - show chosen value

### ISSUE THREAD

**Issue by keehun** [carbon-design-system/carbon-components-svelte#921]
Is it possible to show the chosen values when the dropdown menu is closed, like a "pill box" design that one might see when selecting tags in a blog post editor or selecting categories in a mapping application?

I've tried all the various props one can set on it, but it doesn't seem to be possible. Before giving up, I wanted to check here.

Example: https://miro.medium.com/max/1400/1*SdADE9YcNUJLMt9H12h1iw.png

**Comment by metonym** [comment]
Currently, it's not possible as it is by design (see https://github.com/carbon-design-system/carbon/issues/6953).

**Comment by keehun** [comment]
Ah, thanks @metonym. I don't understand what the linked issue shows about it being "by design". I assume there are no plans to add this feature? I suppose it could get complicated about what to do with overflow when many items are selected.

**Comment by metonym** [comment]
@keehun Are you looking for an ["input chips"](https://material.io/components/chips#types) pattern? I'm not sure if there are plans to support this but I think it would be a standalone component. It doesn't hurt to ask this in the upstream Carbon repo.

**Comment by keehun** [comment]
Ah! Yes, exactly. Thanks. Will ask in upstream carbon repo.
