### ISSUE TITLE
MultiSelect selecting wrong item when using keyboard navigation

### ISSUE THREAD

**Issue by keehun** [carbon-design-system/carbon-components-svelte#922]
In the Svelte REPL, I typed in the following:

```svelte
<link
      rel="stylesheet"
      href="https://unpkg.com/carbon-components-svelte/css/white.css"
    />

<script>
import { MultiSelect } from "carbon-components-svelte";
</script>

<MultiSelect
        filterable
  titleText="Applicable Attributes"
  placeholder="Type in composer attributes to include in the search"
  items={[{ id: '0', text: 'Slack' }, { id: '1', text: 'Email' }, { id: '2', text: 'Fax' }]}
						 />
```

When I type "Fa", press the down arrow key, then press Enter, I expect "Fax" to be the item that is selected. However, "Email" is the item that is actually selected. Same thing when I type "Sl" and press down and Enter to select "Slack". Again, "Email" is selected.

Am I using the keyboard navigation wrong? Wrong expectations? Or is it a bug?

Here's a video recording of what I'm talking about

https://user-images.githubusercontent.com/77378/143618029-f670716c-77f4-4f24-9f00-4b53c5f6c4c5.mov

**Comment by metonym** [comment]
Thanks for reporting this.

Fixed in [v0.50.2](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.50.2)
