### ISSUE TITLE
Do we have a Typography component

### ISSUE THREAD

**Issue by shepherd1530** [carbon-design-system/carbon-components-svelte#928]
Hello, I am looking to adopt this library for a new project and everything checks out except the presence of a typography component. I have read some issues on the repo suggesting the presence of this component but all efforts to do an import has proven futile. Do we have access to a typography component, and if yes how can I import it. Thanks.

**Comment by metonym** [comment]
Currently, there is no `Typography` component. However, CSS from `carbon-components` does apply default styles to semantic heading elements, like `h1`, `h2` etc..

What are you looking for in a typography component?

**Comment by shepherd1530** [comment]
> Currently, there is no `Typography` component. However, CSS from `carbon-components` does apply default styles to semantic heading elements, like `h1`, `h2` etc..
> 
> What are you looking for in a typography component?

I am looking for a more robust type system than what default html provides. i.e Muted text, Subtitle text, captions text e.t.c This was provided by a React library I used to work with and I am wondering if a similar component is available.
