### ISSUE TITLE
Datepicker calendar position is wrong

### ISSUE THREAD

**Issue by silver1bear** [carbon-design-system/carbon-components-svelte#931]
Hi,

I'm currently trying to use the Datepicker in a Form, but the position is always wrong, see attached image.
![datepickerwrong](https://user-images.githubusercontent.com/36518501/144746244-776ceec9-6b79-4774-91fe-6997b537d8b5.png)

Note that I zoomed out, when on 100% zoom, it's basically not visible at all.

I saw that in the ```flatpickr-datepicker``` the inline ```top``` and ```left``` values are the problem, but I don't know how to fix that.
The Datepicker is not directly in the ```Form```, but wrapped in another Svelte-component. It's also wrapped in an ```{#if}```, maybe that's important. 

[Source](https://github.com/silver1bear/buss-mvg/tree/Datepicker-bug)

**Comment by metonym** [comment]
Have you tried setting [`flatpickrProps` to include `static: true`](https://carbon-components-svelte.onrender.com/components/DatePicker#datepicker-in-a-modal)?

**Comment by silver1bear** [comment]
I hadn't and that fixed it.

Thanks a lot for the quick answer!
