### ISSUE TITLE
Take down or redirect from old documentation

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#932]
The older documentation page is still up here: https://carbon-svelte.vercel.app/
It probably should be taken down or redirect to the new one to prevent confusion: https://carbon-components-svelte.onrender.com/

**Comment by alkanna** [comment]
I second this, I sometimes realized a bit too late I was on the old version of the documentation.

**Comment by metonym** [comment]
https://carbon-svelte.vercel.app/ now redirects to https://carbon-components-svelte.onrender.com/
