### ISSUE TITLE
Clicking on a row checkbox fires a click:row event

### ISSUE THREAD

**Issue by alkanna** [carbon-design-system/carbon-components-svelte#933]
When using both a checkbox and on row click event, clicking a checkbox triggers the click:row event.
Area highlighted here should not be firing any events.
![CleanShot 2021-12-07 at 23 13 23](https://user-images.githubusercontent.com/30343764/145114322-aa6e7ad0-514e-4b11-b365-4ea8dceb8525.png)

**Comment by metonym** [comment]
Released in [v0.50.3](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.50.3)
