### ISSUE TITLE
TextInput bind variable set to undefined from code results "undefined" text in input field

### ISSUE THREAD

**Issue by patoi** [carbon-design-system/carbon-components-svelte#935]
Example:

https://svelte.dev/repl/130500ff57c1414ba4c0acfae1dfd42f?version=3.44.2

![image](https://user-images.githubusercontent.com/1846548/145528777-a13d36d6-abaf-40a8-9d4a-d2d7bbf63420.png)

**Comment by metonym** [comment]
Released in [v0.50.3](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.50.3)
