### ISSUE TITLE
Filterable dropdown triggers focus twice when clicking on arrow icon

### ISSUE THREAD

**Issue by alkanna** [carbon-design-system/carbon-components-svelte#940]
Everything's in the title :)
You can easily reproduce it on the filterable example here : https://carbon-components-svelte.onrender.com/components/MultiSelect

**Comment by DerekRoy** [comment]
Also affected by this. To illustrate the issue further: 

1. Click on MultiSelect arrow with filter enabled the event occurs twice flashing the dropdown content, then hiding it.  
2. Clicking anywhere outside the error brings up the multiselect drop down fine.

**Comment by metonym** [comment]
Hot fixed in [v0.50.4](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.50.4)
