### ISSUE TITLE
TextArea requires labelText prop to be set to use labelText slot

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#944]
In the component code there is an if statement preventing the slot from being rendered unless the `labelText` prop is set:

```svelte
  {#if labelText && !hideLabel}
    <label
      for="{id}"
      class:bx--label="{true}"
      class:bx--visually-hidden="{hideLabel}"
      class:bx--label--disabled="{disabled}"
    >
      <slot name="labelText">
        {labelText}
      </slot>
    </label>
  {/if}
```

The same seems to be true for other form inputs as well, e.g. `TextInput`.

**Comment by metonym** [comment]
Released in [v0.50.3](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.50.3)
