### ISSUE TITLE
customizing carbon elements on <style>

### ISSUE THREAD

**Issue by osmancoskun** [carbon-design-system/carbon-components-svelte#948]
i want to know how i can change some css properties of carbon elements at once from `<style>` . i can change the elements properties while using `<elementName style="border-radius:5px 5px 5px 5px;">` . but i want to do it for all elements that i choosed. when i try to write it like 
`<style>
.curvenblack{
      border-radius:5px 5px 5px 5px;
      color:black
}
</style>
`
this gives me an error that this `unused CSS selector ".curvenblack"`
when i try to use it with :global as you suggested on few other issues, it doesnt work. 
How can i work with it?

**Comment by metonym** [comment]
What is the issue with `:global`?

Often times, if no change is apparent, you may need to be more specific with the CSS selector.

E.g.,

```diff
- :global(.bx--link)
+ :global(a.bx--link)
```

**Comment by osmancoskun** [comment]
for example. i want to make borders curved of `TextInput` element from carbon. 
`<TextInput style="border-radius:5px 5px 5px 5px;"/>` works perfect. 
in-between `<style>` tags, it doesnt. 
so i use `:global(TextInput){border-radius:5px 5px 5px 5px;}` this one doesnt work. 
also `TextInput{border-radius:5px 5px 5px 5px;}` doesnt work. 
if i use css properties `.curvenblack{ border-radius:5px 5px 5px 5px;}` and add this to `<TextInput class="curvenblack"/>` this one doesnt work too. 
i just didnt understand why

**Comment by metonym** [comment]
"TextInput" is an invalid selector.

You'll need to target the actual underlying HTML element or class name. You can use your brower's dev tools to inspect the markup structure and classes in the DOM.

```css
:global(.bx--text-input) {
  border-radius:5px 5px 5px 5px;
}
```

**Comment by osmancoskun** [comment]
thanks for reply. it worked now. you saved me
