### ISSUE TITLE
Escape on DatePicker in Modal closes dialog and not only calendar dropdown

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#952]
When Escape is pressed, it should be checked whether the calendar is open, if so, the calendar should close and the event's propagation should be stopped so the dialog is not closed.

Steps to reproduce:
- Add `Modal` with `DatePicker` that has a calendar (`single` or `range`).
- Open dialog and click inside the date picker so the calendar is shown.
- Press Escape.

[REPL](https://svelte.dev/repl/f8571979cc4b46deab2fa7edf069670e?version=3.44.3)

**Comment by metonym** [comment]
Fixed in [v0.50.4](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.50.4)
