### ISSUE TITLE
Select $$restProps on wrong element/required missing.

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-components-svelte#964]
The `Select` component currently cannot be made required for form submissions. I intended to create a pull request to fix this, but noticed that this could either be achieved by...
- having the `$$restProps` apply to the `<select>` element rather than the root wrapper
- or add an explicit `required` property that is then applied to the `<select>`

Maybe even both. The code seems a bit inconsistent, e.g. TextInput has the props on the input while Checkbox has it on a wrapper element. Personally, I think it makes the most sense to always apply the rest props to the interactive element (input/select/textarea/button).

**Comment by metonym** [comment]
Released in [v0.51.1](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.51.1).
