### ISSUE TITLE
more than 1 modal and binding

### ISSUE THREAD

**Issue by osmancoskun** [carbon-design-system/carbon-components-svelte#975]
Hi everyone,
while im trying to add modal, i can see its binded on ```open``` variable in examples. when i change name of binded variable  or bind to another variable, it doesnt work. 
```
<script>
  import { Button, Modal } from "carbon-components-svelte";
  let open = false;
  let modalVisibility = false;
</script>
<main>
  <Header />
  <Sidebar />
  <Content>
    <Grid
      style="background-color:gray;border-radius:20px 20px 20px 20px; margin-top: -13px;padding:10px">
      <h3>Kullanicilar</h3>
      <Button
        on:click={() => (modalVisibility = true)}
        size="small"
        iconDescription="Login"
        icon={Add24}
      >SHOW</Button>
      <Modal
        bind:modalVisibility
        modalHeading="Create database"
        primaryButtonText="Confirm"
        secondaryButtonText="Cancel"
        on:click:button--secondary={() => (modalVisibility = false)}
        on:open
        on:close
        on:submit>
        <p>Create a new Cloudant database in the US South region.</p>
      </Modal>
    </Grid>
  </Content>
</main>
```

what should i do if want to add more than 1 modal in a single page?

**Comment by stilet** [comment]
```
<script lang="ts">
 let openModal: boolean = false;
  let openModal2: boolean = false;

</script>

{#if openModal}
<Modal
        bind:modalVisibility
        modalHeading="Create database"
        primaryButtonText="Confirm"
        secondaryButtonText="Cancel"
        on:click:button--secondary={() => (modalVisibility = false)}
        on:open
        on:close
        on:submit>
        <p>Create a new Cloudant database in the US South region.</p>
      </Modal>
{/if}
{#if openModal2}
<Modal
        bind:modalVisibility
        modalHeading="Create other database"
        primaryButtonText="Confirm"
        secondaryButtonText="Cancel"
        on:click:button--secondary={() => (modalVisibility = false)}
        on:open
        on:close
        on:submit>
        <p>Create a new Cloudant database in the US South region.</p>
      </Modal>
{/if}
```

**Comment by osmancoskun** [comment]
as i understand here, you try to enable/disable modals in if condition. when i click on button which makes this ```openModal``` and ```openModal2```  to ```true``` and also ```modalVisibility``` to ```true``` for each modal. but problem is i still have use ```open``` to use with ```bind``` when i try to use ```bind=modalVisibility2``` it gives me same error. nothing. and it doesnt work. i still have to use ```open``` for that. only way is for now, using open to bind for both of them but changing visibility of openModal variables i guess. thanks for reply

**Comment by metonym** [comment]
"modalVisibility" isn't a valid `Modal` prop. Do you mean to use `bind:open`?

**Comment by osmancoskun** [comment]
yes. but tried it already. in stilets reply, i realized that. used ```bind:open``` but i want to use more than 1 modal on a single page. with this, it doesnt work.

**Comment by metonym** [comment]
@osmancoskun I've added a "Multiple modals" example to the documentation site – hope it helps!

https://carbon-components-svelte.onrender.com/components/Modal#multiple-modals
