### ISSUE TITLE
Consider defaulting `flatpickrProps.static` to `true` in `DatePicker`

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon-components-svelte#985]
Related #833, #931, #953

There have been many cases where consumers use a `DatePicker` within a `Modal`. This requires the DatePicker to be statically positioned, instead of being appended to `document.body`.

This issue proposes setting `static` to `true` by default, while still allowing the consumer to override it.

**Comment by metonym** [comment]
Related #1256

**Comment by metonym** [comment]
`flatpickrProps.static` is now `true` by default in [v0.64.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.64.0)

**Comment by brunnerh** [comment]
I know that I suggested this, but maybe this should not be the default after all. Just noticed that if `static` is true, the calendar may extend the size of the container and require additional scrolling. This can easily come up in longer forms.

[REPL](https://svelte.dev/repl/5e4e854b1eda467f98d35d7db8de221c?version=3.48.0)

Maybe common pitfalls (like the usage within dialogs) could be addressed via a note in the documentation instead. I also think the flatpickr documentation itself could do a better job of addressing the tradeoffs involved with using `static`.
