### ISSUE TITLE
code-splitting error with DatePicker

### ISSUE THREAD

**Issue by rveciana** [carbon-design-system/carbon-components-svelte#986]
When using DatePicker / DatePickerInput, I get thins error:

`[!] Error: Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.`

It can be solved by adding 

`inlineDynamicImports: true`

in `rollup.config.js`, section `output`.

I think that the solution creates a single bundle, but at least adding this in the docs would be very helpful for other people finding the same error.

**Comment by metonym** [comment]
Related: #778

Nice catch – we should document this, and add it to the Rollup example at the very least.
