### ISSUE TITLE
Type `null | HTMLElement` is redundant as `HTMLElement` is already nullable

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon-components-svelte#996]
Some JSDoc types and TypeScript definitions for component props are currently typed as `null | HTMLDivElement`.

The `null` is redundant because `HTMLElement` types are already nullable.

**Comment by metonym** [comment]
Released in [v0.51.3](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.51.3)

**Comment by brunnerh** [comment]
> The `null` is redundant because `HTMLElement` types are already nullable.

That is not quite accurate. When using strict TS typing, `null` has to be declared explicitly to make things nullable. That being the case it probably would not hurt to have that explicitly in the type definitions if a prop can be null.

**Comment by metonym** [comment]
Oof. You're right. Setting `strict: true` will now emit an error.

**Comment by metonym** [comment]
Reverted in [v0.52.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.52.0)
